// Code generated by ent, DO NOT EDIT.

package holder

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldLTE(FieldID, id))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldAlias, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldName, v))
}

// Desc applies equality check predicate on the "desc" field. It's identical to DescEQ.
func Desc(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldDesc, v))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldDateUpdated, v))
}

// DateErased applies equality check predicate on the "date_erased" field. It's identical to DateErasedEQ.
func DateErased(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldDateErased, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldDateCreated, v))
}

// IdpSubject applies equality check predicate on the "idp_subject" field. It's identical to IdpSubjectEQ.
func IdpSubject(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldIdpSubject, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldTenantID, v))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.Holder {
	return predicate.Holder(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.Holder {
	return predicate.Holder(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.Holder {
	return predicate.Holder(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.Holder {
	return predicate.Holder(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.Holder {
	return predicate.Holder(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.Holder {
	return predicate.Holder(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.Holder {
	return predicate.Holder(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.Holder {
	return predicate.Holder(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.Holder {
	return predicate.Holder(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.Holder {
	return predicate.Holder(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.Holder {
	return predicate.Holder(sql.FieldContainsFold(FieldAlias, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Holder {
	return predicate.Holder(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Holder {
	return predicate.Holder(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Holder {
	return predicate.Holder(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Holder {
	return predicate.Holder(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Holder {
	return predicate.Holder(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Holder {
	return predicate.Holder(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Holder {
	return predicate.Holder(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Holder {
	return predicate.Holder(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Holder {
	return predicate.Holder(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Holder {
	return predicate.Holder(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Holder {
	return predicate.Holder(sql.FieldContainsFold(FieldName, v))
}

// DescEQ applies the EQ predicate on the "desc" field.
func DescEQ(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldDesc, v))
}

// DescNEQ applies the NEQ predicate on the "desc" field.
func DescNEQ(v string) predicate.Holder {
	return predicate.Holder(sql.FieldNEQ(FieldDesc, v))
}

// DescIn applies the In predicate on the "desc" field.
func DescIn(vs ...string) predicate.Holder {
	return predicate.Holder(sql.FieldIn(FieldDesc, vs...))
}

// DescNotIn applies the NotIn predicate on the "desc" field.
func DescNotIn(vs ...string) predicate.Holder {
	return predicate.Holder(sql.FieldNotIn(FieldDesc, vs...))
}

// DescGT applies the GT predicate on the "desc" field.
func DescGT(v string) predicate.Holder {
	return predicate.Holder(sql.FieldGT(FieldDesc, v))
}

// DescGTE applies the GTE predicate on the "desc" field.
func DescGTE(v string) predicate.Holder {
	return predicate.Holder(sql.FieldGTE(FieldDesc, v))
}

// DescLT applies the LT predicate on the "desc" field.
func DescLT(v string) predicate.Holder {
	return predicate.Holder(sql.FieldLT(FieldDesc, v))
}

// DescLTE applies the LTE predicate on the "desc" field.
func DescLTE(v string) predicate.Holder {
	return predicate.Holder(sql.FieldLTE(FieldDesc, v))
}

// DescContains applies the Contains predicate on the "desc" field.
func DescContains(v string) predicate.Holder {
	return predicate.Holder(sql.FieldContains(FieldDesc, v))
}

// DescHasPrefix applies the HasPrefix predicate on the "desc" field.
func DescHasPrefix(v string) predicate.Holder {
	return predicate.Holder(sql.FieldHasPrefix(FieldDesc, v))
}

// DescHasSuffix applies the HasSuffix predicate on the "desc" field.
func DescHasSuffix(v string) predicate.Holder {
	return predicate.Holder(sql.FieldHasSuffix(FieldDesc, v))
}

// DescEqualFold applies the EqualFold predicate on the "desc" field.
func DescEqualFold(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEqualFold(FieldDesc, v))
}

// DescContainsFold applies the ContainsFold predicate on the "desc" field.
func DescContainsFold(v string) predicate.Holder {
	return predicate.Holder(sql.FieldContainsFold(FieldDesc, v))
}

// LabelsIsNil applies the IsNil predicate on the "labels" field.
func LabelsIsNil() predicate.Holder {
	return predicate.Holder(sql.FieldIsNull(FieldLabels))
}

// LabelsNotNil applies the NotNil predicate on the "labels" field.
func LabelsNotNil() predicate.Holder {
	return predicate.Holder(sql.FieldNotNull(FieldLabels))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldLTE(FieldDateUpdated, v))
}

// DateErasedEQ applies the EQ predicate on the "date_erased" field.
func DateErasedEQ(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldDateErased, v))
}

// DateErasedNEQ applies the NEQ predicate on the "date_erased" field.
func DateErasedNEQ(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldNEQ(FieldDateErased, v))
}

// DateErasedIn applies the In predicate on the "date_erased" field.
func DateErasedIn(vs ...time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldIn(FieldDateErased, vs...))
}

// DateErasedNotIn applies the NotIn predicate on the "date_erased" field.
func DateErasedNotIn(vs ...time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldNotIn(FieldDateErased, vs...))
}

// DateErasedGT applies the GT predicate on the "date_erased" field.
func DateErasedGT(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldGT(FieldDateErased, v))
}

// DateErasedGTE applies the GTE predicate on the "date_erased" field.
func DateErasedGTE(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldGTE(FieldDateErased, v))
}

// DateErasedLT applies the LT predicate on the "date_erased" field.
func DateErasedLT(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldLT(FieldDateErased, v))
}

// DateErasedLTE applies the LTE predicate on the "date_erased" field.
func DateErasedLTE(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldLTE(FieldDateErased, v))
}

// DateErasedIsNil applies the IsNil predicate on the "date_erased" field.
func DateErasedIsNil() predicate.Holder {
	return predicate.Holder(sql.FieldIsNull(FieldDateErased))
}

// DateErasedNotNil applies the NotNil predicate on the "date_erased" field.
func DateErasedNotNil() predicate.Holder {
	return predicate.Holder(sql.FieldNotNull(FieldDateErased))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.Holder {
	return predicate.Holder(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.Holder {
	return predicate.Holder(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.Holder {
	return predicate.Holder(sql.FieldNotNull(FieldDateCreated))
}

// IdpSubjectEQ applies the EQ predicate on the "idp_subject" field.
func IdpSubjectEQ(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldIdpSubject, v))
}

// IdpSubjectNEQ applies the NEQ predicate on the "idp_subject" field.
func IdpSubjectNEQ(v string) predicate.Holder {
	return predicate.Holder(sql.FieldNEQ(FieldIdpSubject, v))
}

// IdpSubjectIn applies the In predicate on the "idp_subject" field.
func IdpSubjectIn(vs ...string) predicate.Holder {
	return predicate.Holder(sql.FieldIn(FieldIdpSubject, vs...))
}

// IdpSubjectNotIn applies the NotIn predicate on the "idp_subject" field.
func IdpSubjectNotIn(vs ...string) predicate.Holder {
	return predicate.Holder(sql.FieldNotIn(FieldIdpSubject, vs...))
}

// IdpSubjectGT applies the GT predicate on the "idp_subject" field.
func IdpSubjectGT(v string) predicate.Holder {
	return predicate.Holder(sql.FieldGT(FieldIdpSubject, v))
}

// IdpSubjectGTE applies the GTE predicate on the "idp_subject" field.
func IdpSubjectGTE(v string) predicate.Holder {
	return predicate.Holder(sql.FieldGTE(FieldIdpSubject, v))
}

// IdpSubjectLT applies the LT predicate on the "idp_subject" field.
func IdpSubjectLT(v string) predicate.Holder {
	return predicate.Holder(sql.FieldLT(FieldIdpSubject, v))
}

// IdpSubjectLTE applies the LTE predicate on the "idp_subject" field.
func IdpSubjectLTE(v string) predicate.Holder {
	return predicate.Holder(sql.FieldLTE(FieldIdpSubject, v))
}

// IdpSubjectContains applies the Contains predicate on the "idp_subject" field.
func IdpSubjectContains(v string) predicate.Holder {
	return predicate.Holder(sql.FieldContains(FieldIdpSubject, v))
}

// IdpSubjectHasPrefix applies the HasPrefix predicate on the "idp_subject" field.
func IdpSubjectHasPrefix(v string) predicate.Holder {
	return predicate.Holder(sql.FieldHasPrefix(FieldIdpSubject, v))
}

// IdpSubjectHasSuffix applies the HasSuffix predicate on the "idp_subject" field.
func IdpSubjectHasSuffix(v string) predicate.Holder {
	return predicate.Holder(sql.FieldHasSuffix(FieldIdpSubject, v))
}

// IdpSubjectIsNil applies the IsNil predicate on the "idp_subject" field.
func IdpSubjectIsNil() predicate.Holder {
	return predicate.Holder(sql.FieldIsNull(FieldIdpSubject))
}

// IdpSubjectNotNil applies the NotNil predicate on the "idp_subject" field.
func IdpSubjectNotNil() predicate.Holder {
	return predicate.Holder(sql.FieldNotNull(FieldIdpSubject))
}

// IdpSubjectEqualFold applies the EqualFold predicate on the "idp_subject" field.
func IdpSubjectEqualFold(v string) predicate.Holder {
	return predicate.Holder(sql.FieldEqualFold(FieldIdpSubject, v))
}

// IdpSubjectContainsFold applies the ContainsFold predicate on the "idp_subject" field.
func IdpSubjectContainsFold(v string) predicate.Holder {
	return predicate.Holder(sql.FieldContainsFold(FieldIdpSubject, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.Holder {
	return predicate.Holder(sql.FieldNotIn(FieldTenantID, vs...))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.Holder {
	return predicate.Holder(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.Holder {
	return predicate.Holder(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Holder) predicate.Holder {
	return predicate.Holder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Holder) predicate.Holder {
	return predicate.Holder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Holder) predicate.Holder {
	return predicate.Holder(sql.NotPredicates(p))
}
