// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package roster

import (
	bytes "bytes"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *CredentialRef) Pick() *CredentialGetRequest {
	return CredentialGetRequest_builder{Ref: x}.Build()
}

func (x *Credential) Ref() *CredentialRef {
	if v := x.GetId(); len(v) > 0 {
		return CredentialById(v)
	}
	{
		v1 := x.GetHolder()
		v2 := x.GetKind()
		if v1 != nil && len(v2) > 0 {
			return CredentialByKind(v1.Ref(), v2)
		}
	}

	return nil
}

func (x *Credential) Pick() *CredentialGetRequest {
	return x.Ref().Pick()
}

func (x *CredentialRef) Picks(v *Credential) bool {
	switch x.WhichKey() {
	case CredentialRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case CredentialRef_Kind_case:
		x := x.GetKind()
		return (x.GetHolder().Picks(v.GetHolder())) &&
			(x.GetKind() == v.GetKind())
	default:
		return false
	}
}

func (x *CredentialGetRequest) WithSelect(f func(s *CredentialSelect)) *CredentialGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&CredentialSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Credential) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Credential) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func CredentialById(v []byte) *CredentialRef {
	x := &CredentialRef{}
	x.SetId(v)
	return x
}

func CredentialGetById(v []byte) *CredentialGetRequest {
	return CredentialGetRequest_builder{Ref: CredentialById(v)}.Build()
}

func CredentialByKind(holder *HolderRef, kind string) *CredentialRef {
	x := &CredentialRefByKind{}
	x.SetHolder(holder)
	x.SetKind(kind)
	return CredentialRef_builder{Kind: x}.Build()
}

func CredentialGetByKind(holder *HolderRef, kind string) *CredentialGetRequest {
	return CredentialGetRequest_builder{Ref: CredentialByKind(holder, kind)}.Build()
}
