// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/thing.proto

package roster

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Thing is the entity this app starts with. Rename it, or delete it and write
// your own with `pd entity add`.
//
// What is worth reading here is the option at the bottom. Everything payday
// generates comes out of it: the domain byte every identifier of a Thing
// carries, the predicate that narrows every read to the tenants a caller may
// see, the List RPC and its implementation, and the Watch.
type Thing struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_DateErased  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateUpdated *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Thing) Reset() {
	*x = Thing{}
	mi := &file_app_thing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thing) ProtoMessage() {}

func (x *Thing) ProtoReflect() protoreflect.Message {
	mi := &file_app_thing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Thing) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Thing) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *Thing) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Thing) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *Thing) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *Thing) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Thing) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Thing) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Thing) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *Thing) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Thing) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *Thing) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *Thing) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Thing) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Thing) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *Thing) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *Thing) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Thing) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Thing) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *Thing) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *Thing) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Thing) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Thing_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     []byte
	Tenant *Tenant
	// The name a person writes this as. Every write of it is folded and checked
	// on the way in, so "  Arm-01 " and "arm-01" are one row and "Not A Name" is
	// refused with the field it was in.
	Alias string
	// 5 is the name and 6 is the description, in this entity and in every one
	// payday ships. An entity that does not want one of them leaves the number
	// empty rather than spending it on something else, which is what keeps
	// `header.Of` able to read any of them.
	//
	// 3 is yours: a set smaller than a tenant, if this app has one. payday
	// leaves it open and will not spend it -- see `docs/SCHEMA.md`.
	Desc string
	// Erased softly, which is what saying nothing about erasure means: the row is
	// stamped and stays, so it cannot be read or changed, its alias comes free
	// again, and the trail can still say what it held. Delete it and say
	// `erase: {hard: {}}` if losing the row is the point -- a table of readings
	// cannot be one nothing may ever be removed from.
	DateErased *timestamppb.Timestamp
	// Stamped on every write and refused to a patch document, so it is a version
	// and not a field. Generation refuses a `watch:` without one: a watch sends
	// state, so two answers about one row have to be orderable or a late one
	// erases an early one that was newer.
	DateUpdated *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
}

func (b0 Thing_builder) Build() *Thing {
	m0 := &Thing{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_app_thing_proto protoreflect.FileDescriptor

const file_app_thing_proto_rawDesc = "" +
	"\n" +
	"\x0fapp/thing.proto\x12\x03app\x1a\x13payday/tenant.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\"\xc9\x03\n" +
	"\x05Thing\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12+\n" +
	"\x06tenant\x18\x02 \x01(\v2\v.app.TenantB\x06\xf2\x82\x16\x02@\x01R\x06tenant\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated:t\xca\xfc\x15G\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a\x1f\x12\x04slug\x1a\t\n" +
	"\x05alias\x10\x04\x1a\n" +
	"\n" +
	"\x06tenant\x10\x020\x01\x8a\xbb\x16%\b\a2\x1f\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x04\n" +
	"\x02id\x1a\x03ref \x14(d:\x00B!Z\x1agithub.com/lesomnus/roster\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_thing_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_thing_proto_goTypes = []any{
	(*Thing)(nil),                 // 0: app.Thing
	(*Tenant)(nil),                // 1: app.Tenant
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_app_thing_proto_depIdxs = []int32{
	1, // 0: app.Thing.tenant:type_name -> app.Tenant
	2, // 1: app.Thing.date_erased:type_name -> google.protobuf.Timestamp
	2, // 2: app.Thing.date_updated:type_name -> google.protobuf.Timestamp
	2, // 3: app.Thing.date_created:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_app_thing_proto_init() }
func file_app_thing_proto_init() {
	if File_app_thing_proto != nil {
		return
	}
	file_payday_tenant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_thing_proto_rawDesc), len(file_app_thing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_thing_proto_goTypes,
		DependencyIndexes: file_app_thing_proto_depIdxs,
		MessageInfos:      file_app_thing_proto_msgTypes,
	}.Build()
	File_app_thing_proto = out.File
	file_app_thing_proto_goTypes = nil
	file_app_thing_proto_depIdxs = nil
}
