// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/audit"
)

// Audit is the model entity for the Audit schema.
type Audit struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID uuid.UUID `json:"actor_id,omitempty"`
	// TraceID holds the value of the "trace_id" field.
	TraceID []byte `json:"trace_id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// ObjectID holds the value of the "object_id" field.
	ObjectID uuid.UUID `json:"object_id,omitempty"`
	// Patch holds the value of the "patch" field.
	Patch []byte `json:"patch,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// ActorTenantID holds the value of the "actor_tenant_id" field.
	ActorTenantID uuid.UUID `json:"actor_tenant_id,omitempty"`
	// Value holds the value of the "value" field.
	Value []byte `json:"value,omitempty"`
	// CounterpartTenantID holds the value of the "counterpart_tenant_id" field.
	CounterpartTenantID uuid.UUID `json:"counterpart_tenant_id,omitempty"`
	selectValues        sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Audit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case audit.FieldTraceID, audit.FieldPatch, audit.FieldValue:
			values[i] = new([]byte)
		case audit.FieldAction:
			values[i] = new(sql.NullString)
		case audit.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case audit.FieldID, audit.FieldTenantID, audit.FieldActorID, audit.FieldObjectID, audit.FieldActorTenantID, audit.FieldCounterpartTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Audit fields.
func (_m *Audit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case audit.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case audit.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case audit.FieldActorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value != nil {
				_m.ActorID = *value
			}
		case audit.FieldTraceID:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field trace_id", values[i])
			} else if value != nil {
				_m.TraceID = *value
			}
		case audit.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case audit.FieldObjectID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field object_id", values[i])
			} else if value != nil {
				_m.ObjectID = *value
			}
		case audit.FieldPatch:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field patch", values[i])
			} else if value != nil {
				_m.Patch = *value
			}
		case audit.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case audit.FieldActorTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field actor_tenant_id", values[i])
			} else if value != nil {
				_m.ActorTenantID = *value
			}
		case audit.FieldValue:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value != nil {
				_m.Value = *value
			}
		case audit.FieldCounterpartTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field counterpart_tenant_id", values[i])
			} else if value != nil {
				_m.CounterpartTenantID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the Audit.
// This includes values selected through modifiers, order, etc.
func (_m *Audit) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Audit.
// Note that you need to call Audit.Unwrap() before calling this method if this Audit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Audit) Update() *AuditUpdateOne {
	return NewAuditClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Audit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Audit) Unwrap() *Audit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Audit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Audit) String() string {
	var builder strings.Builder
	builder.WriteString("Audit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("actor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActorID))
	builder.WriteString(", ")
	builder.WriteString("trace_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TraceID))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("object_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ObjectID))
	builder.WriteString(", ")
	builder.WriteString("patch=")
	builder.WriteString(fmt.Sprintf("%v", _m.Patch))
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("actor_tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActorTenantID))
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(fmt.Sprintf("%v", _m.Value))
	builder.WriteString(", ")
	builder.WriteString("counterpart_tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CounterpartTenantID))
	builder.WriteByte(')')
	return builder.String()
}

// Audits is a parsable slice of Audit.
type Audits []*Audit
