// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/binding"
	"github.com/lesomnus/roster/internal/ent/group"
	"github.com/lesomnus/roster/internal/ent/holder"
	"github.com/lesomnus/roster/internal/ent/role"
	"github.com/lesomnus/roster/internal/ent/site"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Binding is the model entity for the Binding schema.
type Binding struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated time.Time `json:"date_updated,omitempty"`
	// DateErased holds the value of the "date_erased" field.
	DateErased *time.Time `json:"date_erased,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID uuid.UUID `json:"role_id,omitempty"`
	// SiteID holds the value of the "site_id" field.
	SiteID uuid.UUID `json:"site_id,omitempty"`
	// HolderID holds the value of the "holder_id" field.
	HolderID uuid.UUID `json:"holder_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID uuid.UUID `json:"group_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BindingQuery when eager-loading is set.
	Edges        BindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BindingEdges holds the relations/edges for other nodes in the graph.
type BindingEdges struct {
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// Site holds the value of the site edge.
	Site *Site `json:"site,omitempty"`
	// Holder holds the value of the holder edge.
	Holder *Holder `json:"holder,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BindingEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// SiteOrErr returns the Site value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BindingEdges) SiteOrErr() (*Site, error) {
	if e.Site != nil {
		return e.Site, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: site.Label}
	}
	return nil, &NotLoadedError{edge: "site"}
}

// HolderOrErr returns the Holder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BindingEdges) HolderOrErr() (*Holder, error) {
	if e.Holder != nil {
		return e.Holder, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: holder.Label}
	}
	return nil, &NotLoadedError{edge: "holder"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BindingEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Binding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case binding.FieldDateUpdated, binding.FieldDateErased, binding.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case binding.FieldID, binding.FieldRoleID, binding.FieldSiteID, binding.FieldHolderID, binding.FieldGroupID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Binding fields.
func (_m *Binding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case binding.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case binding.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = value.Time
			}
		case binding.FieldDateErased:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_erased", values[i])
			} else if value.Valid {
				_m.DateErased = new(time.Time)
				*_m.DateErased = value.Time
			}
		case binding.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case binding.FieldRoleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value != nil {
				_m.RoleID = *value
			}
		case binding.FieldSiteID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field site_id", values[i])
			} else if value != nil {
				_m.SiteID = *value
			}
		case binding.FieldHolderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field holder_id", values[i])
			} else if value != nil {
				_m.HolderID = *value
			}
		case binding.FieldGroupID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value != nil {
				_m.GroupID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Binding.
// This includes values selected through modifiers, order, etc.
func (_m *Binding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the Binding entity.
func (_m *Binding) QueryRole() *RoleQuery {
	return NewBindingClient(_m.config).QueryRole(_m)
}

// QuerySite queries the "site" edge of the Binding entity.
func (_m *Binding) QuerySite() *SiteQuery {
	return NewBindingClient(_m.config).QuerySite(_m)
}

// QueryHolder queries the "holder" edge of the Binding entity.
func (_m *Binding) QueryHolder() *HolderQuery {
	return NewBindingClient(_m.config).QueryHolder(_m)
}

// QueryGroup queries the "group" edge of the Binding entity.
func (_m *Binding) QueryGroup() *GroupQuery {
	return NewBindingClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this Binding.
// Note that you need to call Binding.Unwrap() before calling this method if this Binding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Binding) Update() *BindingUpdateOne {
	return NewBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Binding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Binding) Unwrap() *Binding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Binding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Binding) String() string {
	var builder strings.Builder
	builder.WriteString("Binding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date_updated=")
	builder.WriteString(_m.DateUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateErased; v != nil {
		builder.WriteString("date_erased=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("site_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SiteID))
	builder.WriteString(", ")
	builder.WriteString("holder_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HolderID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteByte(')')
	return builder.String()
}

// BindingList is a parsable slice of Binding.
type BindingList []*Binding
