// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/binding"
	"github.com/lesomnus/roster/internal/ent/group"
	"github.com/lesomnus/roster/internal/ent/holder"
	"github.com/lesomnus/roster/internal/ent/role"
	"github.com/lesomnus/roster/internal/ent/site"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// BindingCreate is the builder for creating a Binding entity.
type BindingCreate struct {
	config
	mutation *BindingMutation
	hooks    []Hook
}

// SetDateUpdated sets the "date_updated" field.
func (_c *BindingCreate) SetDateUpdated(v time.Time) *BindingCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateErased sets the "date_erased" field.
func (_c *BindingCreate) SetDateErased(v time.Time) *BindingCreate {
	_c.mutation.SetDateErased(v)
	return _c
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_c *BindingCreate) SetNillableDateErased(v *time.Time) *BindingCreate {
	if v != nil {
		_c.SetDateErased(*v)
	}
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *BindingCreate) SetDateCreated(v time.Time) *BindingCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *BindingCreate) SetNillableDateCreated(v *time.Time) *BindingCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetRoleId sets the "role_id" field.
func (_c *BindingCreate) SetRoleId(v uuid.UUID) *BindingCreate {
	_c.mutation.SetRoleId(v)
	return _c
}

// SetSiteId sets the "site_id" field.
func (_c *BindingCreate) SetSiteId(v uuid.UUID) *BindingCreate {
	_c.mutation.SetSiteId(v)
	return _c
}

// SetNillableSiteId sets the "site_id" field if the given value is not nil.
func (_c *BindingCreate) SetNillableSiteId(v *uuid.UUID) *BindingCreate {
	if v != nil {
		_c.SetSiteId(*v)
	}
	return _c
}

// SetHolderId sets the "holder_id" field.
func (_c *BindingCreate) SetHolderId(v uuid.UUID) *BindingCreate {
	_c.mutation.SetHolderId(v)
	return _c
}

// SetNillableHolderId sets the "holder_id" field if the given value is not nil.
func (_c *BindingCreate) SetNillableHolderId(v *uuid.UUID) *BindingCreate {
	if v != nil {
		_c.SetHolderId(*v)
	}
	return _c
}

// SetGroupId sets the "group_id" field.
func (_c *BindingCreate) SetGroupId(v uuid.UUID) *BindingCreate {
	_c.mutation.SetGroupId(v)
	return _c
}

// SetNillableGroupId sets the "group_id" field if the given value is not nil.
func (_c *BindingCreate) SetNillableGroupId(v *uuid.UUID) *BindingCreate {
	if v != nil {
		_c.SetGroupId(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *BindingCreate) SetId(v uuid.UUID) *BindingCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetRole sets the "role" edge to the Role entity.
func (_c *BindingCreate) SetRole(v *Role) *BindingCreate {
	return _c.SetRoleId(v.Id)
}

// SetSite sets the "site" edge to the Site entity.
func (_c *BindingCreate) SetSite(v *Site) *BindingCreate {
	return _c.SetSiteId(v.Id)
}

// SetHolder sets the "holder" edge to the Holder entity.
func (_c *BindingCreate) SetHolder(v *Holder) *BindingCreate {
	return _c.SetHolderId(v.Id)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *BindingCreate) SetGroup(v *Group) *BindingCreate {
	return _c.SetGroupId(v.Id)
}

// Mutation returns the BindingMutation object of the builder.
func (_c *BindingCreate) Mutation() *BindingMutation {
	return _c.mutation
}

// Save creates the Binding in the database.
func (_c *BindingCreate) Save(ctx context.Context) (*Binding, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BindingCreate) SaveX(ctx context.Context) *Binding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BindingCreate) check() error {
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "Binding.date_updated"`)}
	}
	if _, ok := _c.mutation.RoleId(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "Binding.role_id"`)}
	}
	if len(_c.mutation.RoleIds()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "Binding.role"`)}
	}
	return nil
}

func (_c *BindingCreate) sqlSave(ctx context.Context) (*Binding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else if err := _node.Id.Scan(_spec.Id.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *BindingCreate) createSpec() (*Binding, *sqlgraph.CreateSpec) {
	var (
		_node = &Binding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(binding.Table, sqlgraph.NewFieldSpec(binding.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(binding.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateErased(); ok {
		_spec.SetField(binding.FieldDateErased, field.TypeTime, value)
		_node.DateErased = &value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(binding.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.RoleIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   binding.RoleTable,
			Columns: []string{binding.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(role.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SiteIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   binding.SiteTable,
			Columns: []string{binding.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(site.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.HolderIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   binding.HolderTable,
			Columns: []string{binding.HolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(holder.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HolderId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   binding.GroupTable,
			Columns: []string{binding.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(group.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BindingCreateBulk is the builder for creating many Binding entities in bulk.
type BindingCreateBulk struct {
	config
	err      error
	builders []*BindingCreate
}

// Save creates the Binding entities in the database.
func (_c *BindingCreateBulk) Save(ctx context.Context) ([]*Binding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Binding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BindingCreateBulk) SaveX(ctx context.Context) []*Binding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
