// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/credential"
	"github.com/lesomnus/roster/internal/ent/holder"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Credential is the model entity for the Credential schema.
type Credential struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Secret holds the value of the "secret" field.
	Secret []byte `json:"secret,omitempty"`
	// Failures holds the value of the "failures" field.
	Failures int32 `json:"failures,omitempty"`
	// DateLocked holds the value of the "date_locked" field.
	DateLocked *time.Time `json:"date_locked,omitempty"`
	// DateRotated holds the value of the "date_rotated" field.
	DateRotated *time.Time `json:"date_rotated,omitempty"`
	// LastStep holds the value of the "last_step" field.
	LastStep int64 `json:"last_step,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated time.Time `json:"date_updated,omitempty"`
	// DateErased holds the value of the "date_erased" field.
	DateErased *time.Time `json:"date_erased,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// HolderID holds the value of the "holder_id" field.
	HolderID uuid.UUID `json:"holder_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CredentialQuery when eager-loading is set.
	Edges        CredentialEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CredentialEdges holds the relations/edges for other nodes in the graph.
type CredentialEdges struct {
	// Holder holds the value of the holder edge.
	Holder *Holder `json:"holder,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HolderOrErr returns the Holder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CredentialEdges) HolderOrErr() (*Holder, error) {
	if e.Holder != nil {
		return e.Holder, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: holder.Label}
	}
	return nil, &NotLoadedError{edge: "holder"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Credential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case credential.FieldSecret:
			values[i] = new([]byte)
		case credential.FieldFailures, credential.FieldLastStep:
			values[i] = new(sql.NullInt64)
		case credential.FieldName, credential.FieldKind:
			values[i] = new(sql.NullString)
		case credential.FieldDateLocked, credential.FieldDateRotated, credential.FieldDateUpdated, credential.FieldDateErased, credential.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case credential.FieldID, credential.FieldHolderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Credential fields.
func (_m *Credential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case credential.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case credential.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case credential.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case credential.FieldSecret:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field secret", values[i])
			} else if value != nil {
				_m.Secret = *value
			}
		case credential.FieldFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failures", values[i])
			} else if value.Valid {
				_m.Failures = int32(value.Int64)
			}
		case credential.FieldDateLocked:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_locked", values[i])
			} else if value.Valid {
				_m.DateLocked = new(time.Time)
				*_m.DateLocked = value.Time
			}
		case credential.FieldDateRotated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_rotated", values[i])
			} else if value.Valid {
				_m.DateRotated = new(time.Time)
				*_m.DateRotated = value.Time
			}
		case credential.FieldLastStep:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_step", values[i])
			} else if value.Valid {
				_m.LastStep = value.Int64
			}
		case credential.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = value.Time
			}
		case credential.FieldDateErased:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_erased", values[i])
			} else if value.Valid {
				_m.DateErased = new(time.Time)
				*_m.DateErased = value.Time
			}
		case credential.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case credential.FieldHolderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field holder_id", values[i])
			} else if value != nil {
				_m.HolderID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Credential.
// This includes values selected through modifiers, order, etc.
func (_m *Credential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHolder queries the "holder" edge of the Credential entity.
func (_m *Credential) QueryHolder() *HolderQuery {
	return NewCredentialClient(_m.config).QueryHolder(_m)
}

// Update returns a builder for updating this Credential.
// Note that you need to call Credential.Unwrap() before calling this method if this Credential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Credential) Update() *CredentialUpdateOne {
	return NewCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Credential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Credential) Unwrap() *Credential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Credential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Credential) String() string {
	var builder strings.Builder
	builder.WriteString("Credential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("secret=")
	builder.WriteString(fmt.Sprintf("%v", _m.Secret))
	builder.WriteString(", ")
	builder.WriteString("failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.Failures))
	builder.WriteString(", ")
	if v := _m.DateLocked; v != nil {
		builder.WriteString("date_locked=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DateRotated; v != nil {
		builder.WriteString("date_rotated=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_step=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastStep))
	builder.WriteString(", ")
	builder.WriteString("date_updated=")
	builder.WriteString(_m.DateUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateErased; v != nil {
		builder.WriteString("date_erased=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("holder_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HolderID))
	builder.WriteByte(')')
	return builder.String()
}

// CredentialList is a parsable slice of Credential.
type CredentialList []*Credential
