// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/credential"
	"github.com/lesomnus/roster/internal/ent/holder"
)

// CredentialCreate is the builder for creating a Credential entity.
type CredentialCreate struct {
	config
	mutation *CredentialMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CredentialCreate) SetName(v string) *CredentialCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *CredentialCreate) SetKind(v string) *CredentialCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetSecret sets the "secret" field.
func (_c *CredentialCreate) SetSecret(v []byte) *CredentialCreate {
	_c.mutation.SetSecret(v)
	return _c
}

// SetFailures sets the "failures" field.
func (_c *CredentialCreate) SetFailures(v int32) *CredentialCreate {
	_c.mutation.SetFailures(v)
	return _c
}

// SetDateLocked sets the "date_locked" field.
func (_c *CredentialCreate) SetDateLocked(v time.Time) *CredentialCreate {
	_c.mutation.SetDateLocked(v)
	return _c
}

// SetNillableDateLocked sets the "date_locked" field if the given value is not nil.
func (_c *CredentialCreate) SetNillableDateLocked(v *time.Time) *CredentialCreate {
	if v != nil {
		_c.SetDateLocked(*v)
	}
	return _c
}

// SetDateRotated sets the "date_rotated" field.
func (_c *CredentialCreate) SetDateRotated(v time.Time) *CredentialCreate {
	_c.mutation.SetDateRotated(v)
	return _c
}

// SetNillableDateRotated sets the "date_rotated" field if the given value is not nil.
func (_c *CredentialCreate) SetNillableDateRotated(v *time.Time) *CredentialCreate {
	if v != nil {
		_c.SetDateRotated(*v)
	}
	return _c
}

// SetLastStep sets the "last_step" field.
func (_c *CredentialCreate) SetLastStep(v int64) *CredentialCreate {
	_c.mutation.SetLastStep(v)
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *CredentialCreate) SetDateUpdated(v time.Time) *CredentialCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateErased sets the "date_erased" field.
func (_c *CredentialCreate) SetDateErased(v time.Time) *CredentialCreate {
	_c.mutation.SetDateErased(v)
	return _c
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_c *CredentialCreate) SetNillableDateErased(v *time.Time) *CredentialCreate {
	if v != nil {
		_c.SetDateErased(*v)
	}
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *CredentialCreate) SetDateCreated(v time.Time) *CredentialCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *CredentialCreate) SetNillableDateCreated(v *time.Time) *CredentialCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetHolderID sets the "holder_id" field.
func (_c *CredentialCreate) SetHolderID(v uuid.UUID) *CredentialCreate {
	_c.mutation.SetHolderID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CredentialCreate) SetID(v uuid.UUID) *CredentialCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetHolder sets the "holder" edge to the Holder entity.
func (_c *CredentialCreate) SetHolder(v *Holder) *CredentialCreate {
	return _c.SetHolderID(v.ID)
}

// Mutation returns the CredentialMutation object of the builder.
func (_c *CredentialCreate) Mutation() *CredentialMutation {
	return _c.mutation
}

// Save creates the Credential in the database.
func (_c *CredentialCreate) Save(ctx context.Context) (*Credential, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CredentialCreate) SaveX(ctx context.Context) *Credential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CredentialCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Credential.name"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Credential.kind"`)}
	}
	if _, ok := _c.mutation.Secret(); !ok {
		return &ValidationError{Name: "secret", err: errors.New(`ent: missing required field "Credential.secret"`)}
	}
	if _, ok := _c.mutation.Failures(); !ok {
		return &ValidationError{Name: "failures", err: errors.New(`ent: missing required field "Credential.failures"`)}
	}
	if _, ok := _c.mutation.LastStep(); !ok {
		return &ValidationError{Name: "last_step", err: errors.New(`ent: missing required field "Credential.last_step"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "Credential.date_updated"`)}
	}
	if _, ok := _c.mutation.HolderID(); !ok {
		return &ValidationError{Name: "holder_id", err: errors.New(`ent: missing required field "Credential.holder_id"`)}
	}
	if len(_c.mutation.HolderIDs()) == 0 {
		return &ValidationError{Name: "holder", err: errors.New(`ent: missing required edge "Credential.holder"`)}
	}
	return nil
}

func (_c *CredentialCreate) sqlSave(ctx context.Context) (*Credential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CredentialCreate) createSpec() (*Credential, *sqlgraph.CreateSpec) {
	var (
		_node = &Credential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(credential.Table, sqlgraph.NewFieldSpec(credential.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(credential.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(credential.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Secret(); ok {
		_spec.SetField(credential.FieldSecret, field.TypeBytes, value)
		_node.Secret = value
	}
	if value, ok := _c.mutation.Failures(); ok {
		_spec.SetField(credential.FieldFailures, field.TypeInt32, value)
		_node.Failures = value
	}
	if value, ok := _c.mutation.DateLocked(); ok {
		_spec.SetField(credential.FieldDateLocked, field.TypeTime, value)
		_node.DateLocked = &value
	}
	if value, ok := _c.mutation.DateRotated(); ok {
		_spec.SetField(credential.FieldDateRotated, field.TypeTime, value)
		_node.DateRotated = &value
	}
	if value, ok := _c.mutation.LastStep(); ok {
		_spec.SetField(credential.FieldLastStep, field.TypeInt64, value)
		_node.LastStep = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(credential.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateErased(); ok {
		_spec.SetField(credential.FieldDateErased, field.TypeTime, value)
		_node.DateErased = &value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(credential.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.HolderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   credential.HolderTable,
			Columns: []string{credential.HolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(holder.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HolderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CredentialCreateBulk is the builder for creating many Credential entities in bulk.
type CredentialCreateBulk struct {
	config
	err      error
	builders []*CredentialCreate
}

// Save creates the Credential entities in the database.
func (_c *CredentialCreateBulk) Save(ctx context.Context) ([]*Credential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Credential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CredentialCreateBulk) SaveX(ctx context.Context) []*Credential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
