// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"uuid"

	"github.com/lesomnus/roster/internal/ent/email"
	"github.com/lesomnus/roster/internal/ent/holder"
	"github.com/lesomnus/roster/internal/ent/identity"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Email is the model entity for the Email schema.
type Email struct {
	config `json:"-"`
	// Id of the ent.
	Id uuid.UUID `json:"id,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// DateVerified holds the value of the "date_verified" field.
	DateVerified *time.Time `json:"date_verified,omitempty"`
	// TenantId holds the value of the "tenant_id" field.
	TenantId uuid.UUID `json:"tenant_id,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated time.Time `json:"date_updated,omitempty"`
	// DateErased holds the value of the "date_erased" field.
	DateErased *time.Time `json:"date_erased,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// HolderId holds the value of the "holder_id" field.
	HolderId uuid.UUID `json:"holder_id,omitempty"`
	// VouchedById holds the value of the "vouched_by_id" field.
	VouchedById uuid.UUID `json:"vouched_by_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmailQuery when eager-loading is set.
	Edges        EmailEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EmailEdges holds the relations/edges for other nodes in the graph.
type EmailEdges struct {
	// Holder holds the value of the holder edge.
	Holder *Holder `json:"holder,omitempty"`
	// VouchedBy holds the value of the vouched_by edge.
	VouchedBy *Identity `json:"vouched_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// HolderOrErr returns the Holder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmailEdges) HolderOrErr() (*Holder, error) {
	if e.Holder != nil {
		return e.Holder, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: holder.Label}
	}
	return nil, &NotLoadedError{edge: "holder"}
}

// VouchedByOrErr returns the VouchedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmailEdges) VouchedByOrErr() (*Identity, error) {
	if e.VouchedBy != nil {
		return e.VouchedBy, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: identity.Label}
	}
	return nil, &NotLoadedError{edge: "vouched_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Email) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case email.FieldId:
			values[i] = email.ValueScanner.Id.ScanValue()
		case email.FieldAddress:
			values[i] = new(sql.NullString)
		case email.FieldDateVerified, email.FieldDateUpdated, email.FieldDateErased, email.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case email.FieldTenantId:
			values[i] = email.ValueScanner.TenantId.ScanValue()
		case email.FieldHolderId:
			values[i] = email.ValueScanner.HolderId.ScanValue()
		case email.FieldVouchedById:
			values[i] = email.ValueScanner.VouchedById.ScanValue()
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Email fields.
func (_m *Email) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case email.FieldId:
			if value, err := email.ValueScanner.Id.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.Id = value
			}
		case email.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case email.FieldDateVerified:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_verified", values[i])
			} else if value.Valid {
				_m.DateVerified = new(time.Time)
				*_m.DateVerified = value.Time
			}
		case email.FieldTenantId:
			if value, err := email.ValueScanner.TenantId.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.TenantId = value
			}
		case email.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = value.Time
			}
		case email.FieldDateErased:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_erased", values[i])
			} else if value.Valid {
				_m.DateErased = new(time.Time)
				*_m.DateErased = value.Time
			}
		case email.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case email.FieldHolderId:
			if value, err := email.ValueScanner.HolderId.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.HolderId = value
			}
		case email.FieldVouchedById:
			if value, err := email.ValueScanner.VouchedById.FromValue(values[i]); err != nil {
				return err
			} else {
				_m.VouchedById = value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Email.
// This includes values selected through modifiers, order, etc.
func (_m *Email) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHolder queries the "holder" edge of the Email entity.
func (_m *Email) QueryHolder() *HolderQuery {
	return NewEmailClient(_m.config).QueryHolder(_m)
}

// QueryVouchedBy queries the "vouched_by" edge of the Email entity.
func (_m *Email) QueryVouchedBy() *IdentityQuery {
	return NewEmailClient(_m.config).QueryVouchedBy(_m)
}

// Update returns a builder for updating this Email.
// Note that you need to call Email.Unwrap() before calling this method if this Email
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Email) Update() *EmailUpdateOne {
	return NewEmailClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Email entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Email) Unwrap() *Email {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Email is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Email) String() string {
	var builder strings.Builder
	builder.WriteString("Email(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.Id))
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	if v := _m.DateVerified; v != nil {
		builder.WriteString("date_verified=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantId))
	builder.WriteString(", ")
	builder.WriteString("date_updated=")
	builder.WriteString(_m.DateUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateErased; v != nil {
		builder.WriteString("date_erased=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("holder_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HolderId))
	builder.WriteString(", ")
	builder.WriteString("vouched_by_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.VouchedById))
	builder.WriteByte(')')
	return builder.String()
}

// EmailList is a parsable slice of Email.
type EmailList []*Email
