// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/lesomnus/roster/internal/ent/hostproof"
	"github.com/lesomnus/roster/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// HostProofUpdate is the builder for updating HostProof entities.
type HostProofUpdate struct {
	config
	hooks     []Hook
	mutation  *HostProofMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the HostProofUpdate builder.
func (_u *HostProofUpdate) Where(ps ...predicate.HostProof) *HostProofUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDateExpires sets the "date_expires" field.
func (_u *HostProofUpdate) SetDateExpires(v time.Time) *HostProofUpdate {
	_u.mutation.SetDateExpires(v)
	return _u
}

// SetNillableDateExpires sets the "date_expires" field if the given value is not nil.
func (_u *HostProofUpdate) SetNillableDateExpires(v *time.Time) *HostProofUpdate {
	if v != nil {
		_u.SetDateExpires(*v)
	}
	return _u
}

// ClearDateExpires clears the value of the "date_expires" field.
func (_u *HostProofUpdate) ClearDateExpires() *HostProofUpdate {
	_u.mutation.ClearDateExpires()
	return _u
}

// SetDesc sets the "desc" field.
func (_u *HostProofUpdate) SetDesc(v string) *HostProofUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *HostProofUpdate) SetNillableDesc(v *string) *HostProofUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *HostProofUpdate) SetDateUpdated(v time.Time) *HostProofUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *HostProofUpdate) SetNillableDateUpdated(v *time.Time) *HostProofUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *HostProofUpdate) SetDateErased(v time.Time) *HostProofUpdate {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *HostProofUpdate) SetNillableDateErased(v *time.Time) *HostProofUpdate {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *HostProofUpdate) ClearDateErased() *HostProofUpdate {
	_u.mutation.ClearDateErased()
	return _u
}

// Mutation returns the HostProofMutation object of the builder.
func (_u *HostProofUpdate) Mutation() *HostProofMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HostProofUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HostProofUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HostProofUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HostProofUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HostProofUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HostProof.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *HostProofUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *HostProofUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *HostProofUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hostproof.Table, hostproof.Columns, sqlgraph.NewFieldSpec(hostproof.FieldId, field.TypeUuid))
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DateExpires(); ok {
		_spec.SetField(hostproof.FieldDateExpires, field.TypeTime, value)
	}
	if _u.mutation.DateExpiresCleared() {
		_spec.ClearField(hostproof.FieldDateExpires, field.TypeTime)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(hostproof.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(hostproof.FieldDateUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(hostproof.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(hostproof.FieldDateErased, field.TypeTime)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(hostproof.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hostproof.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HostProofUpdateOne is the builder for updating a single HostProof entity.
type HostProofUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *HostProofMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDateExpires sets the "date_expires" field.
func (_u *HostProofUpdateOne) SetDateExpires(v time.Time) *HostProofUpdateOne {
	_u.mutation.SetDateExpires(v)
	return _u
}

// SetNillableDateExpires sets the "date_expires" field if the given value is not nil.
func (_u *HostProofUpdateOne) SetNillableDateExpires(v *time.Time) *HostProofUpdateOne {
	if v != nil {
		_u.SetDateExpires(*v)
	}
	return _u
}

// ClearDateExpires clears the value of the "date_expires" field.
func (_u *HostProofUpdateOne) ClearDateExpires() *HostProofUpdateOne {
	_u.mutation.ClearDateExpires()
	return _u
}

// SetDesc sets the "desc" field.
func (_u *HostProofUpdateOne) SetDesc(v string) *HostProofUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *HostProofUpdateOne) SetNillableDesc(v *string) *HostProofUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *HostProofUpdateOne) SetDateUpdated(v time.Time) *HostProofUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *HostProofUpdateOne) SetNillableDateUpdated(v *time.Time) *HostProofUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *HostProofUpdateOne) SetDateErased(v time.Time) *HostProofUpdateOne {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *HostProofUpdateOne) SetNillableDateErased(v *time.Time) *HostProofUpdateOne {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *HostProofUpdateOne) ClearDateErased() *HostProofUpdateOne {
	_u.mutation.ClearDateErased()
	return _u
}

// Mutation returns the HostProofMutation object of the builder.
func (_u *HostProofUpdateOne) Mutation() *HostProofMutation {
	return _u.mutation
}

// Where appends a list predicates to the HostProofUpdate builder.
func (_u *HostProofUpdateOne) Where(ps ...predicate.HostProof) *HostProofUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HostProofUpdateOne) Select(field string, fields ...string) *HostProofUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HostProof entity.
func (_u *HostProofUpdateOne) Save(ctx context.Context) (*HostProof, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HostProofUpdateOne) SaveX(ctx context.Context) *HostProof {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HostProofUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HostProofUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HostProofUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIds()) > 0 {
		return errors.New(`ent: clearing a required unique edge "HostProof.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *HostProofUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *HostProofUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *HostProofUpdateOne) sqlSave(ctx context.Context) (_node *HostProof, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(hostproof.Table, hostproof.Columns, sqlgraph.NewFieldSpec(hostproof.FieldId, field.TypeUuid))
	id, ok := _u.mutation.Id()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HostProof.id" for update`)}
	}
	_spec.Node.Id.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, hostproof.FieldId)
		for _, f := range fields {
			if !hostproof.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != hostproof.FieldId {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.Predicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DateExpires(); ok {
		_spec.SetField(hostproof.FieldDateExpires, field.TypeTime, value)
	}
	if _u.mutation.DateExpiresCleared() {
		_spec.ClearField(hostproof.FieldDateExpires, field.TypeTime)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(hostproof.FieldDesc, field.TypeString, value)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(hostproof.FieldDateUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(hostproof.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(hostproof.FieldDateErased, field.TypeTime)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(hostproof.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &HostProof{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{hostproof.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
