// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/identity.proto

package ent

import (
	uuid "github.com/google/uuid"
	roster "github.com/lesomnus/roster"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Identity) Proto() *roster.Identity {
	x := &roster.Identity{}
	x.SetId(e.ID[:])
	if v := e.Edges.Holder; v != nil {
		x.SetHolder(v.Proto())
	} else if v := e.HolderID; v != *new(uuid.UUID) {
		r := &roster.Holder{}
		r.SetId(v[:])
		x.SetHolder(r)
	}
	x.SetProvider(e.Provider)
	x.SetSubject(e.Subject)
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
