// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lesomnus/roster/internal/ent/link"
	"github.com/lesomnus/roster/internal/ent/predicate"
)

// LinkUpdate is the builder for updating Link entities.
type LinkUpdate struct {
	config
	hooks     []Hook
	mutation  *LinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LinkUpdate builder.
func (_u *LinkUpdate) Where(ps ...predicate.Link) *LinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDateUpdated sets the "date_updated" field.
func (_u *LinkUpdate) SetDateUpdated(v time.Time) *LinkUpdate {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableDateUpdated(v *time.Time) *LinkUpdate {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *LinkUpdate) SetDateErased(v time.Time) *LinkUpdate {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *LinkUpdate) SetNillableDateErased(v *time.Time) *LinkUpdate {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *LinkUpdate) ClearDateErased() *LinkUpdate {
	_u.mutation.ClearDateErased()
	return _u
}

// Mutation returns the LinkMutation object of the builder.
func (_u *LinkUpdate) Mutation() *LinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkUpdate) check() error {
	if _u.mutation.HolderCleared() && len(_u.mutation.HolderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Link.holder"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LinkUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LinkUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.DateExpiresCleared() {
		_spec.ClearField(link.FieldDateExpires, field.TypeTime)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(link.FieldDateUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(link.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(link.FieldDateErased, field.TypeTime)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(link.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LinkUpdateOne is the builder for updating a single Link entity.
type LinkUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDateUpdated sets the "date_updated" field.
func (_u *LinkUpdateOne) SetDateUpdated(v time.Time) *LinkUpdateOne {
	_u.mutation.SetDateUpdated(v)
	return _u
}

// SetNillableDateUpdated sets the "date_updated" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableDateUpdated(v *time.Time) *LinkUpdateOne {
	if v != nil {
		_u.SetDateUpdated(*v)
	}
	return _u
}

// SetDateErased sets the "date_erased" field.
func (_u *LinkUpdateOne) SetDateErased(v time.Time) *LinkUpdateOne {
	_u.mutation.SetDateErased(v)
	return _u
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_u *LinkUpdateOne) SetNillableDateErased(v *time.Time) *LinkUpdateOne {
	if v != nil {
		_u.SetDateErased(*v)
	}
	return _u
}

// ClearDateErased clears the value of the "date_erased" field.
func (_u *LinkUpdateOne) ClearDateErased() *LinkUpdateOne {
	_u.mutation.ClearDateErased()
	return _u
}

// Mutation returns the LinkMutation object of the builder.
func (_u *LinkUpdateOne) Mutation() *LinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the LinkUpdate builder.
func (_u *LinkUpdateOne) Where(ps ...predicate.Link) *LinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LinkUpdateOne) Select(field string, fields ...string) *LinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Link entity.
func (_u *LinkUpdateOne) Save(ctx context.Context) (*Link, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkUpdateOne) SaveX(ctx context.Context) *Link {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkUpdateOne) check() error {
	if _u.mutation.HolderCleared() && len(_u.mutation.HolderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Link.holder"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LinkUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LinkUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LinkUpdateOne) sqlSave(ctx context.Context) (_node *Link, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Link.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, link.FieldID)
		for _, f := range fields {
			if !link.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != link.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.DateExpiresCleared() {
		_spec.ClearField(link.FieldDateExpires, field.TypeTime)
	}
	if value, ok := _u.mutation.DateUpdated(); ok {
		_spec.SetField(link.FieldDateUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DateErased(); ok {
		_spec.SetField(link.FieldDateErased, field.TypeTime, value)
	}
	if _u.mutation.DateErasedCleared() {
		_spec.ClearField(link.FieldDateErased, field.TypeTime)
	}
	if _u.mutation.DateCreatedCleared() {
		_spec.ClearField(link.FieldDateCreated, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Link{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
