// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/maildomain"
	"github.com/lesomnus/roster/internal/ent/tenant"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// MailDomainCreate is the builder for creating a MailDomain entity.
type MailDomainCreate struct {
	config
	mutation *MailDomainMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *MailDomainCreate) SetName(v string) *MailDomainCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *MailDomainCreate) SetProvider(v string) *MailDomainCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetDesc sets the "desc" field.
func (_c *MailDomainCreate) SetDesc(v string) *MailDomainCreate {
	_c.mutation.SetDesc(v)
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *MailDomainCreate) SetDateUpdated(v time.Time) *MailDomainCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateErased sets the "date_erased" field.
func (_c *MailDomainCreate) SetDateErased(v time.Time) *MailDomainCreate {
	_c.mutation.SetDateErased(v)
	return _c
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_c *MailDomainCreate) SetNillableDateErased(v *time.Time) *MailDomainCreate {
	if v != nil {
		_c.SetDateErased(*v)
	}
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *MailDomainCreate) SetDateCreated(v time.Time) *MailDomainCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *MailDomainCreate) SetNillableDateCreated(v *time.Time) *MailDomainCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *MailDomainCreate) SetTenantID(v uuid.UUID) *MailDomainCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MailDomainCreate) SetID(v uuid.UUID) *MailDomainCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *MailDomainCreate) SetTenant(v *Tenant) *MailDomainCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the MailDomainMutation object of the builder.
func (_c *MailDomainCreate) Mutation() *MailDomainMutation {
	return _c.mutation
}

// Save creates the MailDomain in the database.
func (_c *MailDomainCreate) Save(ctx context.Context) (*MailDomain, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MailDomainCreate) SaveX(ctx context.Context) *MailDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailDomainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailDomainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MailDomainCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "MailDomain.name"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "MailDomain.provider"`)}
	}
	if _, ok := _c.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "MailDomain.desc"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "MailDomain.date_updated"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "MailDomain.tenant_id"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "MailDomain.tenant"`)}
	}
	return nil
}

func (_c *MailDomainCreate) sqlSave(ctx context.Context) (*MailDomain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MailDomainCreate) createSpec() (*MailDomain, *sqlgraph.CreateSpec) {
	var (
		_node = &MailDomain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(maildomain.Table, sqlgraph.NewFieldSpec(maildomain.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(maildomain.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(maildomain.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Desc(); ok {
		_spec.SetField(maildomain.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(maildomain.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateErased(); ok {
		_spec.SetField(maildomain.FieldDateErased, field.TypeTime, value)
		_node.DateErased = &value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(maildomain.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   maildomain.TenantTable,
			Columns: []string{maildomain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MailDomainCreateBulk is the builder for creating many MailDomain entities in bulk.
type MailDomainCreateBulk struct {
	config
	err      error
	builders []*MailDomainCreate
}

// Save creates the MailDomain entities in the database.
func (_c *MailDomainCreateBulk) Save(ctx context.Context) ([]*MailDomain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MailDomain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MailDomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MailDomainCreateBulk) SaveX(ctx context.Context) []*MailDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailDomainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailDomainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
