// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/membership.proto

package ent

import (
	uuid "github.com/google/uuid"
	rstr "github.com/lesomnus/roster/rstr"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *SiteMembership) Proto() *rstr.SiteMembership {
	x := &rstr.SiteMembership{}
	x.SetId(e.ID[:])
	if v := e.Edges.Holder; v != nil {
		x.SetHolder(v.Proto())
	} else if v := e.HolderID; v != *new(uuid.UUID) {
		r := &rstr.Holder{}
		r.SetId(v[:])
		x.SetHolder(r)
	}
	if v := e.Edges.Site; v != nil {
		x.SetSite(v.Proto())
	} else if v := e.SiteID; v != *new(uuid.UUID) {
		r := &rstr.Site{}
		r.SetId(v[:])
		x.SetSite(r)
	}
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
func (e *TeamMembership) Proto() *rstr.TeamMembership {
	x := &rstr.TeamMembership{}
	x.SetId(e.ID[:])
	if v := e.Edges.Holder; v != nil {
		x.SetHolder(v.Proto())
	} else if v := e.HolderID; v != *new(uuid.UUID) {
		r := &rstr.Holder{}
		r.SetId(v[:])
		x.SetHolder(r)
	}
	if v := e.Edges.Team; v != nil {
		x.SetTeam(v.Proto())
	} else if v := e.TeamID; v != *new(uuid.UUID) {
		r := &rstr.Team{}
		r.SetId(v[:])
		x.SetTeam(r)
	}
	if v := e.Edges.Role; v != nil {
		x.SetRole(v.Proto())
	} else if v := e.RoleID; v != *new(uuid.UUID) {
		r := &rstr.Role{}
		r.SetId(v[:])
		x.SetRole(r)
	}
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
