// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/nomination.proto

package ent

import (
	rstr "github.com/lesomnus/roster/rstr"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	uuid "uuid"
)

func (e *Nomination) Proto() *rstr.Nomination {
	x := &rstr.Nomination{}
	x.SetId(e.Id[:])
	if v := e.Edges.Tenant; v != nil {
		x.SetTenant(v.Proto())
	} else if v := e.TenantId; v != *new(uuid.UUID) {
		r := &rstr.Tenant{}
		r.SetId(v[:])
		x.SetTenant(r)
	}
	x.SetLabels(e.Labels)
	x.SetName(e.Name)
	x.SetBorrowerId(e.BorrowerId[:])
	if v := e.Edges.ActsAs; v != nil {
		x.SetActsAs(v.Proto())
	} else if v := e.ActsAsId; v != *new(uuid.UUID) {
		r := &rstr.Holder{}
		r.SetId(v[:])
		x.SetActsAs(r)
	}
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
