// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: roster/payday/outbox.proto

package ent

import (
	rstr "github.com/lesomnus/roster/rstr"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Outbox) Proto() *rstr.Outbox {
	x := &rstr.Outbox{}
	x.SetId(e.Id[:])
	x.SetTenantId(e.TenantId[:])
	x.SetActorId(e.ActorId[:])
	x.SetMethod(e.Method)
	x.SetBy(e.By)
	x.SetObjectId(e.ObjectId[:])
	x.SetPatch(e.Patch)
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
