// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/role"
	"github.com/lesomnus/roster/internal/ent/site"
	"github.com/lesomnus/roster/internal/ent/tenant"
)

// RoleCreate is the builder for creating a Role entity.
type RoleCreate struct {
	config
	mutation *RoleMutation
	hooks    []Hook
}

// SetAlias sets the "alias" field.
func (_c *RoleCreate) SetAlias(v string) *RoleCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RoleCreate) SetName(v string) *RoleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDesc sets the "desc" field.
func (_c *RoleCreate) SetDesc(v string) *RoleCreate {
	_c.mutation.SetDesc(v)
	return _c
}

// SetMethods sets the "methods" field.
func (_c *RoleCreate) SetMethods(v []string) *RoleCreate {
	_c.mutation.SetMethods(v)
	return _c
}

// SetEveryMethod sets the "every_method" field.
func (_c *RoleCreate) SetEveryMethod(v bool) *RoleCreate {
	_c.mutation.SetEveryMethod(v)
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *RoleCreate) SetDateUpdated(v time.Time) *RoleCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateErased sets the "date_erased" field.
func (_c *RoleCreate) SetDateErased(v time.Time) *RoleCreate {
	_c.mutation.SetDateErased(v)
	return _c
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_c *RoleCreate) SetNillableDateErased(v *time.Time) *RoleCreate {
	if v != nil {
		_c.SetDateErased(*v)
	}
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *RoleCreate) SetDateCreated(v time.Time) *RoleCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *RoleCreate) SetNillableDateCreated(v *time.Time) *RoleCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *RoleCreate) SetTenantID(v uuid.UUID) *RoleCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetSiteID sets the "site_id" field.
func (_c *RoleCreate) SetSiteID(v uuid.UUID) *RoleCreate {
	_c.mutation.SetSiteID(v)
	return _c
}

// SetNillableSiteID sets the "site_id" field if the given value is not nil.
func (_c *RoleCreate) SetNillableSiteID(v *uuid.UUID) *RoleCreate {
	if v != nil {
		_c.SetSiteID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RoleCreate) SetID(v uuid.UUID) *RoleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *RoleCreate) SetTenant(v *Tenant) *RoleCreate {
	return _c.SetTenantID(v.ID)
}

// SetSite sets the "site" edge to the Site entity.
func (_c *RoleCreate) SetSite(v *Site) *RoleCreate {
	return _c.SetSiteID(v.ID)
}

// Mutation returns the RoleMutation object of the builder.
func (_c *RoleCreate) Mutation() *RoleMutation {
	return _c.mutation
}

// Save creates the Role in the database.
func (_c *RoleCreate) Save(ctx context.Context) (*Role, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoleCreate) SaveX(ctx context.Context) *Role {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoleCreate) check() error {
	if _, ok := _c.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "Role.alias"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Role.name"`)}
	}
	if _, ok := _c.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "Role.desc"`)}
	}
	if _, ok := _c.mutation.EveryMethod(); !ok {
		return &ValidationError{Name: "every_method", err: errors.New(`ent: missing required field "Role.every_method"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "Role.date_updated"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Role.tenant_id"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Role.tenant"`)}
	}
	return nil
}

func (_c *RoleCreate) sqlSave(ctx context.Context) (*Role, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoleCreate) createSpec() (*Role, *sqlgraph.CreateSpec) {
	var (
		_node = &Role{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(role.Table, sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(role.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(role.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Desc(); ok {
		_spec.SetField(role.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := _c.mutation.Methods(); ok {
		_spec.SetField(role.FieldMethods, field.TypeJSON, value)
		_node.Methods = value
	}
	if value, ok := _c.mutation.EveryMethod(); ok {
		_spec.SetField(role.FieldEveryMethod, field.TypeBool, value)
		_node.EveryMethod = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(role.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateErased(); ok {
		_spec.SetField(role.FieldDateErased, field.TypeTime, value)
		_node.DateErased = &value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(role.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   role.TenantTable,
			Columns: []string{role.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SiteIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   role.SiteTable,
			Columns: []string{role.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RoleCreateBulk is the builder for creating many Role entities in bulk.
type RoleCreateBulk struct {
	config
	err      error
	builders []*RoleCreate
}

// Save creates the Role entities in the database.
func (_c *RoleCreateBulk) Save(ctx context.Context) ([]*Role, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Role, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoleCreateBulk) SaveX(ctx context.Context) []*Role {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
