// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/roster/internal/ent/role"
	"github.com/lesomnus/roster/internal/ent/site"
	"github.com/lesomnus/roster/internal/ent/tenant"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// RoleCreate is the builder for creating a Role entity.
type RoleCreate struct {
	config
	mutation *RoleMutation
	hooks    []Hook
}

// SetAlias sets the "alias" field.
func (_c *RoleCreate) SetAlias(v string) *RoleCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RoleCreate) SetName(v string) *RoleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDesc sets the "desc" field.
func (_c *RoleCreate) SetDesc(v string) *RoleCreate {
	_c.mutation.SetDesc(v)
	return _c
}

// SetMethods sets the "methods" field.
func (_c *RoleCreate) SetMethods(v []string) *RoleCreate {
	_c.mutation.SetMethods(v)
	return _c
}

// SetDateUpdated sets the "date_updated" field.
func (_c *RoleCreate) SetDateUpdated(v time.Time) *RoleCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateErased sets the "date_erased" field.
func (_c *RoleCreate) SetDateErased(v time.Time) *RoleCreate {
	_c.mutation.SetDateErased(v)
	return _c
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_c *RoleCreate) SetNillableDateErased(v *time.Time) *RoleCreate {
	if v != nil {
		_c.SetDateErased(*v)
	}
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *RoleCreate) SetDateCreated(v time.Time) *RoleCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *RoleCreate) SetNillableDateCreated(v *time.Time) *RoleCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetTenantId sets the "tenant_id" field.
func (_c *RoleCreate) SetTenantId(v uuid.UUID) *RoleCreate {
	_c.mutation.SetTenantId(v)
	return _c
}

// SetSiteId sets the "site_id" field.
func (_c *RoleCreate) SetSiteId(v uuid.UUID) *RoleCreate {
	_c.mutation.SetSiteId(v)
	return _c
}

// SetNillableSiteId sets the "site_id" field if the given value is not nil.
func (_c *RoleCreate) SetNillableSiteId(v *uuid.UUID) *RoleCreate {
	if v != nil {
		_c.SetSiteId(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *RoleCreate) SetId(v uuid.UUID) *RoleCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *RoleCreate) SetTenant(v *Tenant) *RoleCreate {
	return _c.SetTenantId(v.Id)
}

// SetSite sets the "site" edge to the Site entity.
func (_c *RoleCreate) SetSite(v *Site) *RoleCreate {
	return _c.SetSiteId(v.Id)
}

// Mutation returns the RoleMutation object of the builder.
func (_c *RoleCreate) Mutation() *RoleMutation {
	return _c.mutation
}

// Save creates the Role in the database.
func (_c *RoleCreate) Save(ctx context.Context) (*Role, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoleCreate) SaveX(ctx context.Context) *Role {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoleCreate) check() error {
	if _, ok := _c.mutation.Alias(); !ok {
		return &ValidationError{Name: "alias", err: errors.New(`ent: missing required field "Role.alias"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Role.name"`)}
	}
	if _, ok := _c.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "Role.desc"`)}
	}
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "Role.date_updated"`)}
	}
	if _, ok := _c.mutation.TenantId(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Role.tenant_id"`)}
	}
	if len(_c.mutation.TenantIds()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Role.tenant"`)}
	}
	return nil
}

func (_c *RoleCreate) sqlSave(ctx context.Context) (*Role, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec, err := _c.createSpec()
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		sv, ok := _spec.Id.Value.(field.ValueScanner)
		if !ok {
			sv = role.ValueScanner.Id.ScanValue()
			if err := sv.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
		}
		if value, err := role.ValueScanner.Id.FromValue(sv); err != nil {
			return nil, err
		} else {
			_node.Id = value
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoleCreate) createSpec() (*Role, *sqlgraph.CreateSpec, error) {
	var (
		_node = &Role{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(role.Table, sqlgraph.NewFieldSpec(role.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		vv, err := role.ValueScanner.Id.Value(id)
		if err != nil {
			return nil, nil, err
		}
		_spec.Id.Value = vv
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(role.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(role.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Desc(); ok {
		_spec.SetField(role.FieldDesc, field.TypeString, value)
		_node.Desc = value
	}
	if value, ok := _c.mutation.Methods(); ok {
		_spec.SetField(role.FieldMethods, field.TypeJson, value)
		_node.Methods = value
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(role.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateErased(); ok {
		_spec.SetField(role.FieldDateErased, field.TypeTime, value)
		_node.DateErased = &value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(role.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.TenantIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   role.TenantTable,
			Columns: []string{role.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(tenant.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			vv, err := tenant.ValueScanner.Id.Value(k)
			if err != nil {
				return nil, nil, err
			}
			edge.Target.Nodes = append(edge.Target.Nodes, vv)
		}
		_node.TenantId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SiteIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   role.SiteTable,
			Columns: []string{role.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(site.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			vv, err := site.ValueScanner.Id.Value(k)
			if err != nil {
				return nil, nil, err
			}
			edge.Target.Nodes = append(edge.Target.Nodes, vv)
		}
		_node.SiteId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec, nil
}

// RoleCreateBulk is the builder for creating many Role entities in bulk.
type RoleCreateBulk struct {
	config
	err      error
	builders []*RoleCreate
}

// Save creates the Role entities in the database.
func (_c *RoleCreateBulk) Save(ctx context.Context) ([]*Role, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Role, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i], err = builder.createSpec()
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				if specs[i].Id.Value != nil {
					sv, ok := specs[i].Id.Value.(field.ValueScanner)
					if !ok {
						sv = role.ValueScanner.Id.ScanValue()
						if err := sv.Scan(specs[i].Id.Value); err != nil {
							return nil, err
						}
					}
					if id, err := role.ValueScanner.Id.FromValue(sv); err != nil {
						return nil, err
					} else {
						nodes[i].Id = id
					}
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoleCreateBulk) SaveX(ctx context.Context) []*Role {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
