// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"uuid"

	"github.com/lesomnus/roster/internal/ent/holder"
	"github.com/lesomnus/roster/internal/ent/site"
	"github.com/lesomnus/roster/internal/ent/sitemembership"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// SiteMembershipCreate is the builder for creating a SiteMembership entity.
type SiteMembershipCreate struct {
	config
	mutation *SiteMembershipMutation
	hooks    []Hook
}

// SetDateUpdated sets the "date_updated" field.
func (_c *SiteMembershipCreate) SetDateUpdated(v time.Time) *SiteMembershipCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateErased sets the "date_erased" field.
func (_c *SiteMembershipCreate) SetDateErased(v time.Time) *SiteMembershipCreate {
	_c.mutation.SetDateErased(v)
	return _c
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_c *SiteMembershipCreate) SetNillableDateErased(v *time.Time) *SiteMembershipCreate {
	if v != nil {
		_c.SetDateErased(*v)
	}
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *SiteMembershipCreate) SetDateCreated(v time.Time) *SiteMembershipCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *SiteMembershipCreate) SetNillableDateCreated(v *time.Time) *SiteMembershipCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetHolderId sets the "holder_id" field.
func (_c *SiteMembershipCreate) SetHolderId(v uuid.UUID) *SiteMembershipCreate {
	_c.mutation.SetHolderId(v)
	return _c
}

// SetSiteId sets the "site_id" field.
func (_c *SiteMembershipCreate) SetSiteId(v uuid.UUID) *SiteMembershipCreate {
	_c.mutation.SetSiteId(v)
	return _c
}

// SetId sets the "id" field.
func (_c *SiteMembershipCreate) SetId(v uuid.UUID) *SiteMembershipCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetHolder sets the "holder" edge to the Holder entity.
func (_c *SiteMembershipCreate) SetHolder(v *Holder) *SiteMembershipCreate {
	return _c.SetHolderId(v.Id)
}

// SetSite sets the "site" edge to the Site entity.
func (_c *SiteMembershipCreate) SetSite(v *Site) *SiteMembershipCreate {
	return _c.SetSiteId(v.Id)
}

// Mutation returns the SiteMembershipMutation object of the builder.
func (_c *SiteMembershipCreate) Mutation() *SiteMembershipMutation {
	return _c.mutation
}

// Save creates the SiteMembership in the database.
func (_c *SiteMembershipCreate) Save(ctx context.Context) (*SiteMembership, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SiteMembershipCreate) SaveX(ctx context.Context) *SiteMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SiteMembershipCreate) check() error {
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "SiteMembership.date_updated"`)}
	}
	if _, ok := _c.mutation.HolderId(); !ok {
		return &ValidationError{Name: "holder_id", err: errors.New(`ent: missing required field "SiteMembership.holder_id"`)}
	}
	if _, ok := _c.mutation.SiteId(); !ok {
		return &ValidationError{Name: "site_id", err: errors.New(`ent: missing required field "SiteMembership.site_id"`)}
	}
	if len(_c.mutation.HolderIds()) == 0 {
		return &ValidationError{Name: "holder", err: errors.New(`ent: missing required edge "SiteMembership.holder"`)}
	}
	if len(_c.mutation.SiteIds()) == 0 {
		return &ValidationError{Name: "site", err: errors.New(`ent: missing required edge "SiteMembership.site"`)}
	}
	return nil
}

func (_c *SiteMembershipCreate) sqlSave(ctx context.Context) (*SiteMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else {
			var v sql.Null[uuid.UUID]
			if err := v.Scan(_spec.Id.Value); err != nil {
				return nil, err
			}
			_node.Id = v.V
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *SiteMembershipCreate) createSpec() (*SiteMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &SiteMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sitemembership.Table, sqlgraph.NewFieldSpec(sitemembership.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(sitemembership.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateErased(); ok {
		_spec.SetField(sitemembership.FieldDateErased, field.TypeTime, value)
		_node.DateErased = &value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(sitemembership.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.HolderIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitemembership.HolderTable,
			Columns: []string{sitemembership.HolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(holder.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HolderId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SiteIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sitemembership.SiteTable,
			Columns: []string{sitemembership.SiteColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(site.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SiteId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SiteMembershipCreateBulk is the builder for creating many SiteMembership entities in bulk.
type SiteMembershipCreateBulk struct {
	config
	err      error
	builders []*SiteMembershipCreate
}

// Save creates the SiteMembership entities in the database.
func (_c *SiteMembershipCreateBulk) Save(ctx context.Context) ([]*SiteMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SiteMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SiteMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SiteMembershipCreateBulk) SaveX(ctx context.Context) []*SiteMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SiteMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SiteMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
