// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/holder"
	"github.com/lesomnus/roster/internal/ent/role"
	"github.com/lesomnus/roster/internal/ent/team"
	"github.com/lesomnus/roster/internal/ent/teammembership"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	"github.com/protobuf-orm/ent/schema/field"
)

// TeamMembershipCreate is the builder for creating a TeamMembership entity.
type TeamMembershipCreate struct {
	config
	mutation *TeamMembershipMutation
	hooks    []Hook
}

// SetDateUpdated sets the "date_updated" field.
func (_c *TeamMembershipCreate) SetDateUpdated(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetDateUpdated(v)
	return _c
}

// SetDateErased sets the "date_erased" field.
func (_c *TeamMembershipCreate) SetDateErased(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetDateErased(v)
	return _c
}

// SetNillableDateErased sets the "date_erased" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableDateErased(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetDateErased(*v)
	}
	return _c
}

// SetDateCreated sets the "date_created" field.
func (_c *TeamMembershipCreate) SetDateCreated(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetDateCreated(v)
	return _c
}

// SetNillableDateCreated sets the "date_created" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableDateCreated(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetDateCreated(*v)
	}
	return _c
}

// SetHolderId sets the "holder_id" field.
func (_c *TeamMembershipCreate) SetHolderId(v uuid.UUID) *TeamMembershipCreate {
	_c.mutation.SetHolderId(v)
	return _c
}

// SetTeamId sets the "team_id" field.
func (_c *TeamMembershipCreate) SetTeamId(v uuid.UUID) *TeamMembershipCreate {
	_c.mutation.SetTeamId(v)
	return _c
}

// SetRoleId sets the "role_id" field.
func (_c *TeamMembershipCreate) SetRoleId(v uuid.UUID) *TeamMembershipCreate {
	_c.mutation.SetRoleId(v)
	return _c
}

// SetNillableRoleId sets the "role_id" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableRoleId(v *uuid.UUID) *TeamMembershipCreate {
	if v != nil {
		_c.SetRoleId(*v)
	}
	return _c
}

// SetId sets the "id" field.
func (_c *TeamMembershipCreate) SetId(v uuid.UUID) *TeamMembershipCreate {
	_c.mutation.SetId(v)
	return _c
}

// SetHolder sets the "holder" edge to the Holder entity.
func (_c *TeamMembershipCreate) SetHolder(v *Holder) *TeamMembershipCreate {
	return _c.SetHolderId(v.Id)
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamMembershipCreate) SetTeam(v *Team) *TeamMembershipCreate {
	return _c.SetTeamId(v.Id)
}

// SetRole sets the "role" edge to the Role entity.
func (_c *TeamMembershipCreate) SetRole(v *Role) *TeamMembershipCreate {
	return _c.SetRoleId(v.Id)
}

// Mutation returns the TeamMembershipMutation object of the builder.
func (_c *TeamMembershipCreate) Mutation() *TeamMembershipMutation {
	return _c.mutation
}

// Save creates the TeamMembership in the database.
func (_c *TeamMembershipCreate) Save(ctx context.Context) (*TeamMembership, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamMembershipCreate) SaveX(ctx context.Context) *TeamMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamMembershipCreate) check() error {
	if _, ok := _c.mutation.DateUpdated(); !ok {
		return &ValidationError{Name: "date_updated", err: errors.New(`ent: missing required field "TeamMembership.date_updated"`)}
	}
	if _, ok := _c.mutation.HolderId(); !ok {
		return &ValidationError{Name: "holder_id", err: errors.New(`ent: missing required field "TeamMembership.holder_id"`)}
	}
	if _, ok := _c.mutation.TeamId(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "TeamMembership.team_id"`)}
	}
	if len(_c.mutation.HolderIds()) == 0 {
		return &ValidationError{Name: "holder", err: errors.New(`ent: missing required edge "TeamMembership.holder"`)}
	}
	if len(_c.mutation.TeamIds()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "TeamMembership.team"`)}
	}
	return nil
}

func (_c *TeamMembershipCreate) sqlSave(ctx context.Context) (*TeamMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.Id.Value != nil {
		if id, ok := _spec.Id.Value.(*uuid.UUID); ok {
			_node.Id = *id
		} else if err := _node.Id.Scan(_spec.Id.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.Id
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamMembershipCreate) createSpec() (*TeamMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teammembership.Table, sqlgraph.NewFieldSpec(teammembership.FieldId, field.TypeUuid))
	)
	if id, ok := _c.mutation.Id(); ok {
		_node.Id = id
		_spec.Id.Value = &id
	}
	if value, ok := _c.mutation.DateUpdated(); ok {
		_spec.SetField(teammembership.FieldDateUpdated, field.TypeTime, value)
		_node.DateUpdated = value
	}
	if value, ok := _c.mutation.DateErased(); ok {
		_spec.SetField(teammembership.FieldDateErased, field.TypeTime, value)
		_node.DateErased = &value
	}
	if value, ok := _c.mutation.DateCreated(); ok {
		_spec.SetField(teammembership.FieldDateCreated, field.TypeTime, value)
		_node.DateCreated = value
	}
	if nodes := _c.mutation.HolderIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teammembership.HolderTable,
			Columns: []string{teammembership.HolderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(holder.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.HolderId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(team.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoleIds(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teammembership.RoleTable,
			Columns: []string{teammembership.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IdSpec: sqlgraph.NewFieldSpec(role.FieldId, field.TypeUuid),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TeamMembershipCreateBulk is the builder for creating many TeamMembership entities in bulk.
type TeamMembershipCreateBulk struct {
	config
	err      error
	builders []*TeamMembershipCreate
}

// Save creates the TeamMembership entities in the database.
func (_c *TeamMembershipCreateBulk) Save(ctx context.Context) ([]*TeamMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].Id
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamMembershipCreateBulk) SaveX(ctx context.Context) []*TeamMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
