// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/holder"
	"github.com/lesomnus/roster/internal/ent/role"
	"github.com/lesomnus/roster/internal/ent/team"
	"github.com/lesomnus/roster/internal/ent/teammembership"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// TeamMembership is the model entity for the TeamMembership schema.
type TeamMembership struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DateUpdated holds the value of the "date_updated" field.
	DateUpdated time.Time `json:"date_updated,omitempty"`
	// DateErased holds the value of the "date_erased" field.
	DateErased *time.Time `json:"date_erased,omitempty"`
	// DateCreated holds the value of the "date_created" field.
	DateCreated time.Time `json:"date_created,omitempty"`
	// HolderID holds the value of the "holder_id" field.
	HolderID uuid.UUID `json:"holder_id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID uuid.UUID `json:"team_id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID uuid.UUID `json:"role_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TeamMembershipQuery when eager-loading is set.
	Edges        TeamMembershipEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TeamMembershipEdges holds the relations/edges for other nodes in the graph.
type TeamMembershipEdges struct {
	// Holder holds the value of the holder edge.
	Holder *Holder `json:"holder,omitempty"`
	// Team holds the value of the team edge.
	Team *Team `json:"team,omitempty"`
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// HolderOrErr returns the Holder value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamMembershipEdges) HolderOrErr() (*Holder, error) {
	if e.Holder != nil {
		return e.Holder, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: holder.Label}
	}
	return nil, &NotLoadedError{edge: "holder"}
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamMembershipEdges) TeamOrErr() (*Team, error) {
	if e.Team != nil {
		return e.Team, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: team.Label}
	}
	return nil, &NotLoadedError{edge: "team"}
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TeamMembershipEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TeamMembership) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case teammembership.FieldDateUpdated, teammembership.FieldDateErased, teammembership.FieldDateCreated:
			values[i] = new(sql.NullTime)
		case teammembership.FieldID, teammembership.FieldHolderID, teammembership.FieldTeamID, teammembership.FieldRoleID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TeamMembership fields.
func (_m *TeamMembership) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case teammembership.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case teammembership.FieldDateUpdated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_updated", values[i])
			} else if value.Valid {
				_m.DateUpdated = value.Time
			}
		case teammembership.FieldDateErased:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_erased", values[i])
			} else if value.Valid {
				_m.DateErased = new(time.Time)
				*_m.DateErased = value.Time
			}
		case teammembership.FieldDateCreated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_created", values[i])
			} else if value.Valid {
				_m.DateCreated = value.Time
			}
		case teammembership.FieldHolderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field holder_id", values[i])
			} else if value != nil {
				_m.HolderID = *value
			}
		case teammembership.FieldTeamID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value != nil {
				_m.TeamID = *value
			}
		case teammembership.FieldRoleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value != nil {
				_m.RoleID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TeamMembership.
// This includes values selected through modifiers, order, etc.
func (_m *TeamMembership) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHolder queries the "holder" edge of the TeamMembership entity.
func (_m *TeamMembership) QueryHolder() *HolderQuery {
	return NewTeamMembershipClient(_m.config).QueryHolder(_m)
}

// QueryTeam queries the "team" edge of the TeamMembership entity.
func (_m *TeamMembership) QueryTeam() *TeamQuery {
	return NewTeamMembershipClient(_m.config).QueryTeam(_m)
}

// QueryRole queries the "role" edge of the TeamMembership entity.
func (_m *TeamMembership) QueryRole() *RoleQuery {
	return NewTeamMembershipClient(_m.config).QueryRole(_m)
}

// Update returns a builder for updating this TeamMembership.
// Note that you need to call TeamMembership.Unwrap() before calling this method if this TeamMembership
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TeamMembership) Update() *TeamMembershipUpdateOne {
	return NewTeamMembershipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TeamMembership entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TeamMembership) Unwrap() *TeamMembership {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TeamMembership is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TeamMembership) String() string {
	var builder strings.Builder
	builder.WriteString("TeamMembership(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("date_updated=")
	builder.WriteString(_m.DateUpdated.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DateErased; v != nil {
		builder.WriteString("date_erased=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("date_created=")
	builder.WriteString(_m.DateCreated.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("holder_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HolderID))
	builder.WriteString(", ")
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TeamID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteByte(')')
	return builder.String()
}

// TeamMembershipList is a parsable slice of TeamMembership.
type TeamMembershipList []*TeamMembership
