// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/thing.proto

package ent

import (
	uuid "github.com/google/uuid"
	roster "github.com/lesomnus/roster"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

func (e *Thing) Proto() *roster.Thing {
	x := &roster.Thing{}
	x.SetId(e.ID[:])
	if v := e.Edges.Tenant; v != nil {
		x.SetTenant(v.Proto())
	} else if v := e.TenantID; v != *new(uuid.UUID) {
		r := &roster.Tenant{}
		r.SetId(v[:])
		x.SetTenant(r)
	}
	x.SetAlias(e.Alias)
	x.SetDesc(e.Desc)
	if e.DateErased != nil {
		x.SetDateErased(timestamppb.New(*e.DateErased))
	}
	x.SetDateUpdated(timestamppb.New(e.DateUpdated))
	x.SetDateCreated(timestamppb.New(e.DateCreated))
	return x
}
