// Code generated by ent, DO NOT EDIT.

package continuation

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the continuation type in the database.
	Label = "continuation"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldSatisfied holds the string denoting the satisfied field in the database.
	FieldSatisfied = "satisfied"
	// FieldSecret holds the string denoting the secret field in the database.
	FieldSecret = "secret"
	// FieldIssuer holds the string denoting the issuer field in the database.
	FieldIssuer = "issuer"
	// FieldMeteredBy holds the string denoting the metered_by field in the database.
	FieldMeteredBy = "metered_by"
	// FieldDateExpires holds the string denoting the date_expires field in the database.
	FieldDateExpires = "date_expires"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldDateErased holds the string denoting the date_erased field in the database.
	FieldDateErased = "date_erased"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldHolderId holds the string denoting the holder_id field in the database.
	FieldHolderId = "holder_id"
	// EdgeHolder holds the string denoting the holder edge name in mutations.
	EdgeHolder = "holder"
	// Table holds the table name of the continuation in the database.
	Table = "continuation"
	// HolderTable is the table that holds the holder relation/edge.
	HolderTable = "continuation"
	// HolderInverseTable is the table name for the Holder entity.
	// It exists in this package in order to avoid circular dependency with the "holder" package.
	HolderInverseTable = "holder"
	// HolderColumn is the table column denoting the holder relation/edge.
	HolderColumn = "holder_id"
)

// Columns holds all SQL columns for continuation fields.
var Columns = []string{
	FieldId,
	FieldSatisfied,
	FieldSecret,
	FieldIssuer,
	FieldMeteredBy,
	FieldDateExpires,
	FieldDateUpdated,
	FieldDateErased,
	FieldDateCreated,
	FieldHolderId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Continuation queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByMeteredBy orders the results by the metered_by field.
func ByMeteredBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeteredBy, opts...).ToFunc()
}

// ByDateExpires orders the results by the date_expires field.
func ByDateExpires(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateExpires, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByDateErased orders the results by the date_erased field.
func ByDateErased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateErased, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByHolderId orders the results by the holder_id field.
func ByHolderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHolderId, opts...).ToFunc()
}

// ByHolderField orders the results by holder field.
func ByHolderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHolderStep(), sql.OrderByField(field, opts...))
	}
}
func newHolderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(HolderInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, HolderTable, HolderColumn),
	)
}
