// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/lesomnus/roster/internal/ent/runtime.go

const (
	Version = "v0.0.0-20260901230746-4115dcfc4087"              // Version of ent codegen.
	Sum     = "h1:1RMN/oonuxWRHdLh1+aDqJsilqEDUp6Tds/ZixA2AkU=" // Sum of ent codegen.
)
