// Code generated by ent, DO NOT EDIT.

package group

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/predicate"
	"github.com/protobuf-orm/ent"
	"github.com/protobuf-orm/ent/dialect/sql"
)

// Mutation represents an operation that mutates the Group nodes in the graph.
type Mutation struct {
	op            ent.Op
	typ           string
	alias         *string
	name          *string
	desc          *string
	date_updated  *time.Time
	date_erased   *time.Time
	date_created  *time.Time
	clearedFields map[string]struct{}
	tenant        *uuid.UUID
	clearedtenant bool
	site          *uuid.UUID
	clearedsite   bool
	predicates    []predicate.Group
}

// NewMutation creates a new Mutation for the Group entity.
func NewMutation(op ent.Op) *Mutation {
	return &Mutation{
		op:            op,
		typ:           "Group",
		clearedFields: make(map[string]struct{}),
	}
}

// Predicates returns the list of predicates set on the mutation.
func (m *Mutation) Predicates() []predicate.Group {
	return m.predicates
}

// SetAlias sets the "alias" field.
func (m *Mutation) SetAlias(s string) {
	m.alias = &s
}

// Alias returns the value of the "alias" field in the mutation.
func (m *Mutation) Alias() (r string, exists bool) {
	v := m.alias
	if v == nil {
		return
	}
	return *v, true
}

// ResetAlias resets all changes to the "alias" field.
func (m *Mutation) ResetAlias() {
	m.alias = nil
}

// SetName sets the "name" field.
func (m *Mutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *Mutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// ResetName resets all changes to the "name" field.
func (m *Mutation) ResetName() {
	m.name = nil
}

// SetDesc sets the "desc" field.
func (m *Mutation) SetDesc(s string) {
	m.desc = &s
}

// Desc returns the value of the "desc" field in the mutation.
func (m *Mutation) Desc() (r string, exists bool) {
	v := m.desc
	if v == nil {
		return
	}
	return *v, true
}

// ResetDesc resets all changes to the "desc" field.
func (m *Mutation) ResetDesc() {
	m.desc = nil
}

// SetDateUpdated sets the "date_updated" field.
func (m *Mutation) SetDateUpdated(t time.Time) {
	m.date_updated = &t
}

// DateUpdated returns the value of the "date_updated" field in the mutation.
func (m *Mutation) DateUpdated() (r time.Time, exists bool) {
	v := m.date_updated
	if v == nil {
		return
	}
	return *v, true
}

// ResetDateUpdated resets all changes to the "date_updated" field.
func (m *Mutation) ResetDateUpdated() {
	m.date_updated = nil
}

// SetDateErased sets the "date_erased" field.
func (m *Mutation) SetDateErased(t time.Time) {
	m.date_erased = &t
}

// DateErased returns the value of the "date_erased" field in the mutation.
func (m *Mutation) DateErased() (r time.Time, exists bool) {
	v := m.date_erased
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateErased clears the value of the "date_erased" field.
func (m *Mutation) ClearDateErased() {
	m.date_erased = nil
	m.clearedFields[FieldDateErased] = struct{}{}
}

// DateErasedCleared returns if the "date_erased" field was cleared in this mutation.
func (m *Mutation) DateErasedCleared() bool {
	_, ok := m.clearedFields[FieldDateErased]
	return ok
}

// ResetDateErased resets all changes to the "date_erased" field.
func (m *Mutation) ResetDateErased() {
	m.date_erased = nil
	delete(m.clearedFields, FieldDateErased)
}

// SetDateCreated sets the "date_created" field.
func (m *Mutation) SetDateCreated(t time.Time) {
	m.date_created = &t
}

// DateCreated returns the value of the "date_created" field in the mutation.
func (m *Mutation) DateCreated() (r time.Time, exists bool) {
	v := m.date_created
	if v == nil {
		return
	}
	return *v, true
}

// ClearDateCreated clears the value of the "date_created" field.
func (m *Mutation) ClearDateCreated() {
	m.date_created = nil
	m.clearedFields[FieldDateCreated] = struct{}{}
}

// DateCreatedCleared returns if the "date_created" field was cleared in this mutation.
func (m *Mutation) DateCreatedCleared() bool {
	_, ok := m.clearedFields[FieldDateCreated]
	return ok
}

// ResetDateCreated resets all changes to the "date_created" field.
func (m *Mutation) ResetDateCreated() {
	m.date_created = nil
	delete(m.clearedFields, FieldDateCreated)
}

// SetTenantId sets the "tenant_id" field.
func (m *Mutation) SetTenantId(u uuid.UUID) {
	m.tenant = &u
}

// TenantId returns the value of the "tenant_id" field in the mutation.
func (m *Mutation) TenantId() (r uuid.UUID, exists bool) {
	v := m.tenant
	if v == nil {
		return
	}
	return *v, true
}

// ResetTenantId resets all changes to the "tenant_id" field.
func (m *Mutation) ResetTenantId() {
	m.tenant = nil
}

// SetSiteId sets the "site_id" field.
func (m *Mutation) SetSiteId(u uuid.UUID) {
	m.site = &u
}

// SiteId returns the value of the "site_id" field in the mutation.
func (m *Mutation) SiteId() (r uuid.UUID, exists bool) {
	v := m.site
	if v == nil {
		return
	}
	return *v, true
}

// ClearSiteId clears the value of the "site_id" field.
func (m *Mutation) ClearSiteId() {
	m.site = nil
	m.clearedFields[FieldSiteId] = struct{}{}
}

// SiteIdCleared returns if the "site_id" field was cleared in this mutation.
func (m *Mutation) SiteIdCleared() bool {
	_, ok := m.clearedFields[FieldSiteId]
	return ok
}

// ResetSiteId resets all changes to the "site_id" field.
func (m *Mutation) ResetSiteId() {
	m.site = nil
	delete(m.clearedFields, FieldSiteId)
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (m *Mutation) ClearTenant() {
	m.clearedtenant = true
	m.clearedFields[FieldTenantId] = struct{}{}
}

// TenantCleared reports if the "tenant" edge to the Tenant entity was cleared.
func (m *Mutation) TenantCleared() bool {
	return m.clearedtenant
}

// TenantIds returns the "tenant" edge Ids in the mutation.
// Note that Ids always returns len(Ids) <= 1 for unique edges, and you should use
// TenantId instead. It exists only for internal usage by the builders.
func (m *Mutation) TenantIds() (ids []uuid.UUID) {
	if id := m.tenant; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTenant resets all changes to the "tenant" edge.
func (m *Mutation) ResetTenant() {
	m.tenant = nil
	m.clearedtenant = false
}

// ClearSite clears the "site" edge to the Site entity.
func (m *Mutation) ClearSite() {
	m.clearedsite = true
	m.clearedFields[FieldSiteId] = struct{}{}
}

// SiteCleared reports if the "site" edge to the Site entity was cleared.
func (m *Mutation) SiteCleared() bool {
	return m.SiteIdCleared() || m.clearedsite
}

// SiteIds returns the "site" edge Ids in the mutation.
// Note that Ids always returns len(Ids) <= 1 for unique edges, and you should use
// SiteId instead. It exists only for internal usage by the builders.
func (m *Mutation) SiteIds() (ids []uuid.UUID) {
	if id := m.site; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetSite resets all changes to the "site" edge.
func (m *Mutation) ResetSite() {
	m.site = nil
	m.clearedsite = false
}

// Where appends a list predicates to the Mutation builder.
func (m *Mutation) Where(ps ...predicate.Group) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the Mutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *Mutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Group, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *Mutation) Op() ent.Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *Mutation) SetOp(op ent.Op) {
	m.op = op
}

// Type returns the node type of this mutation (Group).
func (m *Mutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *Mutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.alias != nil {
		fields = append(fields, FieldAlias)
	}
	if m.name != nil {
		fields = append(fields, FieldName)
	}
	if m.desc != nil {
		fields = append(fields, FieldDesc)
	}
	if m.date_updated != nil {
		fields = append(fields, FieldDateUpdated)
	}
	if m.date_erased != nil {
		fields = append(fields, FieldDateErased)
	}
	if m.date_created != nil {
		fields = append(fields, FieldDateCreated)
	}
	if m.tenant != nil {
		fields = append(fields, FieldTenantId)
	}
	if m.site != nil {
		fields = append(fields, FieldSiteId)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *Mutation) Field(name string) (ent.Value, bool) {
	switch name {
	case FieldAlias:
		return m.Alias()
	case FieldName:
		return m.Name()
	case FieldDesc:
		return m.Desc()
	case FieldDateUpdated:
		return m.DateUpdated()
	case FieldDateErased:
		return m.DateErased()
	case FieldDateCreated:
		return m.DateCreated()
	case FieldTenantId:
		return m.TenantId()
	case FieldSiteId:
		return m.SiteId()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *Mutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown Group field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) SetField(name string, value ent.Value) error {
	switch name {
	case FieldAlias:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAlias(v)
		return nil
	case FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case FieldDesc:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDesc(v)
		return nil
	case FieldDateUpdated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateUpdated(v)
		return nil
	case FieldDateErased:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateErased(v)
		return nil
	case FieldDateCreated:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDateCreated(v)
		return nil
	case FieldTenantId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantId(v)
		return nil
	case FieldSiteId:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSiteId(v)
		return nil
	}
	return fmt.Errorf("unknown Group field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *Mutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *Mutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *Mutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Group numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *Mutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(FieldDateErased) {
		fields = append(fields, FieldDateErased)
	}
	if m.FieldCleared(FieldDateCreated) {
		fields = append(fields, FieldDateCreated)
	}
	if m.FieldCleared(FieldSiteId) {
		fields = append(fields, FieldSiteId)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *Mutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *Mutation) ClearField(name string) error {
	switch name {
	case FieldDateErased:
		m.ClearDateErased()
		return nil
	case FieldDateCreated:
		m.ClearDateCreated()
		return nil
	case FieldSiteId:
		m.ClearSiteId()
		return nil
	}
	return fmt.Errorf("unknown Group nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *Mutation) ResetField(name string) error {
	switch name {
	case FieldAlias:
		m.ResetAlias()
		return nil
	case FieldName:
		m.ResetName()
		return nil
	case FieldDesc:
		m.ResetDesc()
		return nil
	case FieldDateUpdated:
		m.ResetDateUpdated()
		return nil
	case FieldDateErased:
		m.ResetDateErased()
		return nil
	case FieldDateCreated:
		m.ResetDateCreated()
		return nil
	case FieldTenantId:
		m.ResetTenantId()
		return nil
	case FieldSiteId:
		m.ResetSiteId()
		return nil
	}
	return fmt.Errorf("unknown Group field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *Mutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.tenant != nil {
		edges = append(edges, EdgeTenant)
	}
	if m.site != nil {
		edges = append(edges, EdgeSite)
	}
	return edges
}

// AddedIds returns all Ids (to other nodes) that were added for the given edge
// name in this mutation.
func (m *Mutation) AddedIds(name string) []ent.Value {
	switch name {
	case EdgeTenant:
		if id := m.tenant; id != nil {
			return []ent.Value{*id}
		}
	case EdgeSite:
		if id := m.site; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *Mutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIds returns all Ids (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *Mutation) RemovedIds(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *Mutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedtenant {
		edges = append(edges, EdgeTenant)
	}
	if m.clearedsite {
		edges = append(edges, EdgeSite)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *Mutation) EdgeCleared(name string) bool {
	switch name {
	case EdgeTenant:
		return m.clearedtenant
	case EdgeSite:
		return m.clearedsite
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *Mutation) ClearEdge(name string) error {
	switch name {
	case EdgeTenant:
		m.ClearTenant()
		return nil
	case EdgeSite:
		m.ClearSite()
		return nil
	}
	return fmt.Errorf("unknown Group unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *Mutation) ResetEdge(name string) error {
	switch name {
	case EdgeTenant:
		m.ResetTenant()
		return nil
	case EdgeSite:
		m.ResetSite()
		return nil
	}
	return fmt.Errorf("unknown Group edge %s", name)
}
