// Code generated by ent, DO NOT EDIT.

package email

import (
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the email type in the database.
	Label = "email"
	// FieldId holds the string denoting the id field in the database.
	FieldId = "id"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldDateVerified holds the string denoting the date_verified field in the database.
	FieldDateVerified = "date_verified"
	// FieldTenantId holds the string denoting the tenant_id field in the database.
	FieldTenantId = "tenant_id"
	// FieldDateUpdated holds the string denoting the date_updated field in the database.
	FieldDateUpdated = "date_updated"
	// FieldDateErased holds the string denoting the date_erased field in the database.
	FieldDateErased = "date_erased"
	// FieldDateCreated holds the string denoting the date_created field in the database.
	FieldDateCreated = "date_created"
	// FieldHolderId holds the string denoting the holder_id field in the database.
	FieldHolderId = "holder_id"
	// FieldVouchedById holds the string denoting the vouched_by_id field in the database.
	FieldVouchedById = "vouched_by_id"
	// EdgeHolder holds the string denoting the holder edge name in mutations.
	EdgeHolder = "holder"
	// EdgeVouchedBy holds the string denoting the vouched_by edge name in mutations.
	EdgeVouchedBy = "vouched_by"
	// Table holds the table name of the email in the database.
	Table = "email"
	// HolderTable is the table that holds the holder relation/edge.
	HolderTable = "email"
	// HolderInverseTable is the table name for the Holder entity.
	// It exists in this package in order to avoid circular dependency with the "holder" package.
	HolderInverseTable = "holder"
	// HolderColumn is the table column denoting the holder relation/edge.
	HolderColumn = "holder_id"
	// VouchedByTable is the table that holds the vouched_by relation/edge.
	VouchedByTable = "email"
	// VouchedByInverseTable is the table name for the Identity entity.
	// It exists in this package in order to avoid circular dependency with the "identity" package.
	VouchedByInverseTable = "identity"
	// VouchedByColumn is the table column denoting the vouched_by relation/edge.
	VouchedByColumn = "vouched_by_id"
)

// Columns holds all SQL columns for email fields.
var Columns = []string{
	FieldId,
	FieldAddress,
	FieldDateVerified,
	FieldTenantId,
	FieldDateUpdated,
	FieldDateErased,
	FieldDateCreated,
	FieldHolderId,
	FieldVouchedById,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Email queries.
type OrderOption func(*sql.Selector)

// ById orders the results by the id field.
func ById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldId, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByDateVerified orders the results by the date_verified field.
func ByDateVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateVerified, opts...).ToFunc()
}

// ByTenantId orders the results by the tenant_id field.
func ByTenantId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantId, opts...).ToFunc()
}

// ByDateUpdated orders the results by the date_updated field.
func ByDateUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateUpdated, opts...).ToFunc()
}

// ByDateErased orders the results by the date_erased field.
func ByDateErased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateErased, opts...).ToFunc()
}

// ByDateCreated orders the results by the date_created field.
func ByDateCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateCreated, opts...).ToFunc()
}

// ByHolderId orders the results by the holder_id field.
func ByHolderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHolderId, opts...).ToFunc()
}

// ByVouchedById orders the results by the vouched_by_id field.
func ByVouchedById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVouchedById, opts...).ToFunc()
}

// ByHolderField orders the results by holder field.
func ByHolderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHolderStep(), sql.OrderByField(field, opts...))
	}
}

// ByVouchedByField orders the results by vouched_by field.
func ByVouchedByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVouchedByStep(), sql.OrderByField(field, opts...))
	}
}
func newHolderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(HolderInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, HolderTable, HolderColumn),
	)
}
func newVouchedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldId),
		sqlgraph.To(VouchedByInverseTable, FieldId),
		sqlgraph.Edge(sqlgraph.M2O, false, VouchedByTable, VouchedByColumn),
	)
}
