// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/credential.proto

package bare

import (
	context "context"
	sqlgraph "entgo.io/ent/dialect/sql/sqlgraph"
	errors "errors"
	uuid "github.com/google/uuid"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	ent "github.com/lesomnus/roster/internal/ent"
	credential "github.com/lesomnus/roster/internal/ent/credential"
	predicate "github.com/lesomnus/roster/internal/ent/predicate"
	rstr "github.com/lesomnus/roster/rstr"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	enttx "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/enttx"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type CredentialServiceServer struct {
	Store

	rstr.UnimplementedCredentialServiceServer
}

// NewCredentialServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewCredentialServiceServer(db *ent.Client, opts ...Option) rstr.CredentialServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return CredentialServiceServer{Store: s.Store}
}

// CredentialNarrow answers with `p` and everything else that narrows a
// read of a Credential: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func CredentialNarrow(ctx context.Context, scope Scope, p predicate.Credential) (predicate.Credential, error) {
	ps := make([]predicate.Credential, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, credential.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.CredentialScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return credential.And(ps...), nil
	}
}

// narrow is [CredentialNarrow] with this server's own scope.
func (s CredentialServiceServer) narrow(ctx context.Context, p predicate.Credential) (predicate.Credential, error) {
	return CredentialNarrow(ctx, s.Scope, p)
}

func (s CredentialServiceServer) Add(ctx context.Context, req *rstr.CredentialAddRequest) (*rstr.Credential, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *rstr.Credential), 0, 1)
	q := st.Db.Credential.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "app.Credential", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetID(v)
	}
	if k, err := HolderGetKey(ctx, st.Db, req.GetHolder()); err != nil {
		return nil, err
	} else {
		q.SetHolderID(k)
		ds = append(ds, func(v *rstr.Credential) {
			v.SetHolder(rstr.Holder_builder{Id: k[:]}.Build())
		})
	}
	q.SetKind(req.GetKind())
	q.SetSecret(req.GetSecret())
	q.SetFailures(req.GetFailures())
	if req.HasDateLocked() {
		q.SetDateLocked(req.GetDateLocked().AsTime())
	}
	if req.HasDateRotated() {
		q.SetDateRotated(req.GetDateRotated().AsTime())
	}
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Errorf(codes.AlreadyExists, "Credential already exists: %s", err.Unwrap())
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Errorf(codes.NotFound, "Credential: referenced entity not found: %s", err.Unwrap())
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  rstr.CredentialService_Add_FullMethodName,
		Key: u.ID,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s CredentialServiceServer) Get(ctx context.Context, req *rstr.CredentialGetRequest) (*rstr.Credential, error) {
	p, err := CredentialPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Credential.Query().Where(p)
	CredentialSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Credential not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectCredentialKey(q *ent.CredentialQuery) {
	q.Select(credential.FieldID)
}

func CredentialSelectedFields(m *rstr.CredentialSelect) []string {
	if m.GetAll() {
		return credential.Columns
	}

	vs := make([]string, 0, len(credential.Columns))
	{
		vs = append(vs, credential.FieldID)
	}
	if m.GetKind() {
		vs = append(vs, credential.FieldKind)
	}
	if m.GetSecret() {
		vs = append(vs, credential.FieldSecret)
	}
	if m.GetFailures() {
		vs = append(vs, credential.FieldFailures)
	}
	if m.GetDateLocked() {
		vs = append(vs, credential.FieldDateLocked)
	}
	if m.GetDateRotated() {
		vs = append(vs, credential.FieldDateRotated)
	}
	if m.GetDateUpdated() {
		vs = append(vs, credential.FieldDateUpdated)
	}
	if m.GetDateErased() {
		vs = append(vs, credential.FieldDateErased)
	}
	if m.GetDateCreated() {
		vs = append(vs, credential.FieldDateCreated)
	}

	return vs
}

func CredentialSelect(q *ent.CredentialQuery, m *rstr.CredentialSelect) {
	if !m.GetAll() {
		fields := CredentialSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasHolder() {
		q.WithHolder(func(q *ent.HolderQuery) {
			HolderSelect(q, m.GetHolder())
		})
	}
}

func CredentialSelectInit(q *ent.CredentialQuery, m *rstr.CredentialSelect) {
	if m != nil {
		CredentialSelect(q, m)
	} else {
		q.WithHolder(selectHolderKey)
	}
}

func (s CredentialServiceServer) Patch(ctx context.Context, req *rstr.CredentialPatchRequest) (*rstr.Credential, error) {
	doc, err := ormpatch.FromPatchRequest(credentialOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, rstr.CredentialService_Patch_FullMethodName)
}

func CredentialGetKey(ctx context.Context, db *ent.Client, ref *rstr.CredentialRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := uuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := CredentialPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Credential.Query().Where(p).OnlyID(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Credential not found")
		}
		return z, err
	}

	return v, nil
}

var credentialOrmEntity = ormpatch.MustEntityOf(rstr.File_app_credential_proto, "Credential")

var credentialPatchColumns = entpatch.Columns{
	1: credential.FieldID, 2: credential.HolderColumn, 8: credential.FieldKind, 9: credential.FieldSecret, 10: credential.FieldFailures, 11: credential.FieldDateLocked, 12: credential.FieldDateRotated, 13: credential.FieldDateUpdated, 14: credential.FieldDateErased, 15: credential.FieldDateCreated}

func (s CredentialServiceServer) Apply(ctx context.Context, req *rstr.CredentialApplyRequest) (*rstr.Credential, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), rstr.CredentialService_Apply_FullMethodName)
}

func (s CredentialServiceServer) apply(ctx context.Context, ref *rstr.CredentialRef, doc *patchpb.Patch, by string) (*rstr.Credential, error) {
	plan := &ormpatch.Plan{Entity: credentialOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(credentialOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, credentialPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := CredentialGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &rstr.CredentialRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, credential.IDEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Credential.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Credential(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Credential.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Credential not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Credential.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Credential(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Credential.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Credential not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s CredentialServiceServer) Erase(ctx context.Context, req *rstr.CredentialRef) (*emptypb.Empty, error) {
	p, err := CredentialPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Credential.Query().Where(p).OnlyID(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &emptypb.Empty{}, nil
			}
			return nil, err
		}

		k = v
		p = credential.IDEQ(v)
	}

	u := st.Db.Credential.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  rstr.CredentialService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return &emptypb.Empty{}, nil
}

func CredentialPick(req *rstr.CredentialRef) (predicate.Credential, error) {
	switch req.WhichKey() {
	case rstr.CredentialRef_Id_case:
		if v, err := uuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return credential.IDEQ(v), nil
		}
	case rstr.CredentialRef_Kind_case:
		k := req.GetKind()
		ps := make([]predicate.Credential, 0, 2)
		if p, err := HolderPick(k.GetHolder()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "kind.holder: %s", err)
		} else {
			ps = append(ps, credential.HasHolderWith(p))
		}
		ps = append(ps, credential.KindEQ(k.GetKind()))
		return credential.And(ps...), nil
	case rstr.CredentialRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Credential")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
