// Code generated by protoc-gen-orm-ent. DO NOT EDIT.
// source: app/delegation.proto

package bare

import (
	context "context"
	errors "errors"
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	ent "github.com/lesomnus/roster/internal/ent"
	delegation "github.com/lesomnus/roster/internal/ent/delegation"
	holder "github.com/lesomnus/roster/internal/ent/holder"
	predicate "github.com/lesomnus/roster/internal/ent/predicate"
	rstr "github.com/lesomnus/roster/rstr"
	sqlgraph "github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
	ormpatch "github.com/protobuf-orm/protobuf-orm/ormpatch"
	entpatch "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entpatch"
	enttx "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/enttx"
	entuuid "github.com/protobuf-orm/protoc-gen-orm-ent/runtime/entuuid"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	uuid "uuid"
)

type DelegationServiceServer struct {
	Store

	rstr.UnimplementedDelegationServiceServer
}

// NewDelegationServiceServer answers with a server that runs its queries with `db`.
//
// It takes the options of [Server] so that what is built here can be told
// where to report its writes and what it may see. Built without them, it
// reports nowhere and sees everything.
func NewDelegationServiceServer(db *ent.Client, opts ...Option) rstr.DelegationServiceServer {
	s := Server{Store: Store{Db: db}}
	for _, opt := range opts {
		opt(&s)
	}
	return DelegationServiceServer{Store: s.Store}
}

// DelegationNarrow answers with `p` and everything else that narrows a
// read of a Delegation: the rows that have not been erased, and whatever
// `scope` says of those.
//
// Every read this package makes goes through it, and a read written by
// hand should too -- a List is the one read nothing generates, and so the
// one that would otherwise answer with rows nobody should be given.
func DelegationNarrow(ctx context.Context, scope Scope, p predicate.Delegation) (predicate.Delegation, error) {
	ps := make([]predicate.Delegation, 0, 3)

	// A row that was erased is not a row a read answers with.
	ps = append(ps, delegation.DateErasedIsNil())
	if p != nil {
		ps = append(ps, p)
	}
	if scope != nil {
		q, err := scope.DelegationScope(ctx)
		if err != nil {
			return nil, err
		}
		if q != nil {
			ps = append(ps, q)
		}
	}

	switch len(ps) {
	case 0:
		return nil, nil
	case 1:
		return ps[0], nil
	default:
		return delegation.And(ps...), nil
	}
}

// narrow is [DelegationNarrow] with this server's own scope.
func (s DelegationServiceServer) narrow(ctx context.Context, p predicate.Delegation) (predicate.Delegation, error) {
	return DelegationNarrow(ctx, s.Scope, p)
}

func (s DelegationServiceServer) Add(ctx context.Context, req *rstr.DelegationAddRequest) (*rstr.Delegation, error) {
	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	ds := make([]func(v *rstr.Delegation), 0, 1)
	q := st.Db.Delegation.Create()
	var k uuid.UUID
	if req.HasId() {
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			k = v
		}
	}
	if v, err := mint(ctx, s.Mint, "roster.Delegation", k, req.HasId()); err != nil {
		return nil, err
	} else {
		q.SetId(v)
	}
	if k, err := HolderGetKey(ctx, st.Db, req.GetHolder()); err != nil {
		return nil, err
	} else {
		q.SetHolderId(k)
		ds = append(ds, func(v *rstr.Delegation) {
			v.SetHolder(rstr.Holder_builder{Id: k[:]}.Build())
		})
	}
	if u := req.GetMethods(); len(u) > 0 {
		q.SetMethods(u)
	}
	q.SetSecret(req.GetSecret())
	q.SetIssuer(req.GetIssuer())
	if req.HasDateExpires() {
		q.SetDateExpires(req.GetDateExpires().AsTime())
	}
	q.SetDateUpdated(st.now())
	if req.HasDateCreated() {
		q.SetDateCreated(req.GetDateCreated().AsTime())
	} else {
		q.SetDateCreated(st.now())
	}

	u, err := q.Save(ctx)
	if err != nil {
		if err, ok := err.(*ent.ConstraintError); ok {
			if sqlgraph.IsUniqueConstraintError(err) {
				return nil, status.Error(codes.AlreadyExists, "Delegation already exists")
			}
			if sqlgraph.IsForeignKeyConstraintError(err) {
				return nil, status.Error(codes.NotFound, "Delegation: referenced entity not found")
			}
		}
		return nil, err
	}

	if err := record(ctx, s.Rec, st.Db, Change{
		By:  rstr.DelegationService_Add_FullMethodName,
		Key: u.Id,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}

	v := u.Proto()
	for _, d := range ds {
		d(v)
	}
	return v, nil
}

func (s DelegationServiceServer) Get(ctx context.Context, req *rstr.DelegationGetRequest) (*rstr.Delegation, error) {
	p, err := DelegationPick(req.GetRef())
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	q := s.Db.Delegation.Query().Where(p)
	DelegationSelectInit(q, req.GetSelect())

	v, err := q.Only(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, status.Error(codes.NotFound, "Delegation not found")
		}
		return nil, err
	}
	return v.Proto(), nil
}

func selectDelegationKey(q *ent.DelegationQuery) {
	q.Select(delegation.FieldId)
}

func DelegationSelectedFields(m *rstr.DelegationSelect) []string {
	if m.GetAll() {
		return delegation.Columns
	}

	vs := make([]string, 0, len(delegation.Columns))
	{
		vs = append(vs, delegation.FieldId)
	}
	if m.GetMethods() {
		vs = append(vs, delegation.FieldMethods)
	}
	if m.GetSecret() {
		vs = append(vs, delegation.FieldSecret)
	}
	if m.GetIssuer() {
		vs = append(vs, delegation.FieldIssuer)
	}
	if m.GetDateExpires() {
		vs = append(vs, delegation.FieldDateExpires)
	}
	if m.GetDateUpdated() {
		vs = append(vs, delegation.FieldDateUpdated)
	}
	if m.GetDateErased() {
		vs = append(vs, delegation.FieldDateErased)
	}
	if m.GetDateCreated() {
		vs = append(vs, delegation.FieldDateCreated)
	}

	return vs
}

func DelegationSelect(q *ent.DelegationQuery, m *rstr.DelegationSelect) {
	if !m.GetAll() {
		fields := DelegationSelectedFields(m)
		q.Select(fields...)
	}
	if m.HasHolder() {
		q.WithHolder(func(q *ent.HolderQuery) {
			q.Where(holder.DateErasedIsNil())
			HolderSelect(q, m.GetHolder())
		})
	}
}

func DelegationSelectInit(q *ent.DelegationQuery, m *rstr.DelegationSelect) {
	if m != nil {
		DelegationSelect(q, m)
	} else {
		q.WithHolder(selectHolderKey)
	}
}

func (s DelegationServiceServer) Patch(ctx context.Context, req *rstr.DelegationPatchRequest) (*rstr.Delegation, error) {
	doc, err := ormpatch.FromPatchRequest(delegationOrmEntity, req.ProtoReflect(), nil)
	if err != nil {
		if _, ok := status.FromError(err); ok {
			return nil, err
		}
		if errors.Is(err, ormpatch.ErrRequestLayout) {
			return nil, status.Errorf(codes.Internal, "%s", err)
		}
		if errors.Is(err, ormpatch.ErrUnsupported) {
			return nil, status.Errorf(codes.Unimplemented, "%s", err)
		}
		return nil, status.Errorf(codes.InvalidArgument, "%s", err)
	}

	return s.apply(ctx, req.GetRef(), doc, rstr.DelegationService_Patch_FullMethodName)
}

func DelegationGetKey(ctx context.Context, db *ent.Client, ref *rstr.DelegationRef) (uuid.UUID, error) {
	var z uuid.UUID
	if ref.HasId() {
		if v, err := entuuid.FromBytes(ref.GetId()); err != nil {
			return z, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return v, nil
		}
	}

	p, err := DelegationPick(ref)
	if err != nil {
		return z, err
	}

	v, err := db.Delegation.Query().Where(p).OnlyId(ctx)
	if err != nil {
		if ent.IsNotFound(err) {
			return z, status.Error(codes.NotFound, "Delegation not found")
		}
		return z, err
	}

	return v, nil
}

var delegationOrmEntity = ormpatch.MustEntityOf(rstr.File_app_delegation_proto, "Delegation")

var delegationPatchColumns = entpatch.Columns{
	1: delegation.FieldId, 2: delegation.HolderColumn, 8: delegation.FieldMethods, 9: delegation.FieldSecret, 10: delegation.FieldIssuer, 11: delegation.FieldDateExpires, 13: delegation.FieldDateUpdated, 14: delegation.FieldDateErased, 15: delegation.FieldDateCreated}

func (s DelegationServiceServer) Apply(ctx context.Context, req *rstr.DelegationApplyRequest) (*rstr.Delegation, error) {
	if !req.HasPatch() {
		return nil, status.Errorf(codes.InvalidArgument, "%s", ormpatch.ErrNoPatch)
	}
	return s.apply(ctx, req.GetRef(), req.GetPatch(), rstr.DelegationService_Apply_FullMethodName)
}

func (s DelegationServiceServer) apply(ctx context.Context, ref *rstr.DelegationRef, doc *patchpb.Patch, by string) (*rstr.Delegation, error) {
	plan := &ormpatch.Plan{Entity: delegationOrmEntity}
	if doc != nil {
		v, err := ormpatch.Compile(delegationOrmEntity, doc)
		if err != nil {
			if errors.Is(err, ormpatch.ErrUnsupported) {
				return nil, status.Errorf(codes.Unimplemented, "%s", err)
			}
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		plan = v
	}

	pred, mod, err := entpatch.Build(plan, delegationPatchColumns, s.Db.Dialect())
	if err != nil {
		if errors.Is(err, entpatch.ErrValue) {
			return nil, status.Errorf(codes.InvalidArgument, "%s", err)
		}
		return nil, status.Errorf(codes.Internal, "%s", err)
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, true)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	k, err := DelegationGetKey(ctx, st.Db, ref)
	if err != nil {
		return nil, err
	}
	at := &rstr.DelegationRef{}
	at.SetId(k[:])
	p, err := s.narrow(ctx, delegation.IdEQ(k))
	if err != nil {
		return nil, err
	}

	if mod == nil {
		q := st.Db.Delegation.Query().Where(p)
		if pred != nil {
			q.Where(predicate.Delegation(pred))
		}
		if ok, err := q.Exist(ctx); err != nil {
			return nil, err
		} else if !ok {
			return nil, func() error {
				if ok, err := st.Db.Delegation.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Delegation not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	} else {
		q := st.Db.Delegation.Update().Where(p)
		if pred != nil {
			q.Where(predicate.Delegation(pred))
		}
		q.Modify(mod)
		if !plan.WritesTo(13) {
			q.SetDateUpdated(st.now())
		}
		if n, err := q.Save(ctx); err != nil {
			if err, ok := err.(*ent.ConstraintError); ok {
				if sqlgraph.IsUniqueConstraintError(err) {
					return nil, status.Error(codes.AlreadyExists, "Delegation already exists")
				}
				if sqlgraph.IsForeignKeyConstraintError(err) {
					return nil, status.Error(codes.NotFound, "Delegation: referenced entity not found")
				}
			}
			return nil, err
		} else if n == 0 {
			return nil, func() error {
				if ok, err := st.Db.Delegation.Query().Where(p).Exist(ctx); err != nil {
					return err
				} else if !ok {
					return status.Error(codes.NotFound, "Delegation not found")
				}
				return status.Error(codes.FailedPrecondition, "a test in the patch did not hold")
			}()
		}
	}

	if mod != nil {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:    by,
			Key:   k,
			Patch: doc,
		}); err != nil {
			return nil, err
		}
	}

	out, err := st.Get(ctx, at.Pick())
	if err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return out, nil
}

func (s DelegationServiceServer) Erase(ctx context.Context, req *rstr.DelegationRef) (*rstr.DelegationEraseResponse, error) {
	p, err := DelegationPick(req)
	if err != nil {
		return nil, err
	}
	p, err = s.narrow(ctx, p)
	if err != nil {
		return nil, err
	}

	tx, err := enttx.Join[*ent.Client, *ent.Tx](ctx, s.Db, s.Rec != nil)
	if err != nil {
		return nil, err
	}
	defer tx.Close()

	st := s
	st.Db = tx.Db

	var k any
	if s.Rec != nil {
		v, err := st.Db.Delegation.Query().Where(p).OnlyId(ctx)
		if err != nil {
			if ent.IsNotFound(err) {
				return &rstr.DelegationEraseResponse{}, nil
			}
			return nil, err
		}

		k = v
		p = delegation.And(p, delegation.IdEQ(v))
	}

	u := st.Db.Delegation.Update().Where(p)
	u.SetDateErased(st.now())
	u.SetDateUpdated(st.now())
	n, err := u.Save(ctx)
	if err != nil {
		return nil, err
	}
	if n > 0 {
		if err := record(ctx, s.Rec, st.Db, Change{
			By:  rstr.DelegationService_Erase_FullMethodName,
			Key: k,
		}); err != nil {
			return nil, err
		}
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	res := &rstr.DelegationEraseResponse{}
	res.SetErased(n > 0)

	return res, nil
}

// DelegationPick answers with the predicate this reference selects on,
// among the rows that are still here.
//
// Erasure is part of the reference and not only part of a read's scope,
// because a reference to a Delegation is composed into the reference of
// whatever names one: an index over an edge asks this for a predicate and
// puts it inside `HasDelegationWith`, where no narrowing of a Delegation
// is ever applied. A child of an erased row would otherwise be readable by
// naming its parent.
func DelegationPick(req *rstr.DelegationRef) (predicate.Delegation, error) {
	p, err := pickDelegation(req)
	if err != nil {
		return nil, err
	}

	return delegation.And(delegation.DateErasedIsNil(), p), nil
}

func pickDelegation(req *rstr.DelegationRef) (predicate.Delegation, error) {
	switch req.WhichKey() {
	case rstr.DelegationRef_Id_case:
		if v, err := entuuid.FromBytes(req.GetId()); err != nil {
			return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
		} else {
			return delegation.IdEQ(v), nil
		}
	case rstr.DelegationRef_Secret_case:
		return delegation.SecretEQ(req.GetSecret()), nil
	case rstr.DelegationRef_Key_not_set_case:
		return nil, status.Errorf(codes.InvalidArgument, "key not set: Delegation")
	default:
		return nil, status.Errorf(codes.Unimplemented, "unknown type of key: %s", req.WhichKey())
	}
}
