// Code generated by ent, DO NOT EDIT.

package binding

import (
	"time"
	"uuid"

	"github.com/lesomnus/roster/internal/ent/predicate"
	"github.com/protobuf-orm/ent/dialect/sql"
	"github.com/protobuf-orm/ent/dialect/sql/sqlgraph"
)

// Id filters vertices based on their Id field.
func Id(id uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.BindingOrErr(sql.FieldEQ(FieldId, vc), err)
}

// IdEQ applies the EQ predicate on the Id field.
func IdEQ(id uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.BindingOrErr(sql.FieldEQ(FieldId, vc), err)
}

// IdNEQ applies the NEQ predicate on the Id field.
func IdNEQ(id uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.BindingOrErr(sql.FieldNEQ(FieldId, vc), err)
}

// IdIn applies the In predicate on the Id field.
func IdIn(ids ...uuid.UUID) predicate.Binding {
	var (
		err error
		vcs = make([]any, len(ids))
	)
	for i := range vcs {
		if vcs[i], err = ValueScanner.Id.Value(ids[i]); err != nil {
			break
		}
	}
	return predicate.BindingOrErr(sql.FieldIn(FieldId, vcs...), err)
}

// IdNotIn applies the NotIn predicate on the Id field.
func IdNotIn(ids ...uuid.UUID) predicate.Binding {
	var (
		err error
		vcs = make([]any, len(ids))
	)
	for i := range vcs {
		if vcs[i], err = ValueScanner.Id.Value(ids[i]); err != nil {
			break
		}
	}
	return predicate.BindingOrErr(sql.FieldNotIn(FieldId, vcs...), err)
}

// IdGT applies the GT predicate on the Id field.
func IdGT(id uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.BindingOrErr(sql.FieldGT(FieldId, vc), err)
}

// IdGTE applies the GTE predicate on the Id field.
func IdGTE(id uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.BindingOrErr(sql.FieldGTE(FieldId, vc), err)
}

// IdLT applies the LT predicate on the Id field.
func IdLT(id uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.BindingOrErr(sql.FieldLT(FieldId, vc), err)
}

// IdLTE applies the LTE predicate on the Id field.
func IdLTE(id uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.Id.Value(id)
	return predicate.BindingOrErr(sql.FieldLTE(FieldId, vc), err)
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldEQ(FieldDateUpdated, v))
}

// DateErased applies equality check predicate on the "date_erased" field. It's identical to DateErasedEQ.
func DateErased(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldEQ(FieldDateErased, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldEQ(FieldDateCreated, v))
}

// RoleId applies equality check predicate on the "role_id" field. It's identical to RoleIdEQ.
func RoleId(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.RoleId.Value(v)
	return predicate.BindingOrErr(sql.FieldEQ(FieldRoleId, vc), err)
}

// SiteId applies equality check predicate on the "site_id" field. It's identical to SiteIdEQ.
func SiteId(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.SiteId.Value(v)
	return predicate.BindingOrErr(sql.FieldEQ(FieldSiteId, vc), err)
}

// HolderId applies equality check predicate on the "holder_id" field. It's identical to HolderIdEQ.
func HolderId(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.HolderId.Value(v)
	return predicate.BindingOrErr(sql.FieldEQ(FieldHolderId, vc), err)
}

// GroupId applies equality check predicate on the "group_id" field. It's identical to GroupIdEQ.
func GroupId(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.GroupId.Value(v)
	return predicate.BindingOrErr(sql.FieldEQ(FieldGroupId, vc), err)
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldLTE(FieldDateUpdated, v))
}

// DateErasedEQ applies the EQ predicate on the "date_erased" field.
func DateErasedEQ(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldEQ(FieldDateErased, v))
}

// DateErasedNEQ applies the NEQ predicate on the "date_erased" field.
func DateErasedNEQ(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldNEQ(FieldDateErased, v))
}

// DateErasedIn applies the In predicate on the "date_erased" field.
func DateErasedIn(vs ...time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldIn(FieldDateErased, vs...))
}

// DateErasedNotIn applies the NotIn predicate on the "date_erased" field.
func DateErasedNotIn(vs ...time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldNotIn(FieldDateErased, vs...))
}

// DateErasedGT applies the GT predicate on the "date_erased" field.
func DateErasedGT(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldGT(FieldDateErased, v))
}

// DateErasedGTE applies the GTE predicate on the "date_erased" field.
func DateErasedGTE(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldGTE(FieldDateErased, v))
}

// DateErasedLT applies the LT predicate on the "date_erased" field.
func DateErasedLT(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldLT(FieldDateErased, v))
}

// DateErasedLTE applies the LTE predicate on the "date_erased" field.
func DateErasedLTE(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldLTE(FieldDateErased, v))
}

// DateErasedIsNil applies the IsNil predicate on the "date_erased" field.
func DateErasedIsNil() predicate.Binding {
	return predicate.Binding(sql.FieldIsNull(FieldDateErased))
}

// DateErasedNotNil applies the NotNil predicate on the "date_erased" field.
func DateErasedNotNil() predicate.Binding {
	return predicate.Binding(sql.FieldNotNull(FieldDateErased))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.Binding {
	return predicate.Binding(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.Binding {
	return predicate.Binding(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.Binding {
	return predicate.Binding(sql.FieldNotNull(FieldDateCreated))
}

// RoleIdEQ applies the EQ predicate on the "role_id" field.
func RoleIdEQ(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.RoleId.Value(v)
	return predicate.BindingOrErr(sql.FieldEQ(FieldRoleId, vc), err)
}

// RoleIdNEQ applies the NEQ predicate on the "role_id" field.
func RoleIdNEQ(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.RoleId.Value(v)
	return predicate.BindingOrErr(sql.FieldNEQ(FieldRoleId, vc), err)
}

// RoleIdIn applies the In predicate on the "role_id" field.
func RoleIdIn(vs ...uuid.UUID) predicate.Binding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.RoleId.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.BindingOrErr(sql.FieldIn(FieldRoleId, v...), err)
}

// RoleIdNotIn applies the NotIn predicate on the "role_id" field.
func RoleIdNotIn(vs ...uuid.UUID) predicate.Binding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.RoleId.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.BindingOrErr(sql.FieldNotIn(FieldRoleId, v...), err)
}

// SiteIdEQ applies the EQ predicate on the "site_id" field.
func SiteIdEQ(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.SiteId.Value(v)
	return predicate.BindingOrErr(sql.FieldEQ(FieldSiteId, vc), err)
}

// SiteIdNEQ applies the NEQ predicate on the "site_id" field.
func SiteIdNEQ(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.SiteId.Value(v)
	return predicate.BindingOrErr(sql.FieldNEQ(FieldSiteId, vc), err)
}

// SiteIdIn applies the In predicate on the "site_id" field.
func SiteIdIn(vs ...uuid.UUID) predicate.Binding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.SiteId.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.BindingOrErr(sql.FieldIn(FieldSiteId, v...), err)
}

// SiteIdNotIn applies the NotIn predicate on the "site_id" field.
func SiteIdNotIn(vs ...uuid.UUID) predicate.Binding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.SiteId.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.BindingOrErr(sql.FieldNotIn(FieldSiteId, v...), err)
}

// SiteIdIsNil applies the IsNil predicate on the "site_id" field.
func SiteIdIsNil() predicate.Binding {
	return predicate.Binding(sql.FieldIsNull(FieldSiteId))
}

// SiteIdNotNil applies the NotNil predicate on the "site_id" field.
func SiteIdNotNil() predicate.Binding {
	return predicate.Binding(sql.FieldNotNull(FieldSiteId))
}

// HolderIdEQ applies the EQ predicate on the "holder_id" field.
func HolderIdEQ(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.HolderId.Value(v)
	return predicate.BindingOrErr(sql.FieldEQ(FieldHolderId, vc), err)
}

// HolderIdNEQ applies the NEQ predicate on the "holder_id" field.
func HolderIdNEQ(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.HolderId.Value(v)
	return predicate.BindingOrErr(sql.FieldNEQ(FieldHolderId, vc), err)
}

// HolderIdIn applies the In predicate on the "holder_id" field.
func HolderIdIn(vs ...uuid.UUID) predicate.Binding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.HolderId.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.BindingOrErr(sql.FieldIn(FieldHolderId, v...), err)
}

// HolderIdNotIn applies the NotIn predicate on the "holder_id" field.
func HolderIdNotIn(vs ...uuid.UUID) predicate.Binding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.HolderId.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.BindingOrErr(sql.FieldNotIn(FieldHolderId, v...), err)
}

// HolderIdIsNil applies the IsNil predicate on the "holder_id" field.
func HolderIdIsNil() predicate.Binding {
	return predicate.Binding(sql.FieldIsNull(FieldHolderId))
}

// HolderIdNotNil applies the NotNil predicate on the "holder_id" field.
func HolderIdNotNil() predicate.Binding {
	return predicate.Binding(sql.FieldNotNull(FieldHolderId))
}

// GroupIdEQ applies the EQ predicate on the "group_id" field.
func GroupIdEQ(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.GroupId.Value(v)
	return predicate.BindingOrErr(sql.FieldEQ(FieldGroupId, vc), err)
}

// GroupIdNEQ applies the NEQ predicate on the "group_id" field.
func GroupIdNEQ(v uuid.UUID) predicate.Binding {
	vc, err := ValueScanner.GroupId.Value(v)
	return predicate.BindingOrErr(sql.FieldNEQ(FieldGroupId, vc), err)
}

// GroupIdIn applies the In predicate on the "group_id" field.
func GroupIdIn(vs ...uuid.UUID) predicate.Binding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.GroupId.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.BindingOrErr(sql.FieldIn(FieldGroupId, v...), err)
}

// GroupIdNotIn applies the NotIn predicate on the "group_id" field.
func GroupIdNotIn(vs ...uuid.UUID) predicate.Binding {
	var (
		err error
		v   = make([]any, len(vs))
	)
	for i := range v {
		if v[i], err = ValueScanner.GroupId.Value(vs[i]); err != nil {
			break
		}
	}
	return predicate.BindingOrErr(sql.FieldNotIn(FieldGroupId, v...), err)
}

// GroupIdIsNil applies the IsNil predicate on the "group_id" field.
func GroupIdIsNil() predicate.Binding {
	return predicate.Binding(sql.FieldIsNull(FieldGroupId))
}

// GroupIdNotNil applies the NotNil predicate on the "group_id" field.
func GroupIdNotNil() predicate.Binding {
	return predicate.Binding(sql.FieldNotNull(FieldGroupId))
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.Binding {
	return predicate.Binding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.Binding {
	return predicate.Binding(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSite applies the HasEdge predicate on the "site" edge.
func HasSite() predicate.Binding {
	return predicate.Binding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, SiteTable, SiteColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSiteWith applies the HasEdge predicate on the "site" edge with a given conditions (other predicates).
func HasSiteWith(preds ...predicate.Site) predicate.Binding {
	return predicate.Binding(func(s *sql.Selector) {
		step := newSiteStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHolder applies the HasEdge predicate on the "holder" edge.
func HasHolder() predicate.Binding {
	return predicate.Binding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, HolderTable, HolderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHolderWith applies the HasEdge predicate on the "holder" edge with a given conditions (other predicates).
func HasHolderWith(preds ...predicate.Holder) predicate.Binding {
	return predicate.Binding(func(s *sql.Selector) {
		step := newHolderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.Binding {
	return predicate.Binding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldId),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.Binding {
	return predicate.Binding(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Binding) predicate.Binding {
	return predicate.Binding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Binding) predicate.Binding {
	return predicate.Binding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Binding) predicate.Binding {
	return predicate.Binding(sql.NotPredicates(p))
}
