// Code generated by ent, DO NOT EDIT.

package teammembership

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/lesomnus/roster/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldID, id))
}

// DateUpdated applies equality check predicate on the "date_updated" field. It's identical to DateUpdatedEQ.
func DateUpdated(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldDateUpdated, v))
}

// DateErased applies equality check predicate on the "date_erased" field. It's identical to DateErasedEQ.
func DateErased(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldDateErased, v))
}

// DateCreated applies equality check predicate on the "date_created" field. It's identical to DateCreatedEQ.
func DateCreated(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldDateCreated, v))
}

// HolderID applies equality check predicate on the "holder_id" field. It's identical to HolderIDEQ.
func HolderID(v uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldHolderID, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldTeamID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldRoleID, v))
}

// DateUpdatedEQ applies the EQ predicate on the "date_updated" field.
func DateUpdatedEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldDateUpdated, v))
}

// DateUpdatedNEQ applies the NEQ predicate on the "date_updated" field.
func DateUpdatedNEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldDateUpdated, v))
}

// DateUpdatedIn applies the In predicate on the "date_updated" field.
func DateUpdatedIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldDateUpdated, vs...))
}

// DateUpdatedNotIn applies the NotIn predicate on the "date_updated" field.
func DateUpdatedNotIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldDateUpdated, vs...))
}

// DateUpdatedGT applies the GT predicate on the "date_updated" field.
func DateUpdatedGT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldDateUpdated, v))
}

// DateUpdatedGTE applies the GTE predicate on the "date_updated" field.
func DateUpdatedGTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldDateUpdated, v))
}

// DateUpdatedLT applies the LT predicate on the "date_updated" field.
func DateUpdatedLT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldDateUpdated, v))
}

// DateUpdatedLTE applies the LTE predicate on the "date_updated" field.
func DateUpdatedLTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldDateUpdated, v))
}

// DateErasedEQ applies the EQ predicate on the "date_erased" field.
func DateErasedEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldDateErased, v))
}

// DateErasedNEQ applies the NEQ predicate on the "date_erased" field.
func DateErasedNEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldDateErased, v))
}

// DateErasedIn applies the In predicate on the "date_erased" field.
func DateErasedIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldDateErased, vs...))
}

// DateErasedNotIn applies the NotIn predicate on the "date_erased" field.
func DateErasedNotIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldDateErased, vs...))
}

// DateErasedGT applies the GT predicate on the "date_erased" field.
func DateErasedGT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldDateErased, v))
}

// DateErasedGTE applies the GTE predicate on the "date_erased" field.
func DateErasedGTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldDateErased, v))
}

// DateErasedLT applies the LT predicate on the "date_erased" field.
func DateErasedLT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldDateErased, v))
}

// DateErasedLTE applies the LTE predicate on the "date_erased" field.
func DateErasedLTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldDateErased, v))
}

// DateErasedIsNil applies the IsNil predicate on the "date_erased" field.
func DateErasedIsNil() predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIsNull(FieldDateErased))
}

// DateErasedNotNil applies the NotNil predicate on the "date_erased" field.
func DateErasedNotNil() predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotNull(FieldDateErased))
}

// DateCreatedEQ applies the EQ predicate on the "date_created" field.
func DateCreatedEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldDateCreated, v))
}

// DateCreatedNEQ applies the NEQ predicate on the "date_created" field.
func DateCreatedNEQ(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldDateCreated, v))
}

// DateCreatedIn applies the In predicate on the "date_created" field.
func DateCreatedIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldDateCreated, vs...))
}

// DateCreatedNotIn applies the NotIn predicate on the "date_created" field.
func DateCreatedNotIn(vs ...time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldDateCreated, vs...))
}

// DateCreatedGT applies the GT predicate on the "date_created" field.
func DateCreatedGT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGT(FieldDateCreated, v))
}

// DateCreatedGTE applies the GTE predicate on the "date_created" field.
func DateCreatedGTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldGTE(FieldDateCreated, v))
}

// DateCreatedLT applies the LT predicate on the "date_created" field.
func DateCreatedLT(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLT(FieldDateCreated, v))
}

// DateCreatedLTE applies the LTE predicate on the "date_created" field.
func DateCreatedLTE(v time.Time) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldLTE(FieldDateCreated, v))
}

// DateCreatedIsNil applies the IsNil predicate on the "date_created" field.
func DateCreatedIsNil() predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIsNull(FieldDateCreated))
}

// DateCreatedNotNil applies the NotNil predicate on the "date_created" field.
func DateCreatedNotNil() predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotNull(FieldDateCreated))
}

// HolderIDEQ applies the EQ predicate on the "holder_id" field.
func HolderIDEQ(v uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldHolderID, v))
}

// HolderIDNEQ applies the NEQ predicate on the "holder_id" field.
func HolderIDNEQ(v uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldHolderID, v))
}

// HolderIDIn applies the In predicate on the "holder_id" field.
func HolderIDIn(vs ...uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldHolderID, vs...))
}

// HolderIDNotIn applies the NotIn predicate on the "holder_id" field.
func HolderIDNotIn(vs ...uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldHolderID, vs...))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldTeamID, vs...))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...uuid.UUID) predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDIsNil applies the IsNil predicate on the "role_id" field.
func RoleIDIsNil() predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldIsNull(FieldRoleID))
}

// RoleIDNotNil applies the NotNil predicate on the "role_id" field.
func RoleIDNotNil() predicate.TeamMembership {
	return predicate.TeamMembership(sql.FieldNotNull(FieldRoleID))
}

// HasHolder applies the HasEdge predicate on the "holder" edge.
func HasHolder() predicate.TeamMembership {
	return predicate.TeamMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, HolderTable, HolderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHolderWith applies the HasEdge predicate on the "holder" edge with a given conditions (other predicates).
func HasHolderWith(preds ...predicate.Holder) predicate.TeamMembership {
	return predicate.TeamMembership(func(s *sql.Selector) {
		step := newHolderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamMembership {
	return predicate.TeamMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamMembership {
	return predicate.TeamMembership(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.TeamMembership {
	return predicate.TeamMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.TeamMembership {
	return predicate.TeamMembership(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamMembership) predicate.TeamMembership {
	return predicate.TeamMembership(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamMembership) predicate.TeamMembership {
	return predicate.TeamMembership(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamMembership) predicate.TeamMembership {
	return predicate.TeamMembership(sql.NotPredicates(p))
}
