-- Written by TestTheScriptIsThisSchema. Do not edit; regenerate.
--
-- One transaction, so the page pays for one commit rather than one per table.
BEGIN;

CREATE TABLE `apikey` (`id` uuid NOT NULL, `alias` text NOT NULL, `desc` text NOT NULL, `methods` json NULL, `secret` blob NOT NULL, `date_used` datetime NULL, `date_expires` datetime NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `apikey_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION);
CREATE TABLE `audit` (`id` uuid NOT NULL, `tenant_id` uuid NOT NULL, `actor_id` uuid NOT NULL, `trace_id` blob NOT NULL, `action` text NOT NULL, `object_id` uuid NOT NULL, `patch` blob NOT NULL, `date_created` datetime NULL, `actor_tenant_id` uuid NOT NULL, `value` blob NOT NULL, `counterpart_tenant_id` uuid NULL, `domain` integer NULL, PRIMARY KEY (`id`));
CREATE TABLE `binding` (`id` uuid NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `role_id` uuid NOT NULL, `site_id` uuid NULL, `holder_id` uuid NULL, `group_id` uuid NULL, PRIMARY KEY (`id`), CONSTRAINT `binding_role_role` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE NO ACTION, CONSTRAINT `binding_site_site` FOREIGN KEY (`site_id`) REFERENCES `site` (`id`) ON DELETE SET NULL, CONSTRAINT `binding_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE SET NULL, CONSTRAINT `binding_group_group` FOREIGN KEY (`group_id`) REFERENCES `group` (`id`) ON DELETE SET NULL);
CREATE TABLE `connection` (`id` uuid NOT NULL, `name` text NOT NULL, `desc` text NOT NULL, `issuer` text NOT NULL, `client_id` text NOT NULL, `scopes` json NULL, `secret_ref` text NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `tenant_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `connection_tenant_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`) ON DELETE NO ACTION);
CREATE TABLE `continuation` (`id` uuid NOT NULL, `satisfied` json NULL, `secret` blob NOT NULL, `issuer` blob NOT NULL, `metered_by` uuid NULL, `date_expires` datetime NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `continuation_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION);
CREATE TABLE `credential` (`id` uuid NOT NULL, `name` text NOT NULL, `kind` text NOT NULL, `secret` blob NOT NULL, `failures` integer NOT NULL, `date_locked` datetime NULL, `date_rotated` datetime NULL, `last_step` integer NOT NULL, `previous` json NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `credential_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION);
CREATE TABLE `delegation` (`id` uuid NOT NULL, `methods` json NULL, `secret` blob NOT NULL, `issuer` blob NOT NULL, `date_expires` datetime NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `delegation_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION);
CREATE TABLE `email` (`id` uuid NOT NULL, `address` text NOT NULL, `date_verified` datetime NULL, `tenant_id` uuid NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, `vouched_by_id` uuid NULL, PRIMARY KEY (`id`), CONSTRAINT `email_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION, CONSTRAINT `email_identity_vouched_by` FOREIGN KEY (`vouched_by_id`) REFERENCES `identity` (`id`) ON DELETE SET NULL);
CREATE TABLE `group` (`id` uuid NOT NULL, `alias` text NOT NULL, `name` text NOT NULL, `desc` text NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `tenant_id` uuid NOT NULL, `site_id` uuid NULL, PRIMARY KEY (`id`), CONSTRAINT `group_tenant_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`) ON DELETE NO ACTION, CONSTRAINT `group_site_site` FOREIGN KEY (`site_id`) REFERENCES `site` (`id`) ON DELETE SET NULL);
CREATE TABLE `groupmembership` (`id` uuid NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, `group_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `groupmembership_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION, CONSTRAINT `groupmembership_group_group` FOREIGN KEY (`group_id`) REFERENCES `group` (`id`) ON DELETE NO ACTION);
CREATE TABLE `holder` (`id` uuid NOT NULL, `alias` text NOT NULL, `name` text NOT NULL, `desc` text NOT NULL, `labels` json NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `idp_subject` text NULL, `profile` json NULL, `data` json NULL, `date_invalidated` datetime NULL, `date_disabled` datetime NULL, `tenant_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `holder_tenant_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`) ON DELETE NO ACTION);
CREATE TABLE `host` (`id` uuid NOT NULL, `name` text NOT NULL, `desc` text NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `tenant_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `host_tenant_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`) ON DELETE NO ACTION);
CREATE TABLE `identity` (`id` uuid NOT NULL, `provider` text NOT NULL, `subject` text NOT NULL, `tenant_id` uuid NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `identity_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION);
CREATE TABLE `link` (`id` uuid NOT NULL, `secret` blob NOT NULL, `issuer` blob NOT NULL, `date_expires` datetime NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, `email_id` uuid NULL, PRIMARY KEY (`id`), CONSTRAINT `link_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION, CONSTRAINT `link_email_email` FOREIGN KEY (`email_id`) REFERENCES `email` (`id`) ON DELETE SET NULL);
CREATE TABLE `maildomain` (`id` uuid NOT NULL, `name` text NOT NULL, `provider` text NOT NULL, `desc` text NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `tenant_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `maildomain_tenant_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`) ON DELETE NO ACTION);
CREATE TABLE `outbox` (`id` uuid NOT NULL, `tenant_id` uuid NOT NULL, `actor_id` uuid NOT NULL, `method` text NOT NULL, `by` text NOT NULL, `object_id` uuid NOT NULL, `patch` blob NOT NULL, `date_created` datetime NULL, PRIMARY KEY (`id`));
CREATE TABLE `role` (`id` uuid NOT NULL, `alias` text NOT NULL, `name` text NOT NULL, `desc` text NOT NULL, `methods` json NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `tenant_id` uuid NOT NULL, `site_id` uuid NULL, PRIMARY KEY (`id`), CONSTRAINT `role_tenant_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`) ON DELETE NO ACTION, CONSTRAINT `role_site_site` FOREIGN KEY (`site_id`) REFERENCES `site` (`id`) ON DELETE SET NULL);
CREATE TABLE `session` (`id` uuid NOT NULL, `grant` blob NOT NULL, `secret` blob NOT NULL, `date_expires` datetime NULL, `date_idle` datetime NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `session_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION);
CREATE TABLE `site` (`id` uuid NOT NULL, `alias` text NOT NULL, `name` text NOT NULL, `desc` text NOT NULL, `labels` json NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `tenant_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `site_tenant_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`) ON DELETE NO ACTION);
CREATE TABLE `sitemembership` (`id` uuid NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, `site_id` uuid NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `sitemembership_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION, CONSTRAINT `sitemembership_site_site` FOREIGN KEY (`site_id`) REFERENCES `site` (`id`) ON DELETE NO ACTION);
CREATE TABLE `team` (`id` uuid NOT NULL, `alias` text NOT NULL, `name` text NOT NULL, `desc` text NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `tenant_id` uuid NOT NULL, `site_id` uuid NULL, PRIMARY KEY (`id`), CONSTRAINT `team_tenant_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`) ON DELETE NO ACTION, CONSTRAINT `team_site_site` FOREIGN KEY (`site_id`) REFERENCES `site` (`id`) ON DELETE SET NULL);
CREATE TABLE `teammembership` (`id` uuid NOT NULL, `date_updated` datetime NOT NULL, `date_erased` datetime NULL, `date_created` datetime NULL, `holder_id` uuid NOT NULL, `team_id` uuid NOT NULL, `role_id` uuid NULL, PRIMARY KEY (`id`), CONSTRAINT `teammembership_holder_holder` FOREIGN KEY (`holder_id`) REFERENCES `holder` (`id`) ON DELETE NO ACTION, CONSTRAINT `teammembership_team_team` FOREIGN KEY (`team_id`) REFERENCES `team` (`id`) ON DELETE NO ACTION, CONSTRAINT `teammembership_role_role` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`) ON DELETE SET NULL);
CREATE TABLE `tenant` (`id` uuid NOT NULL, `alias` text NOT NULL, `name` text NOT NULL, `desc` text NOT NULL, `labels` json NULL, `date_updated` datetime NOT NULL, `date_created` datetime NULL, PRIMARY KEY (`id`));
CREATE UNIQUE INDEX `apikey_alias_holder_id` ON `apikey` (`alias`, `holder_id`) WHERE date_erased IS NULL;
CREATE INDEX `apikey_date_created_id` ON `apikey` (`date_created`, `id`);
CREATE UNIQUE INDEX `apikey_secret` ON `apikey` (`secret`) WHERE date_erased IS NULL;
CREATE INDEX `audit_actor_id_date_created` ON `audit` (`actor_id`, `date_created`);
CREATE INDEX `audit_actor_tenant_id_date_created` ON `audit` (`actor_tenant_id`, `date_created`);
CREATE INDEX `audit_counterpart_tenant_id_date_created` ON `audit` (`counterpart_tenant_id`, `date_created`);
CREATE INDEX `audit_domain_date_created` ON `audit` (`domain`, `date_created`);
CREATE INDEX `audit_object_id` ON `audit` (`object_id`);
CREATE INDEX `audit_tenant_id_date_created` ON `audit` (`tenant_id`, `date_created`);
CREATE INDEX `binding_date_created_id` ON `binding` (`date_created`, `id`);
CREATE INDEX `connection_date_created_id` ON `connection` (`date_created`, `id`);
CREATE UNIQUE INDEX `connection_name_tenant_id` ON `connection` (`name`, `tenant_id`) WHERE date_erased IS NULL;
CREATE INDEX `continuation_date_created_id` ON `continuation` (`date_created`, `id`);
CREATE UNIQUE INDEX `continuation_secret` ON `continuation` (`secret`) WHERE date_erased IS NULL;
CREATE INDEX `credential_date_created_id` ON `credential` (`date_created`, `id`);
CREATE UNIQUE INDEX `credential_kind_name_holder_id` ON `credential` (`kind`, `name`, `holder_id`) WHERE date_erased IS NULL;
CREATE INDEX `delegation_date_created_id` ON `delegation` (`date_created`, `id`);
CREATE UNIQUE INDEX `delegation_secret` ON `delegation` (`secret`) WHERE date_erased IS NULL;
CREATE UNIQUE INDEX `email_address_holder_id` ON `email` (`address`, `holder_id`) WHERE date_erased IS NULL;
CREATE INDEX `email_date_created_id` ON `email` (`date_created`, `id`);
CREATE UNIQUE INDEX `email_tenant_id_address` ON `email` (`tenant_id`, `address`) WHERE date_erased IS NULL;
CREATE UNIQUE INDEX `group_alias_tenant_id` ON `group` (`alias`, `tenant_id`) WHERE date_erased IS NULL;
CREATE INDEX `group_date_created_id` ON `group` (`date_created`, `id`);
CREATE INDEX `groupmembership_date_created_id` ON `groupmembership` (`date_created`, `id`);
CREATE UNIQUE INDEX `groupmembership_holder_id_group_id` ON `groupmembership` (`holder_id`, `group_id`) WHERE date_erased IS NULL;
CREATE UNIQUE INDEX `holder_alias_tenant_id` ON `holder` (`alias`, `tenant_id`) WHERE date_erased IS NULL;
CREATE UNIQUE INDEX `holder_idp_subject` ON `holder` (`idp_subject`) WHERE date_erased IS NULL;
CREATE INDEX `host_date_created_id` ON `host` (`date_created`, `id`);
CREATE UNIQUE INDEX `host_name` ON `host` (`name`) WHERE date_erased IS NULL;
CREATE INDEX `identity_date_created_id` ON `identity` (`date_created`, `id`);
CREATE UNIQUE INDEX `identity_tenant_id_provider_subject` ON `identity` (`tenant_id`, `provider`, `subject`) WHERE date_erased IS NULL;
CREATE INDEX `link_date_created_id` ON `link` (`date_created`, `id`);
CREATE UNIQUE INDEX `link_secret` ON `link` (`secret`) WHERE date_erased IS NULL;
CREATE INDEX `maildomain_date_created_id` ON `maildomain` (`date_created`, `id`);
CREATE UNIQUE INDEX `maildomain_name_tenant_id` ON `maildomain` (`name`, `tenant_id`) WHERE date_erased IS NULL;
CREATE INDEX `outbox_id` ON `outbox` (`id`);
CREATE UNIQUE INDEX `role_alias_tenant_id` ON `role` (`alias`, `tenant_id`) WHERE date_erased IS NULL;
CREATE INDEX `role_date_created_id` ON `role` (`date_created`, `id`);
CREATE INDEX `session_date_created_id` ON `session` (`date_created`, `id`);
CREATE UNIQUE INDEX `session_secret` ON `session` (`secret`) WHERE date_erased IS NULL;
CREATE UNIQUE INDEX `site_alias_tenant_id` ON `site` (`alias`, `tenant_id`) WHERE date_erased IS NULL;
CREATE INDEX `site_date_created_id` ON `site` (`date_created`, `id`);
CREATE INDEX `sitemembership_date_created_id` ON `sitemembership` (`date_created`, `id`);
CREATE UNIQUE INDEX `sitemembership_holder_id_site_id` ON `sitemembership` (`holder_id`, `site_id`) WHERE date_erased IS NULL;
CREATE UNIQUE INDEX `team_alias_site_id` ON `team` (`alias`, `site_id`) WHERE date_erased IS NULL;
CREATE INDEX `team_date_created_id` ON `team` (`date_created`, `id`);
CREATE INDEX `teammembership_date_created_id` ON `teammembership` (`date_created`, `id`);
CREATE UNIQUE INDEX `teammembership_holder_id_team_id` ON `teammembership` (`holder_id`, `team_id`) WHERE date_erased IS NULL;
CREATE UNIQUE INDEX `tenant_alias_key` ON `tenant` (`alias`);

COMMIT;
