// Code generated by protoc-gen-orm-go. DO NOT EDIT.

package rstr

import (
	bytes "bytes"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

func (x *ConnectionRef) Pick() *ConnectionGetRequest {
	return ConnectionGetRequest_builder{Ref: x}.Build()
}

func (x *Connection) Ref() *ConnectionRef {
	if v := x.GetId(); len(v) > 0 {
		return ConnectionById(v)
	}
	{
		v1 := x.GetTenant()
		v2 := x.GetName()
		if v1 != nil && len(v2) > 0 {
			return ConnectionByAt(v1.Ref(), v2)
		}
	}

	return nil
}

func (x *Connection) Pick() *ConnectionGetRequest {
	return x.Ref().Pick()
}

func (x *ConnectionRef) Picks(v *Connection) bool {
	switch x.WhichKey() {
	case ConnectionRef_Id_case:
		return bytes.Equal(x.GetId(), v.GetId())
	case ConnectionRef_At_case:
		x := x.GetAt()
		return (x.GetTenant().Picks(v.GetTenant())) &&
			(x.GetName() == v.GetName())
	default:
		return false
	}
}

func (x *ConnectionGetRequest) WithSelect(f func(s *ConnectionSelect)) *ConnectionGetRequest {
	if !x.HasSelect() {
		x.SetSelect(&ConnectionSelect{})
	}
	f(x.GetSelect())
	return x
}

func (x *Connection) MarshalJSON() ([]byte, error) { return protojson.Marshal(x) }
func (x *Connection) UnmarshalJSON(b []byte) error { return protojson.Unmarshal(b, x) }

func ConnectionById(v []byte) *ConnectionRef {
	x := &ConnectionRef{}
	x.SetId(v)
	return x
}

func ConnectionGetById(v []byte) *ConnectionGetRequest {
	return ConnectionGetRequest_builder{Ref: ConnectionById(v)}.Build()
}

func ConnectionByAt(tenant *TenantRef, name string) *ConnectionRef {
	x := &ConnectionRefByAt{}
	x.SetTenant(tenant)
	x.SetName(name)
	return ConnectionRef_builder{At: x}.Build()
}

func ConnectionGetByAt(tenant *TenantRef, name string) *ConnectionGetRequest {
	return ConnectionGetRequest_builder{Ref: ConnectionByAt(tenant, name)}.Build()
}
