// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/delegation.proto

package rstr

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Delegation is a product app calling roster **as** somebody it just signed in.
//
// PLAN.md D23 is the decision and the gap it closes: nothing in the tree lets
// custody ask roster a question on behalf of one of its users. Every screen
// that shows a person their own record needs it -- my identities, my addresses,
// sign me out everywhere -- and the two obvious ways are both wrong. The app's
// own `rk_` key sees every tenant there is, and the app filtering in its own
// code is the thing D17 already named: *that is the kind of thing that leaks by
// being forgotten*, and on a self-service screen one bug in one app exposes
// everybody's identities while roster answered every read correctly.
//
// So the answer rides back with the yes. `VouchService.Verify` has already
// proved the person to this deployment's satisfaction; this is a credential for
// them, valid for minutes, that the app puts in `authorization` and roster
// resolves to the person -- with their wall, their bindings and their sites.
//
// # Why it is not an ApiKey
//
// It is close enough that the comparison has to be made rather than skipped:
// D23 says outright that *practically it is an `rt_` key with a short life,
// minted for the person an app just authenticated*, and every column below
// except one is `ApiKey`'s.
//
// What separates them is who the row is **for**. An `ApiKey` is a thing a
// person makes and manages: its `alias` is unique per holder and is *what
// somebody calls this key when deciding whether to revoke it*, and the screen
// that lists them is one of the reasons D23 exists at all. A delegation is
// minted once per sign-in by an app the person never sees. One table would make
// that screen a list of rows nobody named, arriving faster than anybody could
// read them, with the two or three the person actually made lost in it.
//
// D16 is the entry that decides this kind of question, and it splits the other
// way here than it did for `Credential`: a delegation and a key are the same
// **cost** and the same **cardinality**, and differ in who names the row.
//
// # The issuer is a column and cannot be an edge
//
// D21 and D23 both require the same condition -- *bound to the caller it was
// issued to*, so that one product app cannot pick up what another was given.
// That caller is a **control-plane** `Holder` or the key hanging off one, and
// this row is in the data plane. D15 put a database boundary between them and
// said there is no query from one to the other, so what is written here is an
// identifier and not a reference. Nothing enforces it but the code that
// compares it, which is what makes it a rule rather than a constraint.
//
// It also cannot be checked where the token is looked up. `auth.TokenStore`
// receives the token and nothing else -- no caller, no peer, no frame -- so a
// comparison written there compiles, runs, and binds nothing.
//
// Which is why this **never travels in `authorization`**. A credential there
// arrives alone, and a delegation is not one: it says who a call is *about*
// while the caller goes on saying who they are. Both are on the request, so the
// comparison has something to compare, and one that leaks is worth nothing
// without the key it was minted for. `keys.Acting` reads the pair.
type Delegation struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Holder      *Holder                `protobuf:"bytes,2,opt,name=holder"`
	xxx_hidden_Methods     []string               `protobuf:"bytes,8,rep,name=methods"`
	xxx_hidden_Secret      []byte                 `protobuf:"bytes,9,opt,name=secret"`
	xxx_hidden_Issuer      []byte                 `protobuf:"bytes,10,opt,name=issuer"`
	xxx_hidden_DateExpires *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=date_expires,json=dateExpires"`
	xxx_hidden_DateUpdated *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Delegation) Reset() {
	*x = Delegation{}
	mi := &file_app_delegation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delegation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delegation) ProtoMessage() {}

func (x *Delegation) ProtoReflect() protoreflect.Message {
	mi := &file_app_delegation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Delegation) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Delegation) GetHolder() *Holder {
	if x != nil {
		return x.xxx_hidden_Holder
	}
	return nil
}

func (x *Delegation) GetMethods() []string {
	if x != nil {
		return x.xxx_hidden_Methods
	}
	return nil
}

func (x *Delegation) GetSecret() []byte {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *Delegation) GetIssuer() []byte {
	if x != nil {
		return x.xxx_hidden_Issuer
	}
	return nil
}

func (x *Delegation) GetDateExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateExpires
	}
	return nil
}

func (x *Delegation) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Delegation) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *Delegation) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Delegation) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Delegation) SetHolder(v *Holder) {
	x.xxx_hidden_Holder = v
}

func (x *Delegation) SetMethods(v []string) {
	x.xxx_hidden_Methods = v
}

func (x *Delegation) SetSecret(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Secret = v
}

func (x *Delegation) SetIssuer(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Issuer = v
}

func (x *Delegation) SetDateExpires(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateExpires = v
}

func (x *Delegation) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Delegation) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *Delegation) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Delegation) HasHolder() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Holder != nil
}

func (x *Delegation) HasDateExpires() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateExpires != nil
}

func (x *Delegation) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Delegation) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *Delegation) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Delegation) ClearHolder() {
	x.xxx_hidden_Holder = nil
}

func (x *Delegation) ClearDateExpires() {
	x.xxx_hidden_DateExpires = nil
}

func (x *Delegation) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Delegation) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *Delegation) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Delegation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id []byte
	// Whose it is: the person the app authenticated, in their own tenant.
	Holder *Holder
	// What this delegation may be used for: the gRPC methods, in full, as
	// `frame.Grant.To` takes them.
	//
	// It is an attenuation and never a widening. The token resolves to the
	// holder, so what it may actually do is the intersection of this with what
	// that person may do -- a method here that they cannot call is still refused.
	//
	// Empty allows **nothing**, which is `frame.Grant`'s zero for actions. A
	// delegation minted with no methods authenticates and is then refused
	// everywhere, which reads as a permissions problem and is a minting one.
	Methods []string
	// The verifier, never the token, and also how the row is found -- the same
	// pair of jobs `ApiKey.secret` does, for the same reasons: 256 bits from
	// `crypto/rand` have no dictionary, so the hash is fast and unsalted, and a
	// per-row salt could not be applied before the row is known.
	//
	// Immutable as well as `secret`, so that it is not in the generated
	// `Patch` at all. A delegation is not rotated; it is reissued.
	Secret []byte
	// Which caller was given this, so that another cannot present it.
	//
	// Opaque bytes: an identifier from the other plane, compared and never
	// resolved. See the note above for why it is not an edge.
	//
	// Empty is not a state this can hold. A zero-length value compares equal to
	// an unresolved caller -- `subtle.ConstantTimeCompare` answers 1 for two
	// empty slices -- so "bound to nobody" and "bound to whoever forgot to say"
	// would be one thing. Whatever mints one refuses an empty issuer instead.
	Issuer []byte
	// When it stops working, and there is no such thing as one that does not.
	//
	// Nullable because the generator has no way to say required -- a singular
	// message field with neither `nullable` nor a default generates a NOT NULL
	// column while the API still answers `HasDateExpires`, which is the thing D6
	// is about and F3 has open. So "always set" is the minting path's rule, and
	// the read refuses an absent one rather than treating it as forever.
	//
	// Enforced on read, never by a sweep. A sweep that is the mechanism is a
	// sweep whose outage is a security incident; what a sweep is for is the rows.
	//
	// Immutable, which leaves the generated `Patch` with nothing to write at all
	// -- and that is the declaration. This row is minted once and erased; a
	// delegation is never extended, because extending one is how a credential
	// that was meant to live for minutes comes to live for a day.
	DateExpires *timestamppb.Timestamp
	DateUpdated *timestamppb.Timestamp
	// Revoking is an erase, and it is what "sign out everywhere" reaches for
	// first. Softly, so that a trail naming this row still finds something.
	DateErased  *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
}

func (b0 Delegation_builder) Build() *Delegation {
	m0 := &Delegation{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Holder = b.Holder
	x.xxx_hidden_Methods = b.Methods
	x.xxx_hidden_Secret = b.Secret
	x.xxx_hidden_Issuer = b.Issuer
	x.xxx_hidden_DateExpires = b.DateExpires
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_app_delegation_proto protoreflect.FileDescriptor

const file_app_delegation_proto_rawDesc = "" +
	"\n" +
	"\x14app/delegation.proto\x12\x06roster\x1a\x1aroster/payday/holder.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\"\xce\x04\n" +
	"\n" +
	"Delegation\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12.\n" +
	"\x06holder\x18\x02 \x01(\v2\x0e.roster.HolderB\x06\xf2\x82\x16\x02@\x01R\x06holder\x12 \n" +
	"\amethods\x18\b \x03(\tB\x06\xea\x82\x16\x02@\x01R\amethods\x12&\n" +
	"\x06secret\x18\t \x01(\fB\x0e\xea\x82\x16\x040\x01@\x01\xaa\xc1\x16\x02\b\x01R\x06secret\x12\x1e\n" +
	"\x06issuer\x18\n" +
	" \x01(\fB\x06\xea\x82\x16\x02@\x01R\x06issuer\x12G\n" +
	"\fdate_expires\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\b\xea\x82\x16\x048\x01@\x01R\vdateExpires\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated:h\xca\xfc\x15&\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x8a\xbb\x16:\b\x132%\n" +
	"\x10\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x06\n" +
	"\x04\n" +
	"\x02id\x1a\x05\n" +
	"\x03ref \x14(d\"\x0f\n" +
	"\rholder.tenantB&Z\x1fgithub.com/lesomnus/roster/rstr\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_delegation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_delegation_proto_goTypes = []any{
	(*Delegation)(nil),            // 0: roster.Delegation
	(*Holder)(nil),                // 1: roster.Holder
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_app_delegation_proto_depIdxs = []int32{
	1, // 0: roster.Delegation.holder:type_name -> roster.Holder
	2, // 1: roster.Delegation.date_expires:type_name -> google.protobuf.Timestamp
	2, // 2: roster.Delegation.date_updated:type_name -> google.protobuf.Timestamp
	2, // 3: roster.Delegation.date_erased:type_name -> google.protobuf.Timestamp
	2, // 4: roster.Delegation.date_created:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_app_delegation_proto_init() }
func file_app_delegation_proto_init() {
	if File_app_delegation_proto != nil {
		return
	}
	file_roster_payday_holder_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_delegation_proto_rawDesc), len(file_app_delegation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_delegation_proto_goTypes,
		DependencyIndexes: file_app_delegation_proto_depIdxs,
		MessageInfos:      file_app_delegation_proto_msgTypes,
	}.Build()
	File_app_delegation_proto = out.File
	file_app_delegation_proto_goTypes = nil
	file_app_delegation_proto_depIdxs = nil
}
