// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/issue.proto

package rstr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssuePasswordRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Alias string                 `protobuf:"bytes,1,opt,name=alias"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IssuePasswordRequest) Reset() {
	*x = IssuePasswordRequest{}
	mi := &file_app_issue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePasswordRequest) ProtoMessage() {}

func (x *IssuePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_issue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IssuePasswordRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *IssuePasswordRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

type IssuePasswordRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whose, by alias within this plane's one tenant.
	Alias string
}

func (b0 IssuePasswordRequest_builder) Build() *IssuePasswordRequest {
	m0 := &IssuePasswordRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Alias = b.Alias
	return m0
}

type IssuePasswordResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Password string                 `protobuf:"bytes,1,opt,name=password"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IssuePasswordResponse) Reset() {
	*x = IssuePasswordResponse{}
	mi := &file_app_issue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePasswordResponse) ProtoMessage() {}

func (x *IssuePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_issue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IssuePasswordResponse) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *IssuePasswordResponse) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

type IssuePasswordResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Shown once and not stored. What is stored is an argon2id hash, so this
	// deployment cannot tell anybody what theirs was any more than it can tell
	// them their key.
	Password string
}

func (b0 IssuePasswordResponse_builder) Build() *IssuePasswordResponse {
	m0 := &IssuePasswordResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Password = b.Password
	return m0
}

var File_app_issue_proto protoreflect.FileDescriptor

const file_app_issue_proto_rawDesc = "" +
	"\n" +
	"\x0fapp/issue.proto\x12\x06roster\",\n" +
	"\x14IssuePasswordRequest\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"3\n" +
	"\x15IssuePasswordResponse\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword2\\\n" +
	"\fIssueService\x12L\n" +
	"\rIssuePassword\x12\x1c.roster.IssuePasswordRequest\x1a\x1d.roster.IssuePasswordResponseB&Z\x1fgithub.com/lesomnus/roster/rstr\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_issue_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_issue_proto_goTypes = []any{
	(*IssuePasswordRequest)(nil),  // 0: roster.IssuePasswordRequest
	(*IssuePasswordResponse)(nil), // 1: roster.IssuePasswordResponse
}
var file_app_issue_proto_depIdxs = []int32{
	0, // 0: roster.IssueService.IssuePassword:input_type -> roster.IssuePasswordRequest
	1, // 1: roster.IssueService.IssuePassword:output_type -> roster.IssuePasswordResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_issue_proto_init() }
func file_app_issue_proto_init() {
	if File_app_issue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_issue_proto_rawDesc), len(file_app_issue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_issue_proto_goTypes,
		DependencyIndexes: file_app_issue_proto_depIdxs,
		MessageInfos:      file_app_issue_proto_msgTypes,
	}.Build()
	File_app_issue_proto = out.File
	file_app_issue_proto_goTypes = nil
	file_app_issue_proto_depIdxs = nil
}
