// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/link.proto

package rstr

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Link is a way in that roster mints and somebody else delivers.
//
// A magic link, and the machine behind a recovery: *a single-use opaque nonce
// roster mints and roster checks, delivered by somebody else.* D19 admits it for
// the reason it admits a password -- **who checks this?** Only roster: it
// resolves nowhere else and revoking it is a delete.
//
// # Sending it is not roster's
//
// D19 puts the delivery outside in as many words, and separating the two is
// what makes the air-gapped case work at all: with no mail, the somebody else
// is a **person**, and what they hand over is a password from `Vouch.Reset`
// rather than a link. Same category, two channels, and roster does not know
// about either.
//
// # It is a first factor, not a way around them
//
// Redeeming one proves the person and nothing more. If they have a second
// factor it is asked for exactly as it would have been after a password, which
// is the whole reason `Vouch.Redeem` answers in `Delegate`'s shape: a link that
// skipped the second factor would be a way to turn one channel into an account.
//
// # Where account takeover lives
//
// So the rules are beside the row rather than in each app that sends one:
// single use, minutes, and bound to the caller it was issued to. The first two
// are what stop a link found in a mailbox six months later; the third is what
// stops one app spending what another was given.
type Link struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Holder      *Holder                `protobuf:"bytes,2,opt,name=holder"`
	xxx_hidden_Email       *Email                 `protobuf:"bytes,12,opt,name=email"`
	xxx_hidden_Secret      []byte                 `protobuf:"bytes,9,opt,name=secret"`
	xxx_hidden_Issuer      []byte                 `protobuf:"bytes,10,opt,name=issuer"`
	xxx_hidden_DateExpires *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=date_expires,json=dateExpires"`
	xxx_hidden_DateUpdated *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_app_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_app_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Link) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Link) GetHolder() *Holder {
	if x != nil {
		return x.xxx_hidden_Holder
	}
	return nil
}

func (x *Link) GetEmail() *Email {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return nil
}

func (x *Link) GetSecret() []byte {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *Link) GetIssuer() []byte {
	if x != nil {
		return x.xxx_hidden_Issuer
	}
	return nil
}

func (x *Link) GetDateExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateExpires
	}
	return nil
}

func (x *Link) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Link) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *Link) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Link) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Link) SetHolder(v *Holder) {
	x.xxx_hidden_Holder = v
}

func (x *Link) SetEmail(v *Email) {
	x.xxx_hidden_Email = v
}

func (x *Link) SetSecret(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Secret = v
}

func (x *Link) SetIssuer(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Issuer = v
}

func (x *Link) SetDateExpires(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateExpires = v
}

func (x *Link) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Link) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *Link) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Link) HasHolder() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Holder != nil
}

func (x *Link) HasEmail() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Email != nil
}

func (x *Link) HasDateExpires() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateExpires != nil
}

func (x *Link) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Link) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *Link) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Link) ClearHolder() {
	x.xxx_hidden_Holder = nil
}

func (x *Link) ClearEmail() {
	x.xxx_hidden_Email = nil
}

func (x *Link) ClearDateExpires() {
	x.xxx_hidden_DateExpires = nil
}

func (x *Link) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Link) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *Link) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Link_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id []byte
	// Who it lets in.
	Holder *Holder
	// The address this link is about, when it is a **verification** and not a
	// way in: `Email.Verify` mints one for a row, `Email.Confirm` spends it and
	// stamps that row's `date_verified`, and mints no delegation -- a link that
	// proves an address is worth strictly less than one that signs somebody in.
	// Unset for the recovery links `Vouch.Link` mints, which are about the
	// person and not an address.
	Email *Email
	// The verifier, never the link -- the shape `ApiKey` argued and every
	// short-lived thing here has repeated: 256 bits from `crypto/rand` have no
	// dictionary, so the hash is fast and unsalted, and it is also how the row is
	// found.
	//
	// **Not argon2**, and that is a decision rather than a copy. D16's third leg
	// says the kind selects the cost, and a code a **person transcribes** would
	// be short and would need the slow hash and a counter. This is not that: a
	// link is machine-made, machine-carried and machine-read. The transcribed
	// case is `Vouch.Reset`, which hands over a password and meters it on the
	// `Credential` row like any other.
	Secret []byte
	// Which caller was given it, so that one app cannot spend what another was
	// issued. Opaque bytes and never an edge; see `delegation.proto`.
	Issuer []byte
	// When it stops working, and there is no such thing as one that does not.
	//
	// Nullable because the generator has no way to say required -- D6, and F3 is
	// open -- so an absent one is refused on read rather than read as forever.
	DateExpires *timestamppb.Timestamp
	DateUpdated *timestamppb.Timestamp
	// Spending it is an erase, which is the whole of what single-use means here
	// -- `Undelegate`'s answer, and one mechanism rather than two.
	DateErased  *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
}

func (b0 Link_builder) Build() *Link {
	m0 := &Link{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Holder = b.Holder
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_Secret = b.Secret
	x.xxx_hidden_Issuer = b.Issuer
	x.xxx_hidden_DateExpires = b.DateExpires
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_app_link_proto protoreflect.FileDescriptor

const file_app_link_proto_rawDesc = "" +
	"\n" +
	"\x0eapp/link.proto\x12\x06roster\x1a\x1aroster/payday/holder.proto\x1a\x0fapp/email.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\"\xd5\x04\n" +
	"\x04Link\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12.\n" +
	"\x06holder\x18\x02 \x01(\v2\x0e.roster.HolderB\x06\xf2\x82\x16\x02@\x01R\x06holder\x12-\n" +
	"\x05email\x18\f \x01(\v2\r.roster.EmailB\b\xf2\x82\x16\x048\x01@\x01R\x05email\x12&\n" +
	"\x06secret\x18\t \x01(\fB\x0e\xea\x82\x16\x040\x01@\x01\xaa\xc1\x16\x02\b\x01R\x06secret\x12\x1e\n" +
	"\x06issuer\x18\n" +
	" \x01(\fB\x06\xea\x82\x16\x02@\x01R\x06issuer\x12G\n" +
	"\fdate_expires\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\b\xea\x82\x16\x048\x01@\x01R\vdateExpires\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated:h\xca\xfc\x15&\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x8a\xbb\x16:\b\x172%\n" +
	"\x10\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x06\n" +
	"\x04\n" +
	"\x02id\x1a\x05\n" +
	"\x03ref \x14(d\"\x0f\n" +
	"\rholder.tenantB&Z\x1fgithub.com/lesomnus/roster/rstr\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_link_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_link_proto_goTypes = []any{
	(*Link)(nil),                  // 0: roster.Link
	(*Holder)(nil),                // 1: roster.Holder
	(*Email)(nil),                 // 2: roster.Email
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_app_link_proto_depIdxs = []int32{
	1, // 0: roster.Link.holder:type_name -> roster.Holder
	2, // 1: roster.Link.email:type_name -> roster.Email
	3, // 2: roster.Link.date_expires:type_name -> google.protobuf.Timestamp
	3, // 3: roster.Link.date_updated:type_name -> google.protobuf.Timestamp
	3, // 4: roster.Link.date_erased:type_name -> google.protobuf.Timestamp
	3, // 5: roster.Link.date_created:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_app_link_proto_init() }
func file_app_link_proto_init() {
	if File_app_link_proto != nil {
		return
	}
	file_roster_payday_holder_proto_init()
	file_app_email_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_link_proto_rawDesc), len(file_app_link_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_link_proto_goTypes,
		DependencyIndexes: file_app_link_proto_depIdxs,
		MessageInfos:      file_app_link_proto_msgTypes,
	}.Build()
	File_app_link_proto = out.File
	file_app_link_proto_goTypes = nil
	file_app_link_proto_depIdxs = nil
}
