// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/membership.proto

package rstr

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SiteMembership is somebody being in a site.
//
// A row rather than an edge on the Holder because it is many-to-many: a person
// works at one factory and audits another, and a support engineer sees several.
// That is why the Holder itself carries no site -- see PLAN.md, D4.
//
// It sits on the second axis itself. A caller narrowed to Seoul reads Seoul's
// memberships and not Frankfurt's, which is what makes "who is here" answerable
// without seeing who is anywhere else.
type SiteMembership struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Holder      *Holder                `protobuf:"bytes,2,opt,name=holder"`
	xxx_hidden_Site        *Site                  `protobuf:"bytes,3,opt,name=site"`
	xxx_hidden_DateUpdated *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SiteMembership) Reset() {
	*x = SiteMembership{}
	mi := &file_app_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteMembership) ProtoMessage() {}

func (x *SiteMembership) ProtoReflect() protoreflect.Message {
	mi := &file_app_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SiteMembership) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *SiteMembership) GetHolder() *Holder {
	if x != nil {
		return x.xxx_hidden_Holder
	}
	return nil
}

func (x *SiteMembership) GetSite() *Site {
	if x != nil {
		return x.xxx_hidden_Site
	}
	return nil
}

func (x *SiteMembership) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *SiteMembership) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *SiteMembership) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *SiteMembership) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *SiteMembership) SetHolder(v *Holder) {
	x.xxx_hidden_Holder = v
}

func (x *SiteMembership) SetSite(v *Site) {
	x.xxx_hidden_Site = v
}

func (x *SiteMembership) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *SiteMembership) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *SiteMembership) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *SiteMembership) HasHolder() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Holder != nil
}

func (x *SiteMembership) HasSite() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Site != nil
}

func (x *SiteMembership) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *SiteMembership) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *SiteMembership) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *SiteMembership) ClearHolder() {
	x.xxx_hidden_Holder = nil
}

func (x *SiteMembership) ClearSite() {
	x.xxx_hidden_Site = nil
}

func (x *SiteMembership) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *SiteMembership) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *SiteMembership) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type SiteMembership_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     []byte
	Holder *Holder
	// Immutable: moving somebody between sites is leaving one and joining
	// another, and the trail should say both happened rather than showing one row
	// that changed its mind.
	Site        *Site
	DateUpdated *timestamppb.Timestamp
	DateErased  *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
}

func (b0 SiteMembership_builder) Build() *SiteMembership {
	m0 := &SiteMembership{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Holder = b.Holder
	x.xxx_hidden_Site = b.Site
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

// TeamMembership is somebody being on a team, which is where a role comes from.
//
// The design derives roles from team membership **within a site**: the same
// person is an operator in Seoul and a reader in Frankfurt, and a role that
// meant one thing everywhere could not say that. A team belongs to a site, so
// this row inherits the distinction rather than repeating it.
type TeamMembership struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Holder      *Holder                `protobuf:"bytes,2,opt,name=holder"`
	xxx_hidden_Team        *Team                  `protobuf:"bytes,8,opt,name=team"`
	xxx_hidden_Role        string                 `protobuf:"bytes,9,opt,name=role"`
	xxx_hidden_DateUpdated *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TeamMembership) Reset() {
	*x = TeamMembership{}
	mi := &file_app_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamMembership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamMembership) ProtoMessage() {}

func (x *TeamMembership) ProtoReflect() protoreflect.Message {
	mi := &file_app_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TeamMembership) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *TeamMembership) GetHolder() *Holder {
	if x != nil {
		return x.xxx_hidden_Holder
	}
	return nil
}

func (x *TeamMembership) GetTeam() *Team {
	if x != nil {
		return x.xxx_hidden_Team
	}
	return nil
}

func (x *TeamMembership) GetRole() string {
	if x != nil {
		return x.xxx_hidden_Role
	}
	return ""
}

func (x *TeamMembership) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *TeamMembership) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *TeamMembership) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *TeamMembership) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *TeamMembership) SetHolder(v *Holder) {
	x.xxx_hidden_Holder = v
}

func (x *TeamMembership) SetTeam(v *Team) {
	x.xxx_hidden_Team = v
}

func (x *TeamMembership) SetRole(v string) {
	x.xxx_hidden_Role = v
}

func (x *TeamMembership) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *TeamMembership) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *TeamMembership) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *TeamMembership) HasHolder() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Holder != nil
}

func (x *TeamMembership) HasTeam() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Team != nil
}

func (x *TeamMembership) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *TeamMembership) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *TeamMembership) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *TeamMembership) ClearHolder() {
	x.xxx_hidden_Holder = nil
}

func (x *TeamMembership) ClearTeam() {
	x.xxx_hidden_Team = nil
}

func (x *TeamMembership) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *TeamMembership) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *TeamMembership) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type TeamMembership_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     []byte
	Holder *Holder
	// 3 is not a Site here, and deliberately: the site is the team's, and saying
	// it twice is two facts that can disagree. What narrows this by site is the
	// team it points at.
	Team *Team
	// What being on it means. A string rather than an enum for the reason
	// `Identity.provider` is one: the set is a deployment's to choose.
	Role        string
	DateUpdated *timestamppb.Timestamp
	DateErased  *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
}

func (b0 TeamMembership_builder) Build() *TeamMembership {
	m0 := &TeamMembership{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Holder = b.Holder
	x.xxx_hidden_Team = b.Team
	x.xxx_hidden_Role = b.Role
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_app_membership_proto protoreflect.FileDescriptor

const file_app_membership_proto_rawDesc = "" +
	"\n" +
	"\x14app/membership.proto\x12\x06roster\x1a\x0eapp/site.proto\x1a\x0eapp/team.proto\x1a\x13payday/holder.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\"\xe8\x03\n" +
	"\x0eSiteMembership\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12.\n" +
	"\x06holder\x18\x02 \x01(\v2\x0e.roster.HolderB\x06\xf2\x82\x16\x02@\x01R\x06holder\x12*\n" +
	"\x04site\x18\x03 \x01(\v2\f.roster.SiteB\b\xf2\x82\x16\x048\x01@\x01R\x04site\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated:\x84\x01\xca\xfc\x15H\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a \x12\x06member\x1a\n" +
	"\n" +
	"\x06holder\x10\x02\x1a\b\n" +
	"\x04site\x10\x030\x01\x8a\xbb\x164\b\v2\x1f\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x04\n" +
	"\x02id\x1a\x03ref \x14(d:\x00\"\r\n" +
	"\vsite.tenant\"\xff\x03\n" +
	"\x0eTeamMembership\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12.\n" +
	"\x06holder\x18\x02 \x01(\v2\x0e.roster.HolderB\x06\xf2\x82\x16\x02@\x01R\x06holder\x12(\n" +
	"\x04team\x18\b \x01(\v2\f.roster.TeamB\x06\xf2\x82\x16\x02@\x01R\x04team\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated:\x89\x01\xca\xfc\x15H\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a \x12\x06member\x1a\n" +
	"\n" +
	"\x06holder\x10\x02\x1a\b\n" +
	"\x04team\x10\b0\x01\x8a\xbb\x169\b\f2\x1f\n" +
	"\x0e\n" +
	"\fdate_created\n" +
	"\x04\n" +
	"\x02id\x1a\x03ref \x14(d:\x00\"\x12\n" +
	"\x10team.site.tenantB&Z\x1fgithub.com/lesomnus/roster/rstr\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_membership_proto_goTypes = []any{
	(*SiteMembership)(nil),        // 0: roster.SiteMembership
	(*TeamMembership)(nil),        // 1: roster.TeamMembership
	(*Holder)(nil),                // 2: roster.Holder
	(*Site)(nil),                  // 3: roster.Site
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*Team)(nil),                  // 5: roster.Team
}
var file_app_membership_proto_depIdxs = []int32{
	2,  // 0: roster.SiteMembership.holder:type_name -> roster.Holder
	3,  // 1: roster.SiteMembership.site:type_name -> roster.Site
	4,  // 2: roster.SiteMembership.date_updated:type_name -> google.protobuf.Timestamp
	4,  // 3: roster.SiteMembership.date_erased:type_name -> google.protobuf.Timestamp
	4,  // 4: roster.SiteMembership.date_created:type_name -> google.protobuf.Timestamp
	2,  // 5: roster.TeamMembership.holder:type_name -> roster.Holder
	5,  // 6: roster.TeamMembership.team:type_name -> roster.Team
	4,  // 7: roster.TeamMembership.date_updated:type_name -> google.protobuf.Timestamp
	4,  // 8: roster.TeamMembership.date_erased:type_name -> google.protobuf.Timestamp
	4,  // 9: roster.TeamMembership.date_created:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_app_membership_proto_init() }
func file_app_membership_proto_init() {
	if File_app_membership_proto != nil {
		return
	}
	file_app_site_proto_init()
	file_app_team_proto_init()
	file_payday_holder_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_membership_proto_rawDesc), len(file_app_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_membership_proto_goTypes,
		DependencyIndexes: file_app_membership_proto_depIdxs,
		MessageInfos:      file_app_membership_proto_msgTypes,
	}.Build()
	File_app_membership_proto = out.File
	file_app_membership_proto_goTypes = nil
	file_app_membership_proto_depIdxs = nil
}
