// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/team.proto

package rstr

import (
	_ "github.com/lesomnus/payday/pdpb"
	_ "github.com/protobuf-orm/protobuf-orm/ormpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Team is a group of people within one site, and what a role is derived from.
//
// The design says roles come from team membership **within a site**: the same
// person can be an operator in Seoul and a reader in Frankfurt, and a role that
// meant the same thing everywhere could not say that.
//
// # This is what field 3 is for
//
// The site is at 3, which payday reserves for a set smaller than a tenant.
// Everything that follows -- a read narrowed to the sites a caller may see, on
// top of the tenants they may see -- is generated from that one number.
//
// A team belongs to exactly **one** site, which is the condition. A Holder does
// not, so a Holder has no site edge; see PLAN.md, D4.
type Team struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant      *Tenant                `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Site        *Site                  `protobuf:"bytes,3,opt,name=site"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_DateUpdated *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateErased  *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date_erased,json=dateErased"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Team) Reset() {
	*x = Team{}
	mi := &file_app_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_app_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Team) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *Team) GetTenant() *Tenant {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *Team) GetSite() *Site {
	if x != nil {
		return x.xxx_hidden_Site
	}
	return nil
}

func (x *Team) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *Team) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Team) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *Team) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *Team) GetDateErased() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateErased
	}
	return nil
}

func (x *Team) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *Team) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *Team) SetTenant(v *Tenant) {
	x.xxx_hidden_Tenant = v
}

func (x *Team) SetSite(v *Site) {
	x.xxx_hidden_Site = v
}

func (x *Team) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *Team) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Team) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *Team) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *Team) SetDateErased(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateErased = v
}

func (x *Team) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *Team) HasTenant() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Tenant != nil
}

func (x *Team) HasSite() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Site != nil
}

func (x *Team) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *Team) HasDateErased() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateErased != nil
}

func (x *Team) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *Team) ClearTenant() {
	x.xxx_hidden_Tenant = nil
}

func (x *Team) ClearSite() {
	x.xxx_hidden_Site = nil
}

func (x *Team) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *Team) ClearDateErased() {
	x.xxx_hidden_DateErased = nil
}

func (x *Team) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type Team_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id []byte
	// Nullable, and not because a team without a site is meaningful. It is the
	// shape payday asks for: a required field-3 edge cannot be added to a schema
	// that already has rows, and this one will. A team in no site is then
	// invisible to a read narrowed to one, which is fail-closed and is the right
	// way round.
	Tenant *Tenant
	// Which site, and **empty is none**, which is what an optional namespace
	// means.
	//
	// It is field 3 and therefore what a narrowed read is narrowed by -- so a
	// team with no site is seen by a read of the whole tenant and not by one
	// scoped to a site. That is the right way round: the alternative is a row
	// that turns up in every scoped read because it belongs to none of them.
	//
	// What it is **not** any more is how this row reaches a tenant. It was, and
	// then a team with no site reached none -- written, invisible to everybody,
	// with nothing saying so. The wall goes through field 2 and field 3 only ever
	// narrows; see PLAN.md, D18.
	Site *Site
	// Unique within the site, so `operators` may exist in every one of them.
	Alias       string
	Name        string
	Desc        string
	DateUpdated *timestamppb.Timestamp
	DateErased  *timestamppb.Timestamp
	DateCreated *timestamppb.Timestamp
}

func (b0 Team_builder) Build() *Team {
	m0 := &Team{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Site = b.Site
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_DateUpdated = b.DateUpdated
	x.xxx_hidden_DateErased = b.DateErased
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

var File_app_team_proto protoreflect.FileDescriptor

const file_app_team_proto_rawDesc = "" +
	"\n" +
	"\x0eapp/team.proto\x12\x06roster\x1a\x1aroster/payday/tenant.proto\x1a\x0eapp/site.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\torm.proto\x1a\fpayday.proto\"\x93\x04\n" +
	"\x04Team\x12\x1b\n" +
	"\x02id\x18\x01 \x01(\fB\v\xea\x82\x16\a\x10@(\x01\x82\x01\x00R\x02id\x12.\n" +
	"\x06tenant\x18\x02 \x01(\v2\x0e.roster.TenantB\x06\xf2\x82\x16\x02@\x01R\x06tenant\x12*\n" +
	"\x04site\x18\x03 \x01(\v2\f.roster.SiteB\b\xf2\x82\x16\x048\x01@\x01R\x04site\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12F\n" +
	"\fdate_updated\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x8a\x01\x00R\vdateUpdated\x12D\n" +
	"\vdate_erased\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampB\a\xea\x82\x16\x03\x92\x01\x00R\n" +
	"dateErased\x12H\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\t\xea\x82\x16\x05@\x01\x82\x01\x00R\vdateCreated:|\xca\xfc\x15E\x12\x02\x10\x01\x1a \x12\x04page\x1a\x10\n" +
	"\fdate_created\x10\x0f\x1a\x06\n" +
	"\x02id\x10\x01\x1a\x1d\x12\x04slug\x1a\t\n" +
	"\x05alias\x10\x04\x1a\b\n" +
	"\x04site\x10\x030\x01\x8a\xbb\x16/\b\n" +
	"2)\n" +
	"\x12\n" +
	"\x10\n" +
	"\fdate_created\x10\x0f\n" +
	"\b\n" +
	"\x06\n" +
	"\x02id\x10\x01\x1a\x05\n" +
	"\x03ref \x14(d:\x00B&Z\x1fgithub.com/lesomnus/roster/rstr\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_team_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_app_team_proto_goTypes = []any{
	(*Team)(nil),                  // 0: roster.Team
	(*Tenant)(nil),                // 1: roster.Tenant
	(*Site)(nil),                  // 2: roster.Site
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_app_team_proto_depIdxs = []int32{
	1, // 0: roster.Team.tenant:type_name -> roster.Tenant
	2, // 1: roster.Team.site:type_name -> roster.Site
	3, // 2: roster.Team.date_updated:type_name -> google.protobuf.Timestamp
	3, // 3: roster.Team.date_erased:type_name -> google.protobuf.Timestamp
	3, // 4: roster.Team.date_created:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_app_team_proto_init() }
func file_app_team_proto_init() {
	if File_app_team_proto != nil {
		return
	}
	file_roster_payday_tenant_proto_init()
	file_app_site_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_team_proto_rawDesc), len(file_app_team_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_team_proto_goTypes,
		DependencyIndexes: file_app_team_proto_depIdxs,
		MessageInfos:      file_app_team_proto_msgTypes,
	}.Build()
	File_app_team_proto = out.File
	file_app_team_proto_goTypes = nil
	file_app_team_proto_depIdxs = nil
}
