// Code generated by protoc-gen-orm-service. DO NOT EDIT.
// source: payday/tenant.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: payday/tenant_svc.g.proto

package rstr

import (
	patchpb "github.com/lesomnus/protobuf-patch/patchpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TenantAddRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Alias       string                 `protobuf:"bytes,4,opt,name=alias"`
	xxx_hidden_Name        string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Desc        string                 `protobuf:"bytes,6,opt,name=desc"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,7,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateCreated *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TenantAddRequest) Reset() {
	*x = TenantAddRequest{}
	mi := &file_payday_tenant_svc_g_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantAddRequest) ProtoMessage() {}

func (x *TenantAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payday_tenant_svc_g_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantAddRequest) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *TenantAddRequest) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *TenantAddRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *TenantAddRequest) GetDesc() string {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return ""
}

func (x *TenantAddRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *TenantAddRequest) GetDateCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return nil
}

func (x *TenantAddRequest) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *TenantAddRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *TenantAddRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *TenantAddRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = v
}

func (x *TenantAddRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *TenantAddRequest) SetDateCreated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateCreated = v
}

func (x *TenantAddRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TenantAddRequest) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateCreated != nil
}

func (x *TenantAddRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *TenantAddRequest) ClearDateCreated() {
	x.xxx_hidden_DateCreated = nil
}

type TenantAddRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          []byte
	Alias       string
	Name        string
	Desc        string
	Labels      map[string]string
	DateCreated *timestamppb.Timestamp
}

func (b0 TenantAddRequest_builder) Build() *TenantAddRequest {
	m0 := &TenantAddRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Desc = b.Desc
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateCreated = b.DateCreated
	return m0
}

type TenantRef struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key isTenantRef_Key        `protobuf_oneof:"key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TenantRef) Reset() {
	*x = TenantRef{}
	mi := &file_payday_tenant_svc_g_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRef) ProtoMessage() {}

func (x *TenantRef) ProtoReflect() protoreflect.Message {
	mi := &file_payday_tenant_svc_g_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantRef) GetId() []byte {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*tenantRef_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *TenantRef) GetAlias() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Key.(*tenantRef_Alias); ok {
			return x.Alias
		}
	}
	return ""
}

func (x *TenantRef) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = &tenantRef_Id{v}
}

func (x *TenantRef) SetAlias(v string) {
	x.xxx_hidden_Key = &tenantRef_Alias{v}
}

func (x *TenantRef) HasKey() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Key != nil
}

func (x *TenantRef) HasId() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*tenantRef_Id)
	return ok
}

func (x *TenantRef) HasAlias() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Key.(*tenantRef_Alias)
	return ok
}

func (x *TenantRef) ClearKey() {
	x.xxx_hidden_Key = nil
}

func (x *TenantRef) ClearId() {
	if _, ok := x.xxx_hidden_Key.(*tenantRef_Id); ok {
		x.xxx_hidden_Key = nil
	}
}

func (x *TenantRef) ClearAlias() {
	if _, ok := x.xxx_hidden_Key.(*tenantRef_Alias); ok {
		x.xxx_hidden_Key = nil
	}
}

const TenantRef_Key_not_set_case case_TenantRef_Key = 0
const TenantRef_Id_case case_TenantRef_Key = 1
const TenantRef_Alias_case case_TenantRef_Key = 4

func (x *TenantRef) WhichKey() case_TenantRef_Key {
	if x == nil {
		return TenantRef_Key_not_set_case
	}
	switch x.xxx_hidden_Key.(type) {
	case *tenantRef_Id:
		return TenantRef_Id_case
	case *tenantRef_Alias:
		return TenantRef_Alias_case
	default:
		return TenantRef_Key_not_set_case
	}
}

type TenantRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Key:
	Id    []byte
	Alias *string
	// -- end of xxx_hidden_Key
}

func (b0 TenantRef_builder) Build() *TenantRef {
	m0 := &TenantRef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		x.xxx_hidden_Key = &tenantRef_Id{b.Id}
	}
	if b.Alias != nil {
		x.xxx_hidden_Key = &tenantRef_Alias{*b.Alias}
	}
	return m0
}

type case_TenantRef_Key protoreflect.FieldNumber

func (x case_TenantRef_Key) String() string {
	md := file_payday_tenant_svc_g_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isTenantRef_Key interface {
	isTenantRef_Key()
}

type tenantRef_Id struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,oneof"`
}

type tenantRef_Alias struct {
	Alias string `protobuf:"bytes,4,opt,name=alias,oneof"`
}

func (*tenantRef_Id) isTenantRef_Key() {}

func (*tenantRef_Alias) isTenantRef_Key() {}

type TenantSelect struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_All         bool                   `protobuf:"varint,1,opt,name=all"`
	xxx_hidden_Alias       bool                   `protobuf:"varint,4,opt,name=alias"`
	xxx_hidden_Name        bool                   `protobuf:"varint,5,opt,name=name"`
	xxx_hidden_Desc        bool                   `protobuf:"varint,6,opt,name=desc"`
	xxx_hidden_Labels      bool                   `protobuf:"varint,7,opt,name=labels"`
	xxx_hidden_DateUpdated bool                   `protobuf:"varint,13,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateCreated bool                   `protobuf:"varint,15,opt,name=date_created,json=dateCreated"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TenantSelect) Reset() {
	*x = TenantSelect{}
	mi := &file_payday_tenant_svc_g_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSelect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSelect) ProtoMessage() {}

func (x *TenantSelect) ProtoReflect() protoreflect.Message {
	mi := &file_payday_tenant_svc_g_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantSelect) GetAll() bool {
	if x != nil {
		return x.xxx_hidden_All
	}
	return false
}

func (x *TenantSelect) GetAlias() bool {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return false
}

func (x *TenantSelect) GetName() bool {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return false
}

func (x *TenantSelect) GetDesc() bool {
	if x != nil {
		return x.xxx_hidden_Desc
	}
	return false
}

func (x *TenantSelect) GetLabels() bool {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return false
}

func (x *TenantSelect) GetDateUpdated() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return false
}

func (x *TenantSelect) GetDateCreated() bool {
	if x != nil {
		return x.xxx_hidden_DateCreated
	}
	return false
}

func (x *TenantSelect) SetAll(v bool) {
	x.xxx_hidden_All = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *TenantSelect) SetAlias(v bool) {
	x.xxx_hidden_Alias = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *TenantSelect) SetName(v bool) {
	x.xxx_hidden_Name = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *TenantSelect) SetDesc(v bool) {
	x.xxx_hidden_Desc = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *TenantSelect) SetLabels(v bool) {
	x.xxx_hidden_Labels = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *TenantSelect) SetDateUpdated(v bool) {
	x.xxx_hidden_DateUpdated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *TenantSelect) SetDateCreated(v bool) {
	x.xxx_hidden_DateCreated = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *TenantSelect) HasAll() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TenantSelect) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TenantSelect) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TenantSelect) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TenantSelect) HasLabels() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TenantSelect) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *TenantSelect) HasDateCreated() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *TenantSelect) ClearAll() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_All = false
}

func (x *TenantSelect) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = false
}

func (x *TenantSelect) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = false
}

func (x *TenantSelect) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = false
}

func (x *TenantSelect) ClearLabels() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Labels = false
}

func (x *TenantSelect) ClearDateUpdated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_DateUpdated = false
}

func (x *TenantSelect) ClearDateCreated() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateCreated = false
}

type TenantSelect_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	All         *bool
	Alias       *bool
	Name        *bool
	Desc        *bool
	Labels      *bool
	DateUpdated *bool
	DateCreated *bool
}

func (b0 TenantSelect_builder) Build() *TenantSelect {
	m0 := &TenantSelect{}
	b, x := &b0, m0
	_, _ = b, x
	if b.All != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_All = *b.All
	}
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Alias = *b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Name = *b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Desc = *b.Desc
	}
	if b.Labels != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Labels = *b.Labels
	}
	if b.DateUpdated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_DateUpdated = *b.DateUpdated
	}
	if b.DateCreated != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_DateCreated = *b.DateCreated
	}
	return m0
}

type TenantGetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref    *TenantRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Select *TenantSelect          `protobuf:"bytes,2,opt,name=select"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TenantGetRequest) Reset() {
	*x = TenantGetRequest{}
	mi := &file_payday_tenant_svc_g_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantGetRequest) ProtoMessage() {}

func (x *TenantGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payday_tenant_svc_g_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantGetRequest) GetRef() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *TenantGetRequest) GetSelect() *TenantSelect {
	if x != nil {
		return x.xxx_hidden_Select
	}
	return nil
}

func (x *TenantGetRequest) SetRef(v *TenantRef) {
	x.xxx_hidden_Ref = v
}

func (x *TenantGetRequest) SetSelect(v *TenantSelect) {
	x.xxx_hidden_Select = v
}

func (x *TenantGetRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *TenantGetRequest) HasSelect() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Select != nil
}

func (x *TenantGetRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *TenantGetRequest) ClearSelect() {
	x.xxx_hidden_Select = nil
}

type TenantGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *TenantRef
	Select *TenantSelect
}

func (b0 TenantGetRequest_builder) Build() *TenantGetRequest {
	m0 := &TenantGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Select = b.Select
	return m0
}

type TenantPatchRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref              *TenantRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Alias            *string                `protobuf:"bytes,8,opt,name=alias"`
	xxx_hidden_Name             *string                `protobuf:"bytes,10,opt,name=name"`
	xxx_hidden_Desc             *string                `protobuf:"bytes,12,opt,name=desc"`
	xxx_hidden_Labels           map[string]string      `protobuf:"bytes,14,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_DateUpdated      *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=date_updated,json=dateUpdated"`
	xxx_hidden_DateUpdatedForce bool                   `protobuf:"varint,27,opt,name=date_updated_force,json=dateUpdatedForce"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *TenantPatchRequest) Reset() {
	*x = TenantPatchRequest{}
	mi := &file_payday_tenant_svc_g_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantPatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantPatchRequest) ProtoMessage() {}

func (x *TenantPatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payday_tenant_svc_g_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantPatchRequest) GetRef() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *TenantPatchRequest) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *TenantPatchRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *TenantPatchRequest) GetDesc() string {
	if x != nil {
		if x.xxx_hidden_Desc != nil {
			return *x.xxx_hidden_Desc
		}
		return ""
	}
	return ""
}

func (x *TenantPatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *TenantPatchRequest) GetDateUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DateUpdated
	}
	return nil
}

func (x *TenantPatchRequest) GetDateUpdatedForce() bool {
	if x != nil {
		return x.xxx_hidden_DateUpdatedForce
	}
	return false
}

func (x *TenantPatchRequest) SetRef(v *TenantRef) {
	x.xxx_hidden_Ref = v
}

func (x *TenantPatchRequest) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *TenantPatchRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *TenantPatchRequest) SetDesc(v string) {
	x.xxx_hidden_Desc = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *TenantPatchRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *TenantPatchRequest) SetDateUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_DateUpdated = v
}

func (x *TenantPatchRequest) SetDateUpdatedForce(v bool) {
	x.xxx_hidden_DateUpdatedForce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *TenantPatchRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *TenantPatchRequest) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TenantPatchRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TenantPatchRequest) HasDesc() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TenantPatchRequest) HasDateUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DateUpdated != nil
}

func (x *TenantPatchRequest) HasDateUpdatedForce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *TenantPatchRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *TenantPatchRequest) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *TenantPatchRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Name = nil
}

func (x *TenantPatchRequest) ClearDesc() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Desc = nil
}

func (x *TenantPatchRequest) ClearDateUpdated() {
	x.xxx_hidden_DateUpdated = nil
}

func (x *TenantPatchRequest) ClearDateUpdatedForce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DateUpdatedForce = false
}

type TenantPatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref    *TenantRef
	Alias  *string
	Name   *string
	Desc   *string
	Labels map[string]string
	// The version this update requires the stored date_updated to be.
	// It is a precondition, not a write: the update applies only if the row
	// still holds this value, and the server stamps the new version itself.
	// Setting it together with date_updated_force is an error --
	// the version is the token every client's compare-and-swap is measured
	// against, so it is not the caller's to choose.
	DateUpdated *timestamppb.Timestamp
	// Update whatever the stored date_updated is, with no precondition.
	// The server still stamps a new version, so other clients' tokens are
	// invalidated as usual; this declines the check for THIS update only.
	// One of date_updated or this must be set. An omitted version is
	// refused rather than assumed, because an unset field cannot be told
	// apart from a caller who never considered locking at all.
	DateUpdatedForce *bool
}

func (b0 TenantPatchRequest_builder) Build() *TenantPatchRequest {
	m0 := &TenantPatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Alias = b.Alias
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Name = b.Name
	}
	if b.Desc != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Desc = b.Desc
	}
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_DateUpdated = b.DateUpdated
	if b.DateUpdatedForce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_DateUpdatedForce = *b.DateUpdatedForce
	}
	return m0
}

type TenantApplyRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ref   *TenantRef             `protobuf:"bytes,1,opt,name=ref"`
	xxx_hidden_Patch *patchpb.Patch         `protobuf:"bytes,2,opt,name=patch"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TenantApplyRequest) Reset() {
	*x = TenantApplyRequest{}
	mi := &file_payday_tenant_svc_g_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantApplyRequest) ProtoMessage() {}

func (x *TenantApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payday_tenant_svc_g_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TenantApplyRequest) GetRef() *TenantRef {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return nil
}

func (x *TenantApplyRequest) GetPatch() *patchpb.Patch {
	if x != nil {
		return x.xxx_hidden_Patch
	}
	return nil
}

func (x *TenantApplyRequest) SetRef(v *TenantRef) {
	x.xxx_hidden_Ref = v
}

func (x *TenantApplyRequest) SetPatch(v *patchpb.Patch) {
	x.xxx_hidden_Patch = v
}

func (x *TenantApplyRequest) HasRef() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ref != nil
}

func (x *TenantApplyRequest) HasPatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Patch != nil
}

func (x *TenantApplyRequest) ClearRef() {
	x.xxx_hidden_Ref = nil
}

func (x *TenantApplyRequest) ClearPatch() {
	x.xxx_hidden_Patch = nil
}

type TenantApplyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ref   *TenantRef
	Patch *patchpb.Patch
}

func (b0 TenantApplyRequest_builder) Build() *TenantApplyRequest {
	m0 := &TenantApplyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ref = b.Ref
	x.xxx_hidden_Patch = b.Patch
	return m0
}

var File_payday_tenant_svc_g_proto protoreflect.FileDescriptor

const file_payday_tenant_svc_g_proto_rawDesc = "" +
	"\n" +
	"\x19payday/tenant_svc.g.proto\x12\x03app\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11patch/patch.proto\x1a\x13payday/tenant.proto\"\xaa\x02\n" +
	"\x10TenantAddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1b\n" +
	"\x05alias\x18\x04 \x01(\tB\x05\xaa\x01\x02\b\x02R\x05alias\x12\x19\n" +
	"\x04name\x18\x05 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12\x19\n" +
	"\x04desc\x18\x06 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04desc\x129\n" +
	"\x06labels\x18\a \x03(\v2!.app.TenantAddRequest.LabelsEntryR\x06labels\x12=\n" +
	"\fdate_created\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vdateCreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\tTenantRef\x12\x10\n" +
	"\x02id\x18\x01 \x01(\fH\x00R\x02id\x12\x16\n" +
	"\x05alias\x18\x04 \x01(\tH\x00R\x05aliasB\x05\n" +
	"\x03key\"\xbc\x01\n" +
	"\fTenantSelect\x12\x10\n" +
	"\x03all\x18\x01 \x01(\bR\x03all\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\bR\x05alias\x12\x12\n" +
	"\x04name\x18\x05 \x01(\bR\x04name\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\bR\x04desc\x12\x16\n" +
	"\x06labels\x18\a \x01(\bR\x06labels\x12!\n" +
	"\fdate_updated\x18\r \x01(\bR\vdateUpdated\x12!\n" +
	"\fdate_created\x18\x0f \x01(\bR\vdateCreated\"_\n" +
	"\x10TenantGetRequest\x12 \n" +
	"\x03ref\x18\x01 \x01(\v2\x0e.app.TenantRefR\x03ref\x12)\n" +
	"\x06select\x18\x02 \x01(\v2\x11.app.TenantSelectR\x06select\"\xd9\x02\n" +
	"\x12TenantPatchRequest\x12 \n" +
	"\x03ref\x18\x01 \x01(\v2\x0e.app.TenantRefR\x03ref\x12\x14\n" +
	"\x05alias\x18\b \x01(\tR\x05alias\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\f \x01(\tR\x04desc\x12;\n" +
	"\x06labels\x18\x0e \x03(\v2#.app.TenantPatchRequest.LabelsEntryR\x06labels\x12=\n" +
	"\fdate_updated\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\vdateUpdated\x12,\n" +
	"\x12date_updated_force\x18\x1b \x01(\bR\x10dateUpdatedForce\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x12TenantApplyRequest\x12 \n" +
	"\x03ref\x18\x01 \x01(\v2\x0e.app.TenantRefR\x03ref\x12\"\n" +
	"\x05patch\x18\x02 \x01(\v2\f.patch.PatchR\x05patch2\xf4\x01\n" +
	"\rTenantService\x12)\n" +
	"\x03Add\x12\x15.app.TenantAddRequest\x1a\v.app.Tenant\x12)\n" +
	"\x03Get\x12\x15.app.TenantGetRequest\x1a\v.app.Tenant\x12-\n" +
	"\x05Patch\x12\x17.app.TenantPatchRequest\x1a\v.app.Tenant\x12-\n" +
	"\x05Apply\x12\x17.app.TenantApplyRequest\x1a\v.app.Tenant\x12/\n" +
	"\x05Erase\x12\x0e.app.TenantRef\x1a\x16.google.protobuf.EmptyB!Z\x1fgithub.com/lesomnus/roster/rstrb\beditionsp\xe8\a"

var file_payday_tenant_svc_g_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payday_tenant_svc_g_proto_goTypes = []any{
	(*TenantAddRequest)(nil),      // 0: app.TenantAddRequest
	(*TenantRef)(nil),             // 1: app.TenantRef
	(*TenantSelect)(nil),          // 2: app.TenantSelect
	(*TenantGetRequest)(nil),      // 3: app.TenantGetRequest
	(*TenantPatchRequest)(nil),    // 4: app.TenantPatchRequest
	(*TenantApplyRequest)(nil),    // 5: app.TenantApplyRequest
	nil,                           // 6: app.TenantAddRequest.LabelsEntry
	nil,                           // 7: app.TenantPatchRequest.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*patchpb.Patch)(nil),         // 9: patch.Patch
	(*Tenant)(nil),                // 10: app.Tenant
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_payday_tenant_svc_g_proto_depIdxs = []int32{
	6,  // 0: app.TenantAddRequest.labels:type_name -> app.TenantAddRequest.LabelsEntry
	8,  // 1: app.TenantAddRequest.date_created:type_name -> google.protobuf.Timestamp
	1,  // 2: app.TenantGetRequest.ref:type_name -> app.TenantRef
	2,  // 3: app.TenantGetRequest.select:type_name -> app.TenantSelect
	1,  // 4: app.TenantPatchRequest.ref:type_name -> app.TenantRef
	7,  // 5: app.TenantPatchRequest.labels:type_name -> app.TenantPatchRequest.LabelsEntry
	8,  // 6: app.TenantPatchRequest.date_updated:type_name -> google.protobuf.Timestamp
	1,  // 7: app.TenantApplyRequest.ref:type_name -> app.TenantRef
	9,  // 8: app.TenantApplyRequest.patch:type_name -> patch.Patch
	0,  // 9: app.TenantService.Add:input_type -> app.TenantAddRequest
	3,  // 10: app.TenantService.Get:input_type -> app.TenantGetRequest
	4,  // 11: app.TenantService.Patch:input_type -> app.TenantPatchRequest
	5,  // 12: app.TenantService.Apply:input_type -> app.TenantApplyRequest
	1,  // 13: app.TenantService.Erase:input_type -> app.TenantRef
	10, // 14: app.TenantService.Add:output_type -> app.Tenant
	10, // 15: app.TenantService.Get:output_type -> app.Tenant
	10, // 16: app.TenantService.Patch:output_type -> app.Tenant
	10, // 17: app.TenantService.Apply:output_type -> app.Tenant
	11, // 18: app.TenantService.Erase:output_type -> google.protobuf.Empty
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_payday_tenant_svc_g_proto_init() }
func file_payday_tenant_svc_g_proto_init() {
	if File_payday_tenant_svc_g_proto != nil {
		return
	}
	file_payday_tenant_proto_init()
	file_payday_tenant_svc_g_proto_msgTypes[1].OneofWrappers = []any{
		(*tenantRef_Id)(nil),
		(*tenantRef_Alias)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payday_tenant_svc_g_proto_rawDesc), len(file_payday_tenant_svc_g_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payday_tenant_svc_g_proto_goTypes,
		DependencyIndexes: file_payday_tenant_svc_g_proto_depIdxs,
		MessageInfos:      file_payday_tenant_svc_g_proto_msgTypes,
	}.Build()
	File_payday_tenant_svc_g_proto = out.File
	file_payday_tenant_svc_g_proto_goTypes = nil
	file_payday_tenant_svc_g_proto_depIdxs = nil
}
