// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: app/vouch.proto

package rstr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VouchWho names somebody in the words a sign-in form collects.
//
// It is this file's own shape rather than the generated `HolderRef`, for the
// same reason custody's catalogue defines its own item: what a hand-written
// service takes is its own vocabulary, and `HolderRef` is roster's internal
// one. It is also the only thing that compiles -- the refs are generated from
// the entities in a later step than this file, so a service written by hand
// cannot name one.
//
// Exactly one of these ways is expected. More than one is a caller that has not
// decided, and it is refused rather than resolved in some order this comment
// would then have to define.
type VouchWho struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id      []byte                 `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Tenant  string                 `protobuf:"bytes,2,opt,name=tenant"`
	xxx_hidden_Alias   string                 `protobuf:"bytes,3,opt,name=alias"`
	xxx_hidden_Address string                 `protobuf:"bytes,4,opt,name=address"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VouchWho) Reset() {
	*x = VouchWho{}
	mi := &file_app_vouch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchWho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchWho) ProtoMessage() {}

func (x *VouchWho) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchWho) GetId() []byte {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return nil
}

func (x *VouchWho) GetTenant() string {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return ""
}

func (x *VouchWho) GetAlias() string {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return ""
}

func (x *VouchWho) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *VouchWho) SetId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Id = v
}

func (x *VouchWho) SetTenant(v string) {
	x.xxx_hidden_Tenant = v
}

func (x *VouchWho) SetAlias(v string) {
	x.xxx_hidden_Alias = v
}

func (x *VouchWho) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

type VouchWho_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The identifier, when the caller already has it.
	Id []byte
	// `@tenant/alias`, which is the pair a username field and a tenant selector
	// make -- or the tenant and an [VouchWho.address], which is what a form that
	// asks for an email collects.
	//
	// The tenant is required by either, and comes from the front door rather than
	// from the form: `FrontService.WhoseHost` turns the name a browser arrived at
	// into one.
	Tenant string
	Alias  string
	// An address, within a tenant. What most sign-in forms actually collect.
	//
	// # This used to be empty, and F7 is why
	//
	// `Email` is unique **per holder**, deliberately, so that a consultant can be
	// one person in two tenants under one address -- which meant one address
	// could name two people and a sign-in resolving by it would pick one of them.
	// The comment here said so and left the field unspent.
	//
	// The way out was never a field. It was the second half of the same
	// sentence: *or a tenant that arrives from somewhere the form did not type.*
	// A front door has one now, from `FrontService.WhoseHost`, and `Email` has a
	// unique `(tenant, address)` to go with it -- so within the tenant somebody
	// arrived at, an address names one person again. D3's consultant is
	// untouched: that case is across tenants and this constrains within one.
	//
	// # It is the tenant **and** the address, always
	//
	// Named beside [VouchWho.tenant], which is the same pair an alias uses. There
	// is no form of this that takes an address alone, and that is the constraint
	// rather than an omission: a lookup that could be made without naming a
	// tenant is a lookup a front door that forgot to think about which one
	// compiles a wrong answer for.
	Address string
}

func (b0 VouchWho_builder) Build() *VouchWho {
	m0 := &VouchWho{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_Alias = b.Alias
	x.xxx_hidden_Address = b.Address
	return m0
}

type VouchVerifyRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Who    *VouchWho              `protobuf:"bytes,1,opt,name=who"`
	xxx_hidden_Kind   string                 `protobuf:"bytes,8,opt,name=kind"`
	xxx_hidden_Secret []byte                 `protobuf:"bytes,9,opt,name=secret"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VouchVerifyRequest) Reset() {
	*x = VouchVerifyRequest{}
	mi := &file_app_vouch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchVerifyRequest) ProtoMessage() {}

func (x *VouchVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchVerifyRequest) GetWho() *VouchWho {
	if x != nil {
		return x.xxx_hidden_Who
	}
	return nil
}

func (x *VouchVerifyRequest) GetKind() string {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return ""
}

func (x *VouchVerifyRequest) GetSecret() []byte {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *VouchVerifyRequest) SetWho(v *VouchWho) {
	x.xxx_hidden_Who = v
}

func (x *VouchVerifyRequest) SetKind(v string) {
	x.xxx_hidden_Kind = v
}

func (x *VouchVerifyRequest) SetSecret(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Secret = v
}

func (x *VouchVerifyRequest) HasWho() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Who != nil
}

func (x *VouchVerifyRequest) ClearWho() {
	x.xxx_hidden_Who = nil
}

type VouchVerifyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Who *VouchWho
	// Which secret -- "password", "totp". Empty means "password", since that is
	// the one every deployment has.
	Kind string
	// The secret itself, as typed. Not a hash: hashing is this service's, because
	// parameters chosen by a caller are parameters this store cannot vouch for.
	Secret []byte
}

func (b0 VouchVerifyRequest_builder) Build() *VouchVerifyRequest {
	m0 := &VouchVerifyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Who = b.Who
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type VouchVerifyResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ok          bool                   `protobuf:"varint,1,opt,name=ok"`
	xxx_hidden_Holder      []byte                 `protobuf:"bytes,2,opt,name=holder"`
	xxx_hidden_Tenant      []byte                 `protobuf:"bytes,3,opt,name=tenant"`
	xxx_hidden_LockedUntil *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=locked_until,json=lockedUntil"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VouchVerifyResponse) Reset() {
	*x = VouchVerifyResponse{}
	mi := &file_app_vouch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchVerifyResponse) ProtoMessage() {}

func (x *VouchVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchVerifyResponse) GetOk() bool {
	if x != nil {
		return x.xxx_hidden_Ok
	}
	return false
}

func (x *VouchVerifyResponse) GetHolder() []byte {
	if x != nil {
		return x.xxx_hidden_Holder
	}
	return nil
}

func (x *VouchVerifyResponse) GetTenant() []byte {
	if x != nil {
		return x.xxx_hidden_Tenant
	}
	return nil
}

func (x *VouchVerifyResponse) GetLockedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LockedUntil
	}
	return nil
}

func (x *VouchVerifyResponse) SetOk(v bool) {
	x.xxx_hidden_Ok = v
}

func (x *VouchVerifyResponse) SetHolder(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Holder = v
}

func (x *VouchVerifyResponse) SetTenant(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Tenant = v
}

func (x *VouchVerifyResponse) SetLockedUntil(v *timestamppb.Timestamp) {
	x.xxx_hidden_LockedUntil = v
}

func (x *VouchVerifyResponse) HasLockedUntil() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LockedUntil != nil
}

func (x *VouchVerifyResponse) ClearLockedUntil() {
	x.xxx_hidden_LockedUntil = nil
}

type VouchVerifyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ok bool
	// Who it was, set only when `ok`. This is what the Login App puts in the
	// subject of whatever it goes on to issue.
	Holder []byte
	Tenant []byte
	// When they may try again, set only when too many failures have closed the
	// account for a while.
	//
	// It is distinguishable from an ordinary refusal, and that is a deliberate
	// trade rather than an oversight: it tells a caller that this person exists,
	// which every other refusal here is careful not to. The alternative is a
	// product where somebody locked out is told nothing and tries forever, and
	// being locked out is already something they can discover by succeeding.
	LockedUntil *timestamppb.Timestamp
}

func (b0 VouchVerifyResponse_builder) Build() *VouchVerifyResponse {
	m0 := &VouchVerifyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Ok = b.Ok
	x.xxx_hidden_Holder = b.Holder
	x.xxx_hidden_Tenant = b.Tenant
	x.xxx_hidden_LockedUntil = b.LockedUntil
	return m0
}

type VouchSetRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Who    *VouchWho              `protobuf:"bytes,1,opt,name=who"`
	xxx_hidden_Kind   string                 `protobuf:"bytes,8,opt,name=kind"`
	xxx_hidden_Secret []byte                 `protobuf:"bytes,9,opt,name=secret"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VouchSetRequest) Reset() {
	*x = VouchSetRequest{}
	mi := &file_app_vouch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchSetRequest) ProtoMessage() {}

func (x *VouchSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchSetRequest) GetWho() *VouchWho {
	if x != nil {
		return x.xxx_hidden_Who
	}
	return nil
}

func (x *VouchSetRequest) GetKind() string {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return ""
}

func (x *VouchSetRequest) GetSecret() []byte {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *VouchSetRequest) SetWho(v *VouchWho) {
	x.xxx_hidden_Who = v
}

func (x *VouchSetRequest) SetKind(v string) {
	x.xxx_hidden_Kind = v
}

func (x *VouchSetRequest) SetSecret(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Secret = v
}

func (x *VouchSetRequest) HasWho() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Who != nil
}

func (x *VouchSetRequest) ClearWho() {
	x.xxx_hidden_Who = nil
}

type VouchSetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Who    *VouchWho
	Kind   string
	Secret []byte
}

func (b0 VouchSetRequest_builder) Build() *VouchSetRequest {
	m0 := &VouchSetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Who = b.Who
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type VouchSetResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VouchSetResponse) Reset() {
	*x = VouchSetResponse{}
	mi := &file_app_vouch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchSetResponse) ProtoMessage() {}

func (x *VouchSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type VouchSetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 VouchSetResponse_builder) Build() *VouchSetResponse {
	m0 := &VouchSetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type VouchDelegateRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Who     *VouchWho              `protobuf:"bytes,1,opt,name=who"`
	xxx_hidden_Kind    string                 `protobuf:"bytes,8,opt,name=kind"`
	xxx_hidden_Secret  []byte                 `protobuf:"bytes,9,opt,name=secret"`
	xxx_hidden_Methods []string               `protobuf:"bytes,10,rep,name=methods"`
	xxx_hidden_Expires *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VouchDelegateRequest) Reset() {
	*x = VouchDelegateRequest{}
	mi := &file_app_vouch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchDelegateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchDelegateRequest) ProtoMessage() {}

func (x *VouchDelegateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchDelegateRequest) GetWho() *VouchWho {
	if x != nil {
		return x.xxx_hidden_Who
	}
	return nil
}

func (x *VouchDelegateRequest) GetKind() string {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return ""
}

func (x *VouchDelegateRequest) GetSecret() []byte {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *VouchDelegateRequest) GetMethods() []string {
	if x != nil {
		return x.xxx_hidden_Methods
	}
	return nil
}

func (x *VouchDelegateRequest) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Expires
	}
	return nil
}

func (x *VouchDelegateRequest) SetWho(v *VouchWho) {
	x.xxx_hidden_Who = v
}

func (x *VouchDelegateRequest) SetKind(v string) {
	x.xxx_hidden_Kind = v
}

func (x *VouchDelegateRequest) SetSecret(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Secret = v
}

func (x *VouchDelegateRequest) SetMethods(v []string) {
	x.xxx_hidden_Methods = v
}

func (x *VouchDelegateRequest) SetExpires(v *timestamppb.Timestamp) {
	x.xxx_hidden_Expires = v
}

func (x *VouchDelegateRequest) HasWho() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Who != nil
}

func (x *VouchDelegateRequest) HasExpires() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Expires != nil
}

func (x *VouchDelegateRequest) ClearWho() {
	x.xxx_hidden_Who = nil
}

func (x *VouchDelegateRequest) ClearExpires() {
	x.xxx_hidden_Expires = nil
}

type VouchDelegateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Who    *VouchWho
	Kind   string
	Secret []byte
	// What the delegation may be used for, in full:
	// "/roster.IdentityService/List".
	//
	// Refused when empty, the way `roster key add --allow` is: everything hands
	// out more than was asked for, and nothing mints a credential that silently
	// does not work.
	//
	// **No wider than the caller.** Each of these has to be covered by what the
	// calling key itself may do -- otherwise an app allowed only to check
	// passwords could mint a token that erases holders and use it through
	// somebody who may. The check bites exactly as hard as the caller's own
	// credential is narrow: under `auth.Plain` or mTLS a caller carries
	// `frame.Whole`, so it refuses nothing, because there is nothing there to be
	// wider than.
	//
	// It is checked **before the secret is compared**, which is not a detail. Run
	// after, a caller that over-asks would get one answer for a wrong password
	// and another for a right one -- D14's equal-cost refusal undone as a status
	// code, which is worse than a timing leak because it is exact.
	Methods []string
	// When it stops working, and unset takes this deployment's default.
	//
	// A moment rather than a duration, because the caller is the one that knows:
	// a delegation is held for a session and the app is what decides when that
	// ends. roster has no opinion to impose -- it does not hold the truth of
	// anybody's session -- so there is no cap here, and the safety is elsewhere:
	// it is never wider than the person, and it is worth nothing without the key
	// it was minted for.
	//
	// A time in the past is refused rather than clamped.
	Expires *timestamppb.Timestamp
}

func (b0 VouchDelegateRequest_builder) Build() *VouchDelegateRequest {
	m0 := &VouchDelegateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Who = b.Who
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Secret = b.Secret
	x.xxx_hidden_Methods = b.Methods
	x.xxx_hidden_Expires = b.Expires
	return m0
}

type VouchDelegateResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Verified *VouchVerifyResponse   `protobuf:"bytes,1,opt,name=verified"`
	xxx_hidden_Token    string                 `protobuf:"bytes,10,opt,name=token"`
	xxx_hidden_Expires  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *VouchDelegateResponse) Reset() {
	*x = VouchDelegateResponse{}
	mi := &file_app_vouch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchDelegateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchDelegateResponse) ProtoMessage() {}

func (x *VouchDelegateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchDelegateResponse) GetVerified() *VouchVerifyResponse {
	if x != nil {
		return x.xxx_hidden_Verified
	}
	return nil
}

func (x *VouchDelegateResponse) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *VouchDelegateResponse) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Expires
	}
	return nil
}

func (x *VouchDelegateResponse) SetVerified(v *VouchVerifyResponse) {
	x.xxx_hidden_Verified = v
}

func (x *VouchDelegateResponse) SetToken(v string) {
	x.xxx_hidden_Token = v
}

func (x *VouchDelegateResponse) SetExpires(v *timestamppb.Timestamp) {
	x.xxx_hidden_Expires = v
}

func (x *VouchDelegateResponse) HasVerified() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Verified != nil
}

func (x *VouchDelegateResponse) HasExpires() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Expires != nil
}

func (x *VouchDelegateResponse) ClearVerified() {
	x.xxx_hidden_Verified = nil
}

func (x *VouchDelegateResponse) ClearExpires() {
	x.xxx_hidden_Expires = nil
}

type VouchDelegateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The same answer `Verify` gives, because it is the same question asked
	// first: `ok`, who it was, and a lockout if there is one.
	//
	// Nested rather than copied so that the two cannot drift. An app that already
	// reads a `Verify` reads this with the code it has.
	Verified *VouchVerifyResponse
	// The delegation, and the only time it is ever readable. What is stored is a
	// hash, for the reason every password store has one.
	//
	// Set only when `verified.ok`. It does **not** go in `authorization`: it says
	// who a call is *about* while the caller goes on saying who they are, and it
	// travels in `roster-as` beside the key it was minted for. See
	// `keys.HeaderActing` for why that is what makes it bindable at all.
	Token string
	// When it stops working, which is always set when a token is.
	Expires *timestamppb.Timestamp
}

func (b0 VouchDelegateResponse_builder) Build() *VouchDelegateResponse {
	m0 := &VouchDelegateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Verified = b.Verified
	x.xxx_hidden_Token = b.Token
	x.xxx_hidden_Expires = b.Expires
	return m0
}

type VouchEnrolRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Who    *VouchWho              `protobuf:"bytes,1,opt,name=who"`
	xxx_hidden_Kind   string                 `protobuf:"bytes,8,opt,name=kind"`
	xxx_hidden_Name   string                 `protobuf:"bytes,5,opt,name=name"`
	xxx_hidden_Issuer string                 `protobuf:"bytes,9,opt,name=issuer"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VouchEnrolRequest) Reset() {
	*x = VouchEnrolRequest{}
	mi := &file_app_vouch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchEnrolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchEnrolRequest) ProtoMessage() {}

func (x *VouchEnrolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchEnrolRequest) GetWho() *VouchWho {
	if x != nil {
		return x.xxx_hidden_Who
	}
	return nil
}

func (x *VouchEnrolRequest) GetKind() string {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return ""
}

func (x *VouchEnrolRequest) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *VouchEnrolRequest) GetIssuer() string {
	if x != nil {
		return x.xxx_hidden_Issuer
	}
	return ""
}

func (x *VouchEnrolRequest) SetWho(v *VouchWho) {
	x.xxx_hidden_Who = v
}

func (x *VouchEnrolRequest) SetKind(v string) {
	x.xxx_hidden_Kind = v
}

func (x *VouchEnrolRequest) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *VouchEnrolRequest) SetIssuer(v string) {
	x.xxx_hidden_Issuer = v
}

func (x *VouchEnrolRequest) HasWho() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Who != nil
}

func (x *VouchEnrolRequest) ClearWho() {
	x.xxx_hidden_Who = nil
}

type VouchEnrolRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Who *VouchWho
	// Which kind. Only "totp" today: a password is `Set` or `Reset`, and neither
	// of those is something a person's phone holds.
	Kind string
	// What they call it, when there is more than one to tell apart -- "the
	// phone", "the yubikey in the drawer". Empty is the only one of its kind.
	Name string
	// What the authenticator app shows in its list, and it is the deployment's
	// name rather than the tenant's: a person with accounts at two operators
	// needs to tell the two entries apart, and both are this roster.
	Issuer string
}

func (b0 VouchEnrolRequest_builder) Build() *VouchEnrolRequest {
	m0 := &VouchEnrolRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Who = b.Who
	x.xxx_hidden_Kind = b.Kind
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Issuer = b.Issuer
	return m0
}

type VouchEnrolResponse struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Seed string                 `protobuf:"bytes,1,opt,name=seed"`
	xxx_hidden_Uri  string                 `protobuf:"bytes,2,opt,name=uri"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VouchEnrolResponse) Reset() {
	*x = VouchEnrolResponse{}
	mi := &file_app_vouch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchEnrolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchEnrolResponse) ProtoMessage() {}

func (x *VouchEnrolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchEnrolResponse) GetSeed() string {
	if x != nil {
		return x.xxx_hidden_Seed
	}
	return ""
}

func (x *VouchEnrolResponse) GetUri() string {
	if x != nil {
		return x.xxx_hidden_Uri
	}
	return ""
}

func (x *VouchEnrolResponse) SetSeed(v string) {
	x.xxx_hidden_Seed = v
}

func (x *VouchEnrolResponse) SetUri(v string) {
	x.xxx_hidden_Uri = v
}

type VouchEnrolResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The seed, base32, uppercase and unpadded -- the only time it is readable.
	//
	// Padding is legal and some apps refuse it, which is the sort of thing only
	// discovered in front of a phone that will not scan.
	Seed string
	// The same thing as a QR code's worth of URI.
	Uri string
}

func (b0 VouchEnrolResponse_builder) Build() *VouchEnrolResponse {
	m0 := &VouchEnrolResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Seed = b.Seed
	x.xxx_hidden_Uri = b.Uri
	return m0
}

type VouchRevokeRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token string                 `protobuf:"bytes,1,opt,name=token"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VouchRevokeRequest) Reset() {
	*x = VouchRevokeRequest{}
	mi := &file_app_vouch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchRevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchRevokeRequest) ProtoMessage() {}

func (x *VouchRevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchRevokeRequest) GetToken() string {
	if x != nil {
		return x.xxx_hidden_Token
	}
	return ""
}

func (x *VouchRevokeRequest) SetToken(v string) {
	x.xxx_hidden_Token = v
}

type VouchRevokeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The delegation to end, as it was handed over.
	Token string
}

func (b0 VouchRevokeRequest_builder) Build() *VouchRevokeRequest {
	m0 := &VouchRevokeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Token = b.Token
	return m0
}

type VouchRevokeResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VouchRevokeResponse) Reset() {
	*x = VouchRevokeResponse{}
	mi := &file_app_vouch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchRevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchRevokeResponse) ProtoMessage() {}

func (x *VouchRevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type VouchRevokeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 VouchRevokeResponse_builder) Build() *VouchRevokeResponse {
	m0 := &VouchRevokeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type VouchResetRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Who  *VouchWho              `protobuf:"bytes,1,opt,name=who"`
	xxx_hidden_Kind string                 `protobuf:"bytes,8,opt,name=kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VouchResetRequest) Reset() {
	*x = VouchResetRequest{}
	mi := &file_app_vouch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchResetRequest) ProtoMessage() {}

func (x *VouchResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchResetRequest) GetWho() *VouchWho {
	if x != nil {
		return x.xxx_hidden_Who
	}
	return nil
}

func (x *VouchResetRequest) GetKind() string {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return ""
}

func (x *VouchResetRequest) SetWho(v *VouchWho) {
	x.xxx_hidden_Who = v
}

func (x *VouchResetRequest) SetKind(v string) {
	x.xxx_hidden_Kind = v
}

func (x *VouchResetRequest) HasWho() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Who != nil
}

func (x *VouchResetRequest) ClearWho() {
	x.xxx_hidden_Who = nil
}

type VouchResetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Who *VouchWho
	// Which secret, and empty means "password" as everywhere else. A kind that
	// is not a password is refused: there is nothing sensible to generate for a
	// TOTP seed that the person could then read out.
	Kind string
}

func (b0 VouchResetRequest_builder) Build() *VouchResetRequest {
	m0 := &VouchResetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Who = b.Who
	x.xxx_hidden_Kind = b.Kind
	return m0
}

type VouchResetResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret string                 `protobuf:"bytes,1,opt,name=secret"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VouchResetResponse) Reset() {
	*x = VouchResetResponse{}
	mi := &file_app_vouch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchResetResponse) ProtoMessage() {}

func (x *VouchResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchResetResponse) GetSecret() string {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return ""
}

func (x *VouchResetResponse) SetSecret(v string) {
	x.xxx_hidden_Secret = v
}

type VouchResetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Shown once and not stored. What is stored is an argon2id hash, so this
	// deployment cannot tell anybody what theirs was any more than it can tell
	// them their key.
	Secret string
}

func (b0 VouchResetResponse_builder) Build() *VouchResetResponse {
	m0 := &VouchResetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type VouchUnlockRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Who  *VouchWho              `protobuf:"bytes,1,opt,name=who"`
	xxx_hidden_Kind string                 `protobuf:"bytes,8,opt,name=kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VouchUnlockRequest) Reset() {
	*x = VouchUnlockRequest{}
	mi := &file_app_vouch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchUnlockRequest) ProtoMessage() {}

func (x *VouchUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchUnlockRequest) GetWho() *VouchWho {
	if x != nil {
		return x.xxx_hidden_Who
	}
	return nil
}

func (x *VouchUnlockRequest) GetKind() string {
	if x != nil {
		return x.xxx_hidden_Kind
	}
	return ""
}

func (x *VouchUnlockRequest) SetWho(v *VouchWho) {
	x.xxx_hidden_Who = v
}

func (x *VouchUnlockRequest) SetKind(v string) {
	x.xxx_hidden_Kind = v
}

func (x *VouchUnlockRequest) HasWho() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Who != nil
}

func (x *VouchUnlockRequest) ClearWho() {
	x.xxx_hidden_Who = nil
}

type VouchUnlockRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Who  *VouchWho
	Kind string
}

func (b0 VouchUnlockRequest_builder) Build() *VouchUnlockRequest {
	m0 := &VouchUnlockRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Who = b.Who
	x.xxx_hidden_Kind = b.Kind
	return m0
}

type VouchUnlockResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_WasLockedUntil *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=was_locked_until,json=wasLockedUntil"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *VouchUnlockResponse) Reset() {
	*x = VouchUnlockResponse{}
	mi := &file_app_vouch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VouchUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VouchUnlockResponse) ProtoMessage() {}

func (x *VouchUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_vouch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VouchUnlockResponse) GetWasLockedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_WasLockedUntil
	}
	return nil
}

func (x *VouchUnlockResponse) SetWasLockedUntil(v *timestamppb.Timestamp) {
	x.xxx_hidden_WasLockedUntil = v
}

func (x *VouchUnlockResponse) HasWasLockedUntil() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_WasLockedUntil != nil
}

func (x *VouchUnlockResponse) ClearWasLockedUntil() {
	x.xxx_hidden_WasLockedUntil = nil
}

type VouchUnlockResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// When they were locked until, and unset for an account that was already
	// open. Answered rather than swallowed so that an operator can tell "I opened
	// it" from "it was not closed" -- which is the question they are about to be
	// asked by whoever called them.
	WasLockedUntil *timestamppb.Timestamp
}

func (b0 VouchUnlockResponse_builder) Build() *VouchUnlockResponse {
	m0 := &VouchUnlockResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_WasLockedUntil = b.WasLockedUntil
	return m0
}

var File_app_vouch_proto protoreflect.FileDescriptor

const file_app_vouch_proto_rawDesc = "" +
	"\n" +
	"\x0fapp/vouch.proto\x12\x06roster\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\bVouchWho\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\"d\n" +
	"\x12VouchVerifyRequest\x12\"\n" +
	"\x03who\x18\x01 \x01(\v2\x10.roster.VouchWhoR\x03who\x12\x12\n" +
	"\x04kind\x18\b \x01(\tR\x04kind\x12\x16\n" +
	"\x06secret\x18\t \x01(\fR\x06secret\"\x94\x01\n" +
	"\x13VouchVerifyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\fR\x06holder\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\fR\x06tenant\x12=\n" +
	"\flocked_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlockedUntil\"a\n" +
	"\x0fVouchSetRequest\x12\"\n" +
	"\x03who\x18\x01 \x01(\v2\x10.roster.VouchWhoR\x03who\x12\x12\n" +
	"\x04kind\x18\b \x01(\tR\x04kind\x12\x16\n" +
	"\x06secret\x18\t \x01(\fR\x06secret\"\x12\n" +
	"\x10VouchSetResponse\"\xb6\x01\n" +
	"\x14VouchDelegateRequest\x12\"\n" +
	"\x03who\x18\x01 \x01(\v2\x10.roster.VouchWhoR\x03who\x12\x12\n" +
	"\x04kind\x18\b \x01(\tR\x04kind\x12\x16\n" +
	"\x06secret\x18\t \x01(\fR\x06secret\x12\x18\n" +
	"\amethods\x18\n" +
	" \x03(\tR\amethods\x124\n" +
	"\aexpires\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\"\x9c\x01\n" +
	"\x15VouchDelegateResponse\x127\n" +
	"\bverified\x18\x01 \x01(\v2\x1b.roster.VouchVerifyResponseR\bverified\x12\x14\n" +
	"\x05token\x18\n" +
	" \x01(\tR\x05token\x124\n" +
	"\aexpires\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\"w\n" +
	"\x11VouchEnrolRequest\x12\"\n" +
	"\x03who\x18\x01 \x01(\v2\x10.roster.VouchWhoR\x03who\x12\x12\n" +
	"\x04kind\x18\b \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06issuer\x18\t \x01(\tR\x06issuer\":\n" +
	"\x12VouchEnrolResponse\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\tR\x04seed\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\"*\n" +
	"\x12VouchRevokeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x15\n" +
	"\x13VouchRevokeResponse\"K\n" +
	"\x11VouchResetRequest\x12\"\n" +
	"\x03who\x18\x01 \x01(\v2\x10.roster.VouchWhoR\x03who\x12\x12\n" +
	"\x04kind\x18\b \x01(\tR\x04kind\",\n" +
	"\x12VouchResetResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\"L\n" +
	"\x12VouchUnlockRequest\x12\"\n" +
	"\x03who\x18\x01 \x01(\v2\x10.roster.VouchWhoR\x03who\x12\x12\n" +
	"\x04kind\x18\b \x01(\tR\x04kind\"[\n" +
	"\x13VouchUnlockResponse\x12D\n" +
	"\x10was_locked_until\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0ewasLockedUntil2\xda\x03\n" +
	"\fVouchService\x12A\n" +
	"\x06Verify\x12\x1a.roster.VouchVerifyRequest\x1a\x1b.roster.VouchVerifyResponse\x128\n" +
	"\x03Set\x12\x17.roster.VouchSetRequest\x1a\x18.roster.VouchSetResponse\x12G\n" +
	"\bDelegate\x12\x1c.roster.VouchDelegateRequest\x1a\x1d.roster.VouchDelegateResponse\x12>\n" +
	"\x05Reset\x12\x19.roster.VouchResetRequest\x1a\x1a.roster.VouchResetResponse\x12A\n" +
	"\x06Unlock\x12\x1a.roster.VouchUnlockRequest\x1a\x1b.roster.VouchUnlockResponse\x12>\n" +
	"\x05Enrol\x12\x19.roster.VouchEnrolRequest\x1a\x1a.roster.VouchEnrolResponse\x12A\n" +
	"\x06Revoke\x12\x1a.roster.VouchRevokeRequest\x1a\x1b.roster.VouchRevokeResponseB&Z\x1fgithub.com/lesomnus/roster/rstr\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_app_vouch_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_app_vouch_proto_goTypes = []any{
	(*VouchWho)(nil),              // 0: roster.VouchWho
	(*VouchVerifyRequest)(nil),    // 1: roster.VouchVerifyRequest
	(*VouchVerifyResponse)(nil),   // 2: roster.VouchVerifyResponse
	(*VouchSetRequest)(nil),       // 3: roster.VouchSetRequest
	(*VouchSetResponse)(nil),      // 4: roster.VouchSetResponse
	(*VouchDelegateRequest)(nil),  // 5: roster.VouchDelegateRequest
	(*VouchDelegateResponse)(nil), // 6: roster.VouchDelegateResponse
	(*VouchEnrolRequest)(nil),     // 7: roster.VouchEnrolRequest
	(*VouchEnrolResponse)(nil),    // 8: roster.VouchEnrolResponse
	(*VouchRevokeRequest)(nil),    // 9: roster.VouchRevokeRequest
	(*VouchRevokeResponse)(nil),   // 10: roster.VouchRevokeResponse
	(*VouchResetRequest)(nil),     // 11: roster.VouchResetRequest
	(*VouchResetResponse)(nil),    // 12: roster.VouchResetResponse
	(*VouchUnlockRequest)(nil),    // 13: roster.VouchUnlockRequest
	(*VouchUnlockResponse)(nil),   // 14: roster.VouchUnlockResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_app_vouch_proto_depIdxs = []int32{
	0,  // 0: roster.VouchVerifyRequest.who:type_name -> roster.VouchWho
	15, // 1: roster.VouchVerifyResponse.locked_until:type_name -> google.protobuf.Timestamp
	0,  // 2: roster.VouchSetRequest.who:type_name -> roster.VouchWho
	0,  // 3: roster.VouchDelegateRequest.who:type_name -> roster.VouchWho
	15, // 4: roster.VouchDelegateRequest.expires:type_name -> google.protobuf.Timestamp
	2,  // 5: roster.VouchDelegateResponse.verified:type_name -> roster.VouchVerifyResponse
	15, // 6: roster.VouchDelegateResponse.expires:type_name -> google.protobuf.Timestamp
	0,  // 7: roster.VouchEnrolRequest.who:type_name -> roster.VouchWho
	0,  // 8: roster.VouchResetRequest.who:type_name -> roster.VouchWho
	0,  // 9: roster.VouchUnlockRequest.who:type_name -> roster.VouchWho
	15, // 10: roster.VouchUnlockResponse.was_locked_until:type_name -> google.protobuf.Timestamp
	1,  // 11: roster.VouchService.Verify:input_type -> roster.VouchVerifyRequest
	3,  // 12: roster.VouchService.Set:input_type -> roster.VouchSetRequest
	5,  // 13: roster.VouchService.Delegate:input_type -> roster.VouchDelegateRequest
	11, // 14: roster.VouchService.Reset:input_type -> roster.VouchResetRequest
	13, // 15: roster.VouchService.Unlock:input_type -> roster.VouchUnlockRequest
	7,  // 16: roster.VouchService.Enrol:input_type -> roster.VouchEnrolRequest
	9,  // 17: roster.VouchService.Revoke:input_type -> roster.VouchRevokeRequest
	2,  // 18: roster.VouchService.Verify:output_type -> roster.VouchVerifyResponse
	4,  // 19: roster.VouchService.Set:output_type -> roster.VouchSetResponse
	6,  // 20: roster.VouchService.Delegate:output_type -> roster.VouchDelegateResponse
	12, // 21: roster.VouchService.Reset:output_type -> roster.VouchResetResponse
	14, // 22: roster.VouchService.Unlock:output_type -> roster.VouchUnlockResponse
	8,  // 23: roster.VouchService.Enrol:output_type -> roster.VouchEnrolResponse
	10, // 24: roster.VouchService.Revoke:output_type -> roster.VouchRevokeResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_app_vouch_proto_init() }
func file_app_vouch_proto_init() {
	if File_app_vouch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_vouch_proto_rawDesc), len(file_app_vouch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_vouch_proto_goTypes,
		DependencyIndexes: file_app_vouch_proto_depIdxs,
		MessageInfos:      file_app_vouch_proto_msgTypes,
	}.Build()
	File_app_vouch_proto = out.File
	file_app_vouch_proto_goTypes = nil
	file_app_vouch_proto_depIdxs = nil
}
